vulns v3 push

diff --git a/bin/rftw_vuln_brokenlink b/bin/rftw_vuln_brokenlink
--- a/bin/rftw_vuln_brokenlink
+++ b/bin/rftw_vuln_brokenlink
@@ -4,60 +4,78 @@
 CONFIG_PATH="${RECONFTW_CFG}"
 
 # Check if the config file exists
-if [[ -f "${CONFIG_PATH}" ]]; then
-    source "${CONFIG_PATH}"
+if [[ -f ${CONFIG_PATH} ]]; then
+	source "${CONFIG_PATH}"
 else
-    echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
-    exit 1
+	echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
+	exit 1
 fi
 
 # Help menu
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo "Broken Links Check using katana and axiom"
-	echo ""
-	echo "Options:"
-	echo "  -d, --deep              Set deep mode (optional)"
-	echo "  -h, --help              Display this help message and exit"
-	exit 0
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation
-DEEP_MODE=false
-while [[ $1 != "" ]]; do
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	deep_mode="False"
 	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
+		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
 	-d | --deep)
-		DEEP_MODE=true
+		deep_mode="True"
+		shift
 		;;
-	-h | --help)
-		help_menu
-		exit
-		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown option: $1"
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
 	shift
 done
 
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+mkdir -p .tmp 2>/dev/null
+
 broken_links_check() {
 	local deep_mode=$1
 
 		# The code remains mostly unchanged, with only minor adjustments for clarity.
-		[[ ! -s ".tmp/webs_all.txt" ]] && cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null | anew -q .tmp/webs_all.txt
 		if [[ ! ${AXIOM} == true ]]; then
 			depth_level=$([[ "$deep_mode" = true ]] && echo 3 || echo 2)
-			[[ -s ".tmp/webs_all.txt" ]] && katana -silent -list .tmp/webs_all.txt -jc -kf all -c $KATANA_THREADS -d $depth_level -o .tmp/katana.txt
-			[[ -s ".tmp/katana.txt" ]] && sed -i '/^.\{2048\}./d' .tmp/katana.txt
+			[[ -s "${input_file}" ]] && katana -silent -list ${input_file} -jc -kf all -c $KATANA_THREADS -d $depth_level -o ${output_dir}/katana.txt
+			[[ -s "${output_dir}/katana.txt" ]] && sed -i '/^.\{2048\}./d' ${output_dir}/katana.txt
 		else
 			depth_level=$([[ "$deep_mode" = true ]] && echo 3 || echo 2)
-			[[ -s ".tmp/webs_all.txt" ]] && axiom-scan .tmp/webs_all.txt -m katana -jc -kf all -d $depth_level -o .tmp/katana.txt "${AXIOM_EXTRA_ARGS}"
-			[[ -s ".tmp/katana.txt" ]] && sed -i '/^.\{2048\}./d' .tmp/katana.txt
+			[[ -s "${input_file}" ]] && axiom-scan ${input_file} -m katana -jc -kf all -d $depth_level -o ${output_dir}/katana.txt "${AXIOM_EXTRA_ARGS}"
+			[[ -s "${output_dir}/katana.txt" ]] && sed -i '/^.\{2048\}./d' ${output_dir}/katana.txt
 		fi
-		[[ -s ".tmp/katana.txt" ]] && cat .tmp/katana.txt | sort -u | httpx -follow-redirects -random-agent -status-code -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -timeout $HTTPX_TIMEOUT -silent -retries 2 -no-color | grep "\[4" | cut -d ' ' -f1 | anew -q .tmp/brokenLinks_total.txt
-		NUMOFLINES=$(cat .tmp/brokenLinks_total.txt | anew vulns/brokenLinks.txt | sed '/^$/d' | wc -l)
-		notification "${NUMOFLINES} new broken links found" info
+		[[ -s "${output_dir}/katana.txt" ]] && cat ${output_dir}/katana.txt | sort -u | httpx -follow-redirects -random-agent -status-code -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -timeout $HTTPX_TIMEOUT -silent -retries 2 -no-color | grep "\[4" | cut -d ' ' -f1 | anew -q ${output_dir}/brokenLinks_total.txt
 
 }
 
diff --git a/bin/rftw_vuln_ssrf b/bin/rftw_vuln_ssrf
--- a/bin/rftw_vuln_ssrf
+++ b/bin/rftw_vuln_ssrf
@@ -4,35 +4,63 @@
 CONFIG_PATH="${RECONFTW_CFG}"
 
 # Check if the config file exists
-if [[ -f "${CONFIG_PATH}" ]]; then
-    source "${CONFIG_PATH}"
+if [[ -f ${CONFIG_PATH} ]]; then
+	source "${CONFIG_PATH}"
 else
-    echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
-    exit 1
+	echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
+	exit 1
 fi
 
 # Help menu
-function display_help() {
-	echo "$(basename "$0") [OPTIONS]"
+display_help() {
+	echo "$(basename "$0") [Options]"
 	echo
-	echo "Perform SSRF checks on provided inputs."
-	echo "Options:"
-	echo "  -d, --deep    Perform deep scanning"
-	echo "  -h, --help    Display this help and exit"
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
 	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Validate the required tools and files
-function validate_requirements() {
-	if ! [[ -x "$(command -v python3)" ]]; then
-		echo "Error: python3 is not installed." >&2
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	deep_flag="False"
+	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
+		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-d | --deep)
+		deep_flag="True"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
 		exit 1
-	fi
-	if [[ ! -f "${tools}/Oralyzer/oralyzer.py" ]]; then
-		echo "Error: Oralyzer tool is missing." >&2
-		exit 1
-	fi
-}
+		;;
+	esac
+	shift
+done
+
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+mkdir -p .tmp 2>/dev/null
 
 # Main SSRF checks function
 function ssrf_checks() {
@@ -49,19 +77,19 @@ function ssrf_checks() {
 		COLLAB_SERVER_FIX="FFUFHASH.$(echo ${COLLAB_SERVER} | sed -r "s/https?:\/\///")"
 		INTERACT=false
 	fi
-	if [[ $deep_flag == true ]] || [[ $(cat gf/ssrf.txt | wc -l) -le $DEEP_LIMIT ]]; then
-		cat gf/ssrf.txt | qsreplace ${COLLAB_SERVER_FIX} | anew -q .tmp/tmp_ssrf.txt
-		cat gf/ssrf.txt | qsreplace ${COLLAB_SERVER_URL} | anew -q .tmp/tmp_ssrf.txt
-		ffuf -v -H "${HEADER}" -t $FFUF_THREADS -rate $FFUF_RATELIMIT -w .tmp/tmp_ssrf.txt -u FUZZ 2>/dev/null | grep "URL" | sed 's/| URL | //' | anew -q vulns/ssrf_requested_url.txt
-		ffuf -v -w .tmp/tmp_ssrf.txt:W1,$tools/headers_inject.txt:W2 -H "${HEADER}" -H "W2: ${COLLAB_SERVER_FIX}" -t $FFUF_THREADS -rate $FFUF_RATELIMIT -u W1 2>/dev/null | anew -q vulns/ssrf_requested_headers.txt
-		ffuf -v -w .tmp/tmp_ssrf.txt:W1,$tools/headers_inject.txt:W2 -H "${HEADER}" -H "W2: ${COLLAB_SERVER_URL}" -t $FFUF_THREADS -rate $FFUF_RATELIMIT -u W1 2>/dev/null | anew -q vulns/ssrf_requested_headers.txt
+	if [[ $deep_flag == true ]] || [[ $(cat ${input_file} | wc -l) -le $DEEP_LIMIT ]]; then
+		cat ${input_file} | qsreplace ${COLLAB_SERVER_FIX} | anew -q .tmp/tmp_ssrf.txt
+		cat ${input_file} | qsreplace ${COLLAB_SERVER_URL} | anew -q .tmp/tmp_ssrf.txt
+		ffuf -v -H "${HEADER}" -t $FFUF_THREADS -rate $FFUF_RATELIMIT -w .tmp/tmp_ssrf.txt -u FUZZ 2>/dev/null | grep "URL" | sed 's/| URL | //' | anew -q ${input_file}/ssrf_requested_url.txt
+		ffuf -v -w .tmp/tmp_ssrf.txt:W1,$tools/headers_inject.txt:W2 -H "${HEADER}" -H "W2: ${COLLAB_SERVER_FIX}" -t $FFUF_THREADS -rate $FFUF_RATELIMIT -u W1 2>/dev/null | anew -q ${input_file}/ssrf_requested_headers.txt
+		ffuf -v -w .tmp/tmp_ssrf.txt:W1,$tools/headers_inject.txt:W2 -H "${HEADER}" -H "W2: ${COLLAB_SERVER_URL}" -t $FFUF_THREADS -rate $FFUF_RATELIMIT -u W1 2>/dev/null | anew -q ${input_file}/ssrf_requested_headers.txt
 		sleep 5
 		if [[ -s ".tmp/ssrf_callback.txt" ]]; then
-			cat .tmp/ssrf_callback.txt | tail -n+11 | anew -q vulns/ssrf_callback.txt
+			cat .tmp/ssrf_callback.txt | tail -n+11 | anew -q ${input_file}/ssrf_callback.txt
 			NUMOFLINES=$(cat .tmp/ssrf_callback.txt | tail -n+12 | sed '/^$/d' | wc -l)
 			[[ $INTERACT == true ]] && echo "SSRF: ${NUMOFLINES} callbacks received"
 		fi
-		echo "[+] Results are saved in vulns/ssrf_*"
+		echo "[+] Results are saved in ${input_file}/ssrf_*"
 	else
 		echo "[!] Skipping SSRF: Too many URLs to test, try with --deep flag"
 	fi
@@ -69,26 +97,5 @@ function ssrf_checks() {
 
 }
 
-# Main script execution
-deep_flag=false
 
-while (("$#")); do
-	case "$1" in
-	-d | --deep)
-		deep_flag=true
-		shift
-		;;
-	-h | --help)
-		display_help
-		exit 0
-		;;
-	*)
-		echo "Unknown parameter passed: $1"
-		display_help
-		exit 1
-		;;
-	esac
-done
-
-validate_requirements
-ssrf_checks $deep_flag
+ssrf_checks
diff --git a/bin/rftw_vuln_xss b/bin/rftw_vuln_xss
--- a/bin/rftw_vuln_xss
+++ b/bin/rftw_vuln_xss
@@ -4,56 +4,84 @@
 CONFIG_PATH="${RECONFTW_CFG}"
 
 # Check if the config file exists
-if [[ -f "${CONFIG_PATH}" ]]; then
-    source "${CONFIG_PATH}"
+if [[ -f ${CONFIG_PATH} ]]; then
+	source "${CONFIG_PATH}"
 else
-    echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
-    exit 1
+	echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
+	exit 1
 fi
 
 # Help menu
-function display_help() {
-	echo "$(basename "$0") [OPTIONS]"
+display_help() {
+	echo "$(basename "$0") [Options]"
 	echo
-	echo "Perform XSS analysis on provided inputs."
-	echo "Options:"
-	echo "  -h, --help    Display this help and exit"
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
 	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Validate the required tools and files
-function validate_requirements() {
-	if ! [[ -x "$(command -v dalfox)" ]]; then
-		echo "Error: dalfox is not installed." >&2
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	deep_mode="False"
+	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
+		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-d | --deep)
+		DEEP="True"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
 		exit 1
-	fi
-	if [[ ! -f "gf/xss.txt" ]]; then
-		echo "Error: gf/xss.txt does not exist." >&2
-		exit 1
-	fi
-}
+		;;
+	esac
+	shift
+done
+
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+mkdir -p .tmp 2>/dev/null
 
 # Main xss function
 function xss_analysis() {
-	echo "[*] Starting XSS Analysis"
-	# Check if gf/xss.txt exists and process it
-	[[ -s "gf/xss.txt" ]] && cat gf/xss.txt | qsreplace FUZZ | sed '/FUZZ/!d' | Gxss -c 100 -p Xss | qsreplace FUZZ | sed '/FUZZ/!d' | anew -q .tmp/xss_reflected.txt
+	# Check if ${input_file} exists and process it
+	[[ -s "${input_file}" ]] && cat ${input_file} | qsreplace FUZZ | sed '/FUZZ/!d' | Gxss -c 100 -p Xss | qsreplace FUZZ | sed '/FUZZ/!d' | anew -q .tmp/xss_reflected.txt
 	# Check if AXIOM is true or not and perform the corresponding operations
 	if [[ ${AXIOM} != true ]]; then
 		if [[ $DEEP == true ]]; then
 			if [[ -n $XSS_SERVER ]]; then
-				[[ -s ".tmp/xss_reflected.txt" ]] && cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --only-poc r --ignore-return 302,404,403 --skip-bav -b ${XSS_SERVER} -w $DALFOX_THREADS | anew -q vulns/xss.txt
+				[[ -s ".tmp/xss_reflected.txt" ]] && cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --only-poc r --ignore-return 302,404,403 --skip-bav -b ${XSS_SERVER} -w $DALFOX_THREADS | anew -q ${output_dir}/xss.txt
 			else
 				printf "${yellow}\n No XSS_SERVER defined, blind xss skipped\n\n"
-				[[ -s ".tmp/xss_reflected.txt" ]] && cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --only-poc r --ignore-return 302,404,403 --skip-bav -w $DALFOX_THREADS | anew -q vulns/xss.txt
+				[[ -s ".tmp/xss_reflected.txt" ]] && cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --only-poc r --ignore-return 302,404,403 --skip-bav -w $DALFOX_THREADS | anew -q ${output_dir}/xss.txt
 			fi
 		else
 			if [[ $(cat .tmp/xss_reflected.txt | wc -l) -le $DEEP_LIMIT ]]; then
 				if [[ -n $XSS_SERVER ]]; then
-					cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --skip-bav --skip-mining-dom --skip-mining-dict --only-poc r --ignore-return 302,404,403 -b ${XSS_SERVER} -w $DALFOX_THREADS | anew -q vulns/xss.txt
+					cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --skip-bav --skip-mining-dom --skip-mining-dict --only-poc r --ignore-return 302,404,403 -b ${XSS_SERVER} -w $DALFOX_THREADS | anew -q ${output_dir}/xss.txt
 				else
 					printf "${yellow}\n No XSS_SERVER defined, blind xss skipped\n\n"
-					cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --skip-bav --skip-mining-dom --skip-mining-dict --only-poc r --ignore-return 302,404,403 -w $DALFOX_THREADS | anew -q vulns/xss.txt
+					cat .tmp/xss_reflected.txt | dalfox pipe --silence --no-color --no-spinner --skip-bav --skip-mining-dom --skip-mining-dict --only-poc r --ignore-return 302,404,403 -w $DALFOX_THREADS | anew -q ${output_dir}/xss.txt
 				fi
 			else
 				printf "${bred} Skipping XSS: Too many URLs to test, try with --deep flag${reset}\n"
@@ -62,47 +90,24 @@ function xss_analysis() {
 	else
 		if [[ $DEEP == true ]]; then
 			if [[ -n $XSS_SERVER ]]; then
-				[[ -s ".tmp/xss_reflected.txt" ]] && axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav -b ${XSS_SERVER} -w $DALFOX_THREADS -o vulns/xss.txt "${AXIOM_EXTRA_ARGS}"
+				[[ -s ".tmp/xss_reflected.txt" ]] && axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav -b ${XSS_SERVER} -w $DALFOX_THREADS -o ${output_dir}/xss.txt "${AXIOM_EXTRA_ARGS}"
 			else
 				printf "${yellow}\n No XSS_SERVER defined, blind xss skipped\n\n"
-				[[ -s ".tmp/xss_reflected.txt" ]] && axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav -w $DALFOX_THREADS -o vulns/xss.txt "${AXIOM_EXTRA_ARGS}"
+				[[ -s ".tmp/xss_reflected.txt" ]] && axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav -w $DALFOX_THREADS -o ${output_dir}/xss.txt "${AXIOM_EXTRA_ARGS}"
 			fi
 		else
 			if [[ $(cat .tmp/xss_reflected.txt | wc -l) -le $DEEP_LIMIT ]]; then
 				if [[ -n $XSS_SERVER ]]; then
-					axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav --skip-grepping --skip-mining-all --skip-mining-dict -b ${XSS_SERVER} -w $DALFOX_THREADS -o vulns/xss.txt "${AXIOM_EXTRA_ARGS}"
+					axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav --skip-grepping --skip-mining-all --skip-mining-dict -b ${XSS_SERVER} -w $DALFOX_THREADS -o ${output_dir}/xss.txt "${AXIOM_EXTRA_ARGS}"
 				else
 					printf "${yellow}\n No XSS_SERVER defined, blind xss skipped\n\n"
-					axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav --skip-grepping --skip-mining-all --skip-mining-dict -w $DALFOX_THREADS -o vulns/xss.txt "${AXIOM_EXTRA_ARGS}"
+					axiom-scan .tmp/xss_reflected.txt -m dalfox --skip-bav --skip-grepping --skip-mining-all --skip-mining-dict -w $DALFOX_THREADS -o ${output_dir}/xss.txt "${AXIOM_EXTRA_ARGS}"
 				fi
 			else
 				printf "${bred} Skipping XSS: Too many URLs to test, try with --deep flag${reset}\n"
 			fi
 		fi
 	fi
-	echo "[+] Results are saved in vulns/xss.txt"
 }
 
-# Main script execution
-if [[ $# -eq 0 ]]; then
-	display_help
-	exit 0
-fi
-
-while (("$#")); do
-	case "$1" in
-	-h | --help)
-		display_help
-		exit 0
-		;;
-	*)
-		echo "Unknown parameter passed: $1"
-		display_help
-		exit 1
-		;;
-	esac
-	shift
-done
-
-validate_requirements
 xss_analysis
diff --git a/bin/rftw_web_jschecks b/bin/rftw_web_jschecks
--- a/bin/rftw_web_jschecks
+++ b/bin/rftw_web_jschecks
@@ -4,11 +4,11 @@
 CONFIG_PATH="${RECONFTW_CFG}"
 
 # Check if the config file exists
-if [[ -f "${CONFIG_PATH}" ]]; then
-    source "${CONFIG_PATH}"
+if [[ -f ${CONFIG_PATH} ]]; then
+	source "${CONFIG_PATH}"
 else
-    echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
-    exit 1
+	echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
+	exit 1
 fi
 
 # Help menu
@@ -58,42 +58,39 @@ fi
 mkdir -p .tmp 2>/dev/null
 
 jschecks() {
-	local DOMAIN=$1
 
-	if [[ -s ".tmp/url_extract_js.txt" ]]; then
-		printf "${yellow} Running : Fetching Urls 1/5${reset}\n"
-		if [[ ${AXIOM} != true ]]; then
-			cat .tmp/url_extract_js.txt | subjs -ua "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -c 40 | grep "${DOMAIN}" | anew -q .tmp/subjslinks.txt
-		else
-			axiom-scan .tmp/url_extract_js.txt -m subjs -o .tmp/subjslinks.txt "${AXIOM_EXTRA_ARGS}"
-		fi
-		[[ -s ".tmp/subjslinks.txt" ]] && cat .tmp/subjslinks.txt | egrep -iv "\.(eot|jpg|jpeg|gif|css|tif|tiff|png|ttf|otf|woff|woff2|ico|pdf|svg|txt|js)" | anew -q js/nojs_links.txt
-		[[ -s ".tmp/subjslinks.txt" ]] && cat .tmp/subjslinks.txt | grep -iE "\.js($|\?)" | anew -q .tmp/url_extract_js.txt
-		cat .tmp/url_extract_js.txt | python3"${tools}"/urless/urless/urless.py | anew -q js/url_extract_js.txt
-		printf "${yellow} Running : Resolving JS Urls 2/5${reset}\n"
-		if [[ ${AXIOM} != true ]]; then
-			[[ -s "js/url_extract_js.txt" ]] && cat js/url_extract_js.txt | httpx -follow-redirects -random-agent -silent -timeout $HTTPX_TIMEOUT -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -status-code -content-type -retries 2 -no-color | grep "[200]" | grep "javascript" | cut -d ' ' -f1 | anew -q js/js_livelinks.txt
-		else
-			[[ -s "js/url_extract_js.txt" ]] && axiom-scan js/url_extract_js.txt -m httpx -follow-host-redirects -H \"${HEADER}\" -status-code -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -timeout $HTTPX_TIMEOUT -silent -content-type -retries 2 -no-color -o .tmp/js_livelinks.txt "${AXIOM_EXTRA_ARGS}"
-			[[ -s ".tmp/js_livelinks.txt" ]] && cat .tmp/js_livelinks.txt | anew .tmp/web_full_info.txt | grep "[200]" | grep "javascript" | cut -d ' ' -f1 | anew -q js/js_livelinks.txt
-		fi
-		printf "${yellow} Running : Gathering endpoints 3/5${reset}\n"
-		[[ -s "js/js_livelinks.txt" ]] && python3"${tools}"/xnLinkFinder/xnLinkFinder.py -i js/js_livelinks.txt -sf subdomains/subdomains.txt -d $XNLINKFINDER_DEPTH -o .tmp/js_endpoints.txt
-		[[ -s "parameters.txt" ]] && rm -f parameters.txt
-		if [[ -s ".tmp/js_endpoints.txt" ]]; then
-			sed -i '/^\//!d' .tmp/js_endpoints.txt
-			cat .tmp/js_endpoints.txt | anew -q js/js_endpoints.txt
-		fi
-		printf "${yellow} Running : Gathering secrets 4/5${reset}\n"
-		if [[ ${AXIOM} != true ]]; then
-			[[ -s "js/js_livelinks.txt" ]] && cat js/js_livelinks.txt | Mantra -ua ${HEADER} -s | anew -q js/js_secrets.txt
-		else
-			[[ -s "js/js_livelinks.txt" ]] && axiom-scan js/js_livelinks.txt -m mantra -ua ${HEADER} -s -o js/js_secrets.txt "${AXIOM_EXTRA_ARGS}" &>/dev/null
-		fi
-		[[ -s "js/js_secrets.txt" ]] && sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" -i js/js_secrets.txt
-		printf "${yellow} Running : Building wordlist 5/5${reset}\n"
-		[[ -s "js/js_livelinks.txt" ]] && interlace -tL js/js_livelinks.txt -threads "${INTERLACE_THREADS}" -c "python3"${tools}"/getjswords.py '_target_' | anew -q webs/dict_words.txt"
+	local DOMAIN=$(cat ${input_file} | head -n1 | unfurl -u apexes)
+	if [[ ${AXIOM} != true ]]; then
+		cat ${input_file} | subjs -ua "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -c 40 | grep "${DOMAIN}" | anew -q .tmp/subjslinks.txt
+	else
+		axiom-scan ${input_file} -m subjs -o .tmp/subjslinks.txt "${AXIOM_EXTRA_ARGS}"
 	fi
+	[[ -s ".tmp/subjslinks.txt" ]] && cat .tmp/subjslinks.txt | egrep -iv "\.(eot|jpg|jpeg|gif|css|tif|tiff|png|ttf|otf|woff|woff2|ico|pdf|svg|txt|js)" | anew -q ${output_dir}/nojs_links.txt
+	[[ -s ".tmp/subjslinks.txt" ]] && cat .tmp/subjslinks.txt | grep -iE "\.js($|\?)" | anew -q ${input_file}
+	cat ${input_file} | python3"${tools}"/urless/urless/urless.py | anew -q ${output_dir}/url_extract_js.txt
+	printf "${yellow} Running : Resolving JS Urls 2/5${reset}\n"
+	if [[ ${AXIOM} != true ]]; then
+		[[ -s "${output_dir}/url_extract_js.txt" ]] && cat ${output_dir}/url_extract_js.txt | httpx -follow-redirects -random-agent -silent -timeout $HTTPX_TIMEOUT -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -status-code -content-type -retries 2 -no-color | grep "[200]" | grep "javascript" | cut -d ' ' -f1 | anew -q ${output_dir}/js_livelinks.txt
+	else
+		[[ -s "${output_dir}/url_extract_js.txt" ]] && axiom-scan ${output_dir}/url_extract_js.txt -m httpx -follow-host-redirects -H \"${HEADER}\" -status-code -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -timeout $HTTPX_TIMEOUT -silent -content-type -retries 2 -no-color -o .tmp/js_livelinks.txt "${AXIOM_EXTRA_ARGS}"
+		[[ -s ".tmp/js_livelinks.txt" ]] && cat .tmp/js_livelinks.txt | anew .tmp/web_full_info.txt | grep "[200]" | grep "javascript" | cut -d ' ' -f1 | anew -q ${output_dir}/js_livelinks.txt
+	fi
+	printf "${yellow} Running : Gathering endpoints 3/5${reset}\n"
+	[[ -s "${output_dir}/js_livelinks.txt" ]] && python3"${tools}"/xnLinkFinder/xnLinkFinder.py -i ${output_dir}/js_livelinks.txt -sf subdomains/subdomains.txt -d $XNLINKFINDER_DEPTH -o .tmp/js_endpoints.txt
+	[[ -s "parameters.txt" ]] && rm -f parameters.txt
+	if [[ -s ".tmp/js_endpoints.txt" ]]; then
+		sed -i '/^\//!d' .tmp/js_endpoints.txt
+		cat .tmp/js_endpoints.txt | anew -q ${output_dir}/js_endpoints.txt
+	fi
+	printf "${yellow} Running : Gathering secrets 4/5${reset}\n"
+	if [[ ${AXIOM} != true ]]; then
+		[[ -s "${output_dir}/js_livelinks.txt" ]] && cat ${output_dir}/js_livelinks.txt | Mantra -ua ${HEADER} -s | anew -q ${output_dir}/js_secrets.txt
+	else
+		[[ -s "${output_dir}/js_livelinks.txt" ]] && axiom-scan ${output_dir}/js_livelinks.txt -m mantra -ua ${HEADER} -s -o ${output_dir}/js_secrets.txt "${AXIOM_EXTRA_ARGS}" &>/dev/null
+	fi
+	[[ -s "${output_dir}/js_secrets.txt" ]] && sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" -i ${output_dir}/js_secrets.txt
+	printf "${yellow} Running : Building wordlist 5/5${reset}\n"
+	[[ -s "${output_dir}/js_livelinks.txt" ]] && interlace -tL ${output_dir}/js_livelinks.txt -threads "${INTERLACE_THREADS}" -c "python3"${tools}"/getjswords.py '_target_' | anew -q webs/dict_words.txt"
 }
 
 jschecks "${DOMAIN}"
diff --git a/bin/rftw_web_passdict b/bin/rftw_web_passdict
--- a/bin/rftw_web_passdict
+++ b/bin/rftw_web_passdict
@@ -12,53 +12,53 @@ else
 fi
 
 # Help menu
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo "Password Dictionary Generation using pydictor"
-	echo ""
-	echo "Options:"
-	echo "  -d, --domain DOMAIN     Set domain (required)"
-	echo "  -h, --help              Display this help message and exit"
-	exit 0
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation
-if [[ $# -eq 0 ]]; then
-	help_menu
-fi
-
-DOMAIN=""
-while [[ $1 != "" ]]; do
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
 	case $1 in
 	-d | --domain)
+		input_domain="$2"
 		shift
-		DOMAIN=$1
 		;;
-	-h | --help)
-		help_menu
-		exit
+	-o | --output)
+		output_dir="$2"
+		shift
 		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown option: $1"
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
 	shift
 done
 
-if [[ -z ${DOMAIN} ]]; then
-	echo "Error: Domain is required!"
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
 	exit 1
 fi
 
 password_dict() {
-	local DOMAIN=$1
-
-	start_func ${FUNCNAME[0]} "Password dictionary generation"
-
-	local word=${DOMAIN%%.*}
+	word=${input_domain%%.*}
 	python3"${tools}"/pydictor/pydictor.py -extend $word --leet 0 1 2 11 21 --len ${PASSWORD_MIN_LENGTH} ${PASSWORD_MAX_LENGTH} -o webs/password_dict.txt
 
 }
 
-password_dict ${DOMAIN}
+password_dict
diff --git a/bin/rftw_web_roboxtractor b/bin/rftw_web_roboxtractor
--- a/bin/rftw_web_roboxtractor
+++ b/bin/rftw_web_roboxtractor
@@ -12,53 +12,55 @@ else
 fi
 
 # Help menu
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo "Robots Wordlist Generation using roboxtractor"
-	echo ""
-	echo "Options:"
-	echo "  -d, --domain DOMAIN     Set domain (required)"
-	echo "  -h, --help              Display this help message and exit"
-	exit 0
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation
-if [[ $# -eq 0 ]]; then
-	help_menu
-fi
-
-DOMAIN=""
-while [[ $1 != "" ]]; do
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
 	case $1 in
-	-d | --domain)
+	-f | --file)
+		input_file="$2"
 		shift
-		DOMAIN=$1
 		;;
-	-h | --help)
-		help_menu
-		exit
+	-o | --output)
+		output_dir="$2"
+		shift
 		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown option: $1"
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
 	shift
 done
 
-if [[ -z ${DOMAIN} ]]; then
-	echo "Error: Domain is required!"
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
 	exit 1
 fi
 
 wordlist_gen_roboxtractor() {
-	local DOMAIN=$1
 
-	[[ ! -s ".tmp/webs_all.txt" ]] && cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null | anew -q .tmp/webs_all.txt
-	if [[ -s ".tmp/webs_all.txt" ]]; then
-		cat .tmp/webs_all.txt | roboxtractor -m 1 -wb 2>/dev/null | anew -q webs/robots_wordlist.txt
+	if [[ -s "${input_file}" ]]; then
+		cat ${input_file} | roboxtractor -m 1 -wb 2>/dev/null | anew -q ${output_dir}/robots_wordlist.txt
 	fi
 
 }
 
-wordlist_gen_roboxtractor ${DOMAIN}
+wordlist_gen_roboxtractor
diff --git a/bin/rftw_web_urlext b/bin/rftw_web_urlext
--- a/bin/rftw_web_urlext
+++ b/bin/rftw_web_urlext
@@ -11,36 +11,49 @@ else
     exit 1
 fi
 
-# Help menu function
-help_menu() {
-	echo "Usage: url_ext.sh [OPTIONS]"
-	echo ""
-	echo "Options:"
-	echo "  -i, --input-file <file>    Specify the input URL file for extraction."
-	echo "  -o, --output-file <file>   Specify the output file for URLs by extension."
-	echo "  -h, --help                 Display this help menu."
-	echo ""
-	echo "Example:"
-	echo "  url_ext.sh -i .tmp/url_extract_tmp.txt -o webs/urls_by_ext.txt"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation function
-validate_input() {
-	if [[ -z ${input_file} ]]; then
-		echo "Error: Input file not specified."
-		help_menu
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
+		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
 		exit 1
-	elif [[ ! -f ${input_file} ]]; then
-		echo "Error: Specified input file does not exist."
-		exit 1
-	fi
+		;;
+	esac
+	shift
+done
 
-	if [[ -z ${output_file} ]]; then
-		echo "Error: Output file not specified."
-		help_menu
-		exit 1
-	fi
-}
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
 
 # Extract URLs by extension function
 url_ext() {
@@ -60,29 +73,6 @@ url_ext() {
 	fi
 }
 
-# Parse command-line arguments
-while [[ $# -gt 0 ]]; do
-	case "$1" in
-	-i | --input-file)
-		input_file="$2"
-		shift 2
-		;;
-	-o | --output-file)
-		output_file="$2"
-		shift 2
-		;;
-	-h | --help)
-		help_menu
-		exit 0
-		;;
-	*)
-		echo "Unknown parameter: $1"
-		help_menu
-		exit 1
-		;;
-	esac
-done
 
 # Validate input and start the main function
-validate_input
 url_ext
diff --git a/bin/rftw_web_urlgf b/bin/rftw_web_urlgf
--- a/bin/rftw_web_urlgf
+++ b/bin/rftw_web_urlgf
@@ -11,68 +11,65 @@ else
     exit 1
 fi
 
-# Help menu function
-help_menu() {
-	echo "Usage: url_gf.sh [OPTIONS]"
-	echo ""
-	echo "Options:"
-	echo "  -u, --url-file <file>   Specify the URL file to scan."
-	echo "  -h, --help             Display this help menu."
-	echo ""
-	echo "Example:"
-	echo "  url_gf.sh -u webs/url_extract.txt"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation function
-validate_input() {
-	if [[ -z $url_file ]]; then
-		echo "Error: URL file not specified."
-		help_menu
-		exit 1
-	elif [[ ! -f $url_file ]]; then
-		echo "Error: Specified URL file does not exist."
-		exit 1
-	fi
-}
-
-# Vulnerable pattern search function
-url_gf() {
-	echo "[+] Starting Vulnerable Pattern Search"
-	mkdir -p gf
-	if [[ -s $url_file ]]; then
-		gf xss "$url_file" | anew -q gf/xss.txt
-		gf ssti "$url_file" | anew -q gf/ssti.txt
-		gf ssrf "$url_file" | anew -q gf/ssrf.txt
-		gf sqli "$url_file" | anew -q gf/sqli.txt
-		gf redirect "$url_file" | anew -q gf/redirect.txt
-		[[ -s "gf/ssrf.txt" ]] && cat gf/ssrf.txt | anew -q gf/redirect.txt
-		gf rce "$url_file" | anew -q gf/rce.txt
-		gf potential "$url_file" | cut -d ':' -f3-5 | anew -q gf/potential.txt
-		[[ -s ".tmp/url_extract_tmp.txt" ]] && cat .tmp/url_extract_tmp.txt | grep -aEiv "\.(eot|jpg|jpeg|gif|css|tif|tiff|png|ttf|otf|woff|woff2|ico|pdf|svg|txt|js)$" | unfurl -u format %s://%d%p | anew -q gf/endpoints.txt
-		gf lfi "$url_file" | anew -q gf/lfi.txt
-	fi
-	echo "[+] Results are saved in ${DOMAIN}/gf folder"
-}
-
-# Parse command-line arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
-	case "$1" in
-	-u | --url-file)
-		url_file="$2"
-		shift 2
+	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
 		;;
-	-h | --help)
-		help_menu
-		exit 0
+	-o | --output)
+		output_dir="$2"
+		shift
 		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown parameter: $1"
-		help_menu
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
+	shift
 done
 
-# Validate input and start main function
-validate_input
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+# Vulnerable pattern search function
+url_gf() {
+	mkdir -p $output_dir
+	if [[ -s $input_file ]]; then
+		gf xss "$input_file" | anew -q ${output_dir}/xss.txt
+		gf ssti "$input_file" | anew -q ${output_dir}/ssti.txt
+		gf ssrf "$input_file" | anew -q ${output_dir}/ssrf.txt
+		gf sqli "$input_file" | anew -q ${output_dir}/sqli.txt
+		gf redirect "$input_file" | anew -q ${output_dir}/redirect.txt
+		[[ -s "${output_dir}/ssrf.txt" ]] && cat ${output_dir}/ssrf.txt | anew -q ${output_dir}/redirect.txt
+		gf rce "$input_file" | anew -q ${output_dir}/rce.txt
+		gf potential "$input_file" | cut -d ':' -f3-5 | anew -q ${output_dir}/potential.txt
+		[[ -s ".tmp/url_extract_tmp.txt" ]] && cat .tmp/url_extract_tmp.txt | grep -aEiv "\.(eot|jpg|jpeg|gif|css|tif|tiff|png|ttf|otf|woff|woff2|ico|pdf|svg|txt|js)$" | unfurl -u format %s://%d%p | anew -q ${output_dir}/endpoints.txt
+		gf lfi "$input_file" | anew -q ${output_dir}/lfi.txt
+	fi
+}
+
 url_gf
diff --git a/bin/rftw_web_wordlists b/bin/rftw_web_wordlists
--- a/bin/rftw_web_wordlists
+++ b/bin/rftw_web_wordlists
@@ -12,60 +12,59 @@ else
 fi
 
 # Help menu
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo "Wordlist Generation"
-	echo ""
-	echo "Options:"
-	echo "  -d, --domain DOMAIN     Set domain (required)"
-	echo "  -h, --help              Display this help message and exit"
-	exit 0
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation
-if [[ $# -eq 0 ]]; then
-	help_menu
-fi
-
-DOMAIN=""
-while [[ $1 != "" ]]; do
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
 	case $1 in
-	-d | --domain)
+	-f | --file)
+		input_file="$2"
 		shift
-		DOMAIN=$1
 		;;
-	-h | --help)
-		help_menu
-		exit
+	-o | --output)
+		output_dir="$2"
+		shift
 		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown option: $1"
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
 	shift
 done
 
-if [[ -z ${DOMAIN} ]]; then
-	echo "Error: Domain is required!"
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
 	exit 1
 fi
 
 wordlist_gen() {
-	local DOMAIN=$1
-	start_func ${FUNCNAME[0]} "Wordlist generation"
+	local DOMAIN=$(cat ${input_file} | head -n1 | unfurl -u apexes)
 	if [[ -s ".tmp/url_extract_tmp.txt" ]]; then
-		cat .tmp/url_extract_tmp.txt | unfurl -u keys | sed 's/[][]//g' | sed 's/[#]//g' | sed 's/[}{]//g' | anew -q webs/dict_params.txt
-		cat .tmp/url_extract_tmp.txt | unfurl -u values | sed 's/[][]//g' | sed 's/[#]//g' | sed 's/[}{]//g' | anew -q webs/dict_values.txt
-		cat .tmp/url_extract_tmp.txt | tr "[:punct:]" "\n" | anew -q webs/dict_words.txt
+		cat .tmp/url_extract_tmp.txt | unfurl -u keys | sed 's/[][]//g' | sed 's/[#]//g' | sed 's/[}{]//g' | anew -q ${output_dir}/dict_params.txt
+		cat .tmp/url_extract_tmp.txt | unfurl -u values | sed 's/[][]//g' | sed 's/[#]//g' | sed 's/[}{]//g' | anew -q ${output_dir}/dict_values.txt
+		cat .tmp/url_extract_tmp.txt | tr "[:punct:]" "\n" | anew -q ${output_dir}/dict_words.txt
 	fi
-	[[ -s ".tmp/js_endpoints.txt" ]] && cat .tmp/js_endpoints.txt | unfurl -u format %s://%d%p | anew -q webs/all_paths.txt
-	[[ -s ".tmp/url_extract_tmp.txt" ]] && cat .tmp/url_extract_tmp.txt | unfurl -u format %s://%d%p | anew -q webs/all_paths.txt
-	end_func "Results are saved in ${DOMAIN}/webs/dict_[words|paths].txt" ${FUNCNAME[0]}
-	if [[ $PROXY == true ]] && [[ -n $proxy_url ]] && [[ $(cat webs/all_paths.txt | wc -l) -le $DEEP_LIMIT2 ]]; then
-		notification "Sending urls to proxy" info
-		ffuf -mc all -w webs/all_paths.txt -u FUZZ -replay-proxy $proxy_url
-	fi
+	[[ -s ".tmp/js_endpoints.txt" ]] && cat .tmp/js_endpoints.txt | unfurl -u format %s://%d%p | anew -q ${output_dir}/all_paths.txt
+	[[ -s ".tmp/url_extract_tmp.txt" ]] && cat .tmp/url_extract_tmp.txt | unfurl -u format %s://%d%p | anew -q ${output_dir}/all_paths.txt
+
 }
 
 wordlist_gen ${DOMAIN}
