Format code

diff --git a/bin/rftw_ip_favicon b/bin/rftw_ip_favicon
--- a/bin/rftw_ip_favicon
+++ b/bin/rftw_ip_favicon
@@ -46,39 +46,40 @@ while [[ $# -gt 0 ]]; do
 		;;
 	*)
 		# Set the domain if it's not specified with -d
-		[ -z "$DOMAIN" ] && DOMAIN="$1" || {
-			echo "Unknown parameter passed: $1"
-			exit 1
-		}
+		if [[ -z ${DOMAIN} ]]; then
+			DOMAIN="$1"
+		fi
 		;;
 	esac
 	shift
 done
 
 # Input validation
-if [ -z "$DOMAIN" ]; then
+if [[ -z ${DOMAIN} ]]; then
 	help_menu
 	exit 1
 fi
 
 # Validate domain format
-if [[ ! $DOMAIN =~ ^[a-zA-Z0-9.-]+$ ]]; then
+if [[ ! ${DOMAIN} =~ ^[a-zA-Z0-9.-]+$ ]]; then
 	echo "Invalid domain format."
 	exit 1
 fi
 
-pushd "$tools/fav-up" &>/dev/null || {
-	echo "Failed to cd to $tools/fav-up in favicon"
+pushd "${tools}/fav-up" &>/dev/null || {
+	echo "Failed to cd to ${tools}/fav-up in favicon"
 	exit 1
 }
-python3 favUp.py -w "$DOMAIN" -sc -o favicontest.json
-if [ -s "favicontest.json" ]; then
-	jq -r 'try .found_ips' favicontest.json | grep -v "not-found" >favicontest.txt
+python3 favUp.py -w "${DOMAIN}" -sc -o favicontest.json
+if [[ -s "favicontest.json" ]]; then
+	jq -r 'try .found_ips' favicontest.json >temp.txt
+	grep -v "not-found" temp.txt >favicontest.txt
+	rm temp.txt
 	sed -i "s/|/\n/g" favicontest.txt
 fi
 popd &>/dev/null || {
 	echo "Failed to cd back from favicon"
 	exit 1
 }
-[ -s "$tools/fav-up/favicontest.txt" ] && cp $tools/fav-up/favicontest.txt .
+[[ -s "${tools}/fav-up/favicontest.txt" ]] && cp "${tools}"/fav-up/favicontest.txt .
 cat favicontest.txt
diff --git a/bin/rftw_osint_emails b/bin/rftw_osint_emails
--- a/bin/rftw_osint_emails
+++ b/bin/rftw_osint_emails
@@ -14,30 +14,23 @@ function help_menu() {
 # Main function
 function gather_emails() {
     # Validate tools
-    for tool in emailfinder anew; do
-        if ! command -v $tool &> /dev/null; then
-            echo -e "${bred}Error: ${tool} is not installed.${reset}" >&2
-            exit 1
-        fi
-    done
-
     echo "Searching emails/users/passwords leaks"
-    emailfinder -d "$domain" 2>>"$LOGFILE" | anew -q .tmp/emailfinder.txt || { echo "emailfinder command failed"; exit 1; }
-    if [ -z "$output_file" ]; then
+    emailfinder -d "${DOMAIN}" 2>>"${LOGFILE}" | anew -q .tmp/emailfinder.txt || { echo "emailfinder command failed"; exit 1; }
+    if [[ -z "${output_file}" ]]; then
         cat ".tmp/emailfinder.txt" 2>/dev/null | grep "@" | grep -iv "|_"
     else
-        cat ".tmp/emailfinder.txt" 2>/dev/null | grep "@" | grep -iv "|_" > "$output_file"
+        cat ".tmp/emailfinder.txt" 2>/dev/null | grep "@" | grep -iv "|_" > "${output_file}"
     fi
 }
 
 # Default values
-domain=""
+DOMAIN=""
 output_file=""
 
 # Parse command-line arguments
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-        -d|--domain) domain="$2"; shift ;;
+        -d|--domain) DOMAIN="$2"; shift ;;
         -o|--output) output_file="$2"; shift ;;
         -h|--help) help_menu ;;
         *) echo -e "${bred}Unknown parameter passed: $1${reset}" >&2; help_menu ;;
@@ -46,10 +39,10 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 # Validate the domain using the utility script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 # Validate inputs
-if [ -z "$domain" ]; then
+if [[ -z "${DOMAIN}" ]]; then
     echo -e "${bred}Error: Missing required parameters.${reset}" >&2
     help_menu
     exit 1
diff --git a/bin/rftw_osint_ghrepos b/bin/rftw_osint_ghrepos
--- a/bin/rftw_osint_ghrepos
+++ b/bin/rftw_osint_ghrepos
@@ -2,74 +2,80 @@
 
 # Help menu
 function help_menu() {
-    echo -e "Usage: ./rftw_osint_ghrepos.sh [OPTIONS]"
-    echo -e "Options:"
-    echo -e "  -d, --domain DOMAIN       Specify the domain"
-    echo -e "  -g, --github-tokens FILE  Specify the path to the GitHub tokens file"
-    echo -e "  -o, --output FILE         (Optional) Specify the output file path (prints to stdout if not set)"
-    echo -e "  -h, --help                Display this help menu"
-    exit 1
+	echo -e "Usage: ./rftw_osint_ghrepos.sh [OPTIONS]"
+	echo -e "Options:"
+	echo -e "  -d, --domain DOMAIN       Specify the domain"
+	echo -e "  -g, --github-tokens FILE  Specify the path to the GitHub tokens file"
+	echo -e "  -o, --output FILE         (Optional) Specify the output file path (prints to stdout if not set)"
+	echo -e "  -h, --help                Display this help menu"
+	exit 1
 }
 
 # Main function
 function github_repos() {
-    # Validate tools
-    mkdir -p .tmp
-    for tool in unfurl enumerepo jq interlace gitleaks trufflehog; do
-        if ! command -v $tool &> /dev/null; then
-            echo -e "${bred}Error: ${tool} is not installed.${reset}" >&2
-            exit 1
-        fi
-    done
+	# Validate tools
+	mkdir -p .tmp
 
-    if [ -s "${github_tokens}" ]; then
-        GH_TOKEN=$(cat ${github_tokens} | head -1)
-        echo $domain | unfurl format %r > .tmp/company_name.txt
-        enumerepo -token-string "${GH_TOKEN}" -usernames .tmp/company_name.txt -o .tmp/company_repos.txt
-        [ -s ".tmp/company_repos.txt" ] && jq -r '.[].repos[]|.url' < .tmp/company_repos.txt > .tmp/company_repos_url.txt
-        mkdir -p .tmp/github_repos
-        mkdir -p .tmp/github
-        [ -s ".tmp/company_repos_url.txt" ] && interlace -tL .tmp/company_repos_url.txt -threads ${INTERLACE_THREADS} -c "git clone _target_  .tmp/github_repos/_cleantarget_"
-        [ -d ".tmp/github/" ] && ls .tmp/github_repos > .tmp/github_repos_folders.txt
-        [ -s ".tmp/github_repos_folders.txt" ] && interlace -tL .tmp/github_repos_folders.txt -threads ${INTERLACE_THREADS} -c "gitleaks detect --source .tmp/github_repos/_target_ --no-banner --no-color -r .tmp/github/gh_secret_cleantarget_.json"
-        [ -s ".tmp/company_repos_url.txt" ] && interlace -tL .tmp/company_repos_url.txt -threads ${INTERLACE_THREADS} -c "trufflehog git _target_ -j 2>&1 | jq -c > _output_/_cleantarget_" -o .tmp/github/
-        if [ -d ".tmp/github/" ]; then
-            if [ -z "$output_file" ]; then
-                cat .tmp/github/* 2>/dev/null | jq -c | jq -r
-            else
-                cat .tmp/github/* 2>/dev/null | jq -c | jq -r > "$output_file"
-            fi
-        fi
-    else
-        printf "\n${bred} Required file ${GITHUB_TOKENS} not exists or empty${reset}\n"
-    fi
+	if [[ -s ${github_tokens} ]]; then
+		GH_TOKEN=$(cat "${github_tokens}" | head -1)
+		echo "${DOMAIN}" | unfurl format %r >.tmp/company_name.txt
+		enumerepo -token-string "${GH_TOKEN}" -usernames .tmp/company_name.txt -o .tmp/company_repos.txt
+		[[ -s ".tmp/company_repos.txt" ]] && jq -r '.[].repos[]|.url' <.tmp/company_repos.txt >.tmp/company_repos_url.txt
+		mkdir -p .tmp/github_repos
+		mkdir -p .tmp/github
+		[[ -s ".tmp/company_repos_url.txt" ]] && interlace -tL .tmp/company_repos_url.txt -threads "${INTERLACE_THREADS}" -c "git clone _target_  .tmp/github_repos/_cleantarget_"
+		[[ -d ".tmp/github/" ]] && ls .tmp/github_repos >.tmp/github_repos_folders.txt
+		[[ -s ".tmp/github_repos_folders.txt" ]] && interlace -tL .tmp/github_repos_folders.txt -threads "${INTERLACE_THREADS}" -c "gitleaks detect --source .tmp/github_repos/_target_ --no-banner --no-color -r .tmp/github/gh_secret_cleantarget_.json"
+		[[ -s ".tmp/company_repos_url.txt" ]] && interlace -tL .tmp/company_repos_url.txt -threads "${INTERLACE_THREADS}" -c "trufflehog git _target_ -j 2>&1 | jq -c > _output_/_cleantarget_" -o .tmp/github/
+		if [[ -d ".tmp/github/" ]]; then
+			if [[ -z $output_file ]]; then
+				cat .tmp/github/* 2>/dev/null | jq -c | jq -r
+			else
+				cat .tmp/github/* 2>/dev/null | jq -c | jq -r >"${output_file}"
+			fi
+		fi
+	else
+		printf "\n${bred} Required file ${GITHUB_TOKENS} not exists or empty${reset}\n"
+	fi
 }
 
 # Default values
-domain=""
+DOMAIN=""
 github_tokens=""
 output_file=""
 
 # Parse command-line arguments
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift ;;
-        -g|--github-tokens) github_tokens="$2"; shift ;;
-        -o|--output) output_file="$2"; shift ;;
-        -h|--help) help_menu ;;
-        *) echo -e "${bred}Unknown parameter passed: $1${reset}" >&2; help_menu ;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-g | --github-tokens)
+		github_tokens="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) help_menu ;;
+	*)
+		echo -e "${bred}Unknown parameter passed: $1${reset}" >&2
+		help_menu
+		;;
+	esac
+	shift
 done
 
 # Validate the domain using the utility script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 # Validate inputs
-if [ -z "$domain" ] || [ -z "$github_tokens" ]; then
-    echo -e "${bred}Error: Missing required parameters.${reset}" >&2
-    help_menu
-    exit 1
+if [[ -z ${DOMAIN} ]] || [[ -z ${github_tokens} ]]; then
+	echo -e "${bred}Error: Missing required parameters.${reset}" >&2
+	help_menu
+	exit 1
 fi
 
 # Execute the main function
diff --git a/bin/rftw_osint_googledorks b/bin/rftw_osint_googledorks
--- a/bin/rftw_osint_googledorks
+++ b/bin/rftw_osint_googledorks
@@ -4,49 +4,58 @@
 
 # Help menu
 function help_menu() {
-    echo -e "Usage: ./rftw_osint_googledorks.sh [OPTIONS]"
-    echo -e "Options:"
-    echo -e "  -d, --domain DOMAIN       Specify the domain"
-    echo -e "  -o, --output FILE         (Optional) Specify the output directory file"
-    echo -e "  -h, --help                Display this help menu"
-    exit 1
+	echo -e "Usage: ./rftw_osint_googledorks.sh [OPTIONS]"
+	echo -e "Options:"
+	echo -e "  -d, --domain DOMAIN       Specify the domain"
+	echo -e "  -o, --output FILE         (Optional) Specify the output directory file"
+	echo -e "  -h, --help                Display this help menu"
+	exit 1
 }
 
 # Main function
 function google_dorks() {
-    output_file_arg=""
-    if [ -n "$output" ]; then
-        output_file_arg="-o ${output}"
-    fi
+	output_file_arg=""
+	if [[ -n ${output} ]]; then
+		output_file_arg="-o ${output}"
+	fi
 
-    python3 "${tools}/dorks_hunter/dorks_hunter.py" -d "$domain" $output_file_arg || { 
-        echo -e "${bred}Error: dorks_hunter.py failed.${reset}" >&2; 
-        exit 1; 
-    }
+	python3 "${tools}/dorks_hunter/dorks_hunter.py" -d "${DOMAIN}" "${output_file_arg}" || {
+		echo -e "${bred}Error: dorks_hunter.py failed.${reset}" >&2
+		exit 1
+	}
 }
 
 # Parse command-line arguments
-domain=""
+DOMAIN=""
 output=""
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift ;;
-        -o|--output) output="$2"; shift ;;
-        -h|--help) help_menu ;;
-        *) echo -e "${bred}Unknown parameter passed: $1${reset}" >&2; help_menu ;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-o | --output)
+		output="$2"
+		shift
+		;;
+	-h | --help) help_menu ;;
+	*)
+		echo -e "${bred}Unknown parameter passed: $1${reset}" >&2
+		help_menu
+		;;
+	esac
+	shift
 done
 
 # Validate inputs
-if [ -z "$domain" ]; then
-    echo -e "${bred}Error: Missing required parameters.${reset}" >&2
-    help_menu
-    exit 1
+if [[ -z ${DOMAIN} ]]; then
+	echo -e "${bred}Error: Missing required parameters.${reset}" >&2
+	help_menu
+	exit 1
 fi
 
 # Validate the domain using the utility script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 # Execute the main function
 google_dorks
diff --git a/bin/rftw_osint_metadata b/bin/rftw_osint_metadata
--- a/bin/rftw_osint_metadata
+++ b/bin/rftw_osint_metadata
@@ -13,21 +13,15 @@ function help_menu() {
 # Main function
 function gather_metadata() {
     # Validate tools
-    for tool in metafinder; do
-        if ! command -v $tool &> /dev/null; then
-            echo -e "${bred}Error: ${tool} is not installed.${reset}" >&2
-            exit 1
-        fi
-    done
 
     echo -e "${yellow}Scanning metadata in public files${reset}"
-    metafinder -d "$domain" -l $METAFINDER_LIMIT -o osint -go -bi -ba &>> "$LOGFILE" || { echo "metafinder command failed"; exit 1; }
-    mv "osint/${domain}/"*".txt" "osint/" 2>>"$LOGFILE"
-    rm -rf "osint/${domain}" 2>>"$LOGFILE"
-    if [ -z "$output_file" ]; then
+    metafinder -d "${DOMAIN}" -l "${METAFINDER_LIMIT}" -o osint -go -bi -ba &>> "${LOGFILE}" || { echo "metafinder command failed"; exit 1; }
+    mv "osint/${domain}/"*".txt" "osint/" 2>>"${LOGFILE}"
+    rm -rf "osint/${domain}" 2>>"${LOGFILE}"
+    if [[ -z "${output_file}" ]]; then
         cat "osint/${domain}/*" 2>/dev/null
     else
-        cat "osint/${domain}/*" 2>/dev/null > "$output_file"
+        cat "osint/${domain}/*" 2>/dev/null > "${output_file}"
     fi
 }
 
@@ -47,10 +41,10 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 # Validate the domain using the utility script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 # Validate inputs
-if [ -z "$domain" ]; then
+if [[ -z "${DOMAIN}" ]]; then
     echo -e "${bred}Error: Missing required parameters.${reset}" >&2
     help_menu
     exit 1
diff --git a/bin/rftw_osint_postleaks b/bin/rftw_osint_postleaks
--- a/bin/rftw_osint_postleaks
+++ b/bin/rftw_osint_postleaks
@@ -12,31 +12,24 @@ function help_menu() {
 
 # Main function
 function postleaks() {
-    # Validate tools
-    for tool in postleaksNg; do
-        if ! command -v $tool &> /dev/null; then
-            echo -e "${bred}Error: ${tool} is not installed.${reset}" >&2
-            exit 1
-        fi
-    done
 
     echo -e "${yellow}Scanning for leaks in postman public directory${reset}"
-    postleaksNg -k "$domain" > .tmp/postleaks.txt  || { echo "postleaksNg command failed"; exit 1; }
-    if [ -z "$output_file" ]; then
+    postleaksNg -k "${DOMAIN}" > .tmp/postleaks.txt  || { echo "postleaksNg command failed"; exit 1; }
+    if [[ -z "${output_file}" ]]; then
         cat ".tmp/postleaks.txt" 2>/dev/null
     else
-        cat ".tmp/postleaks.txt" 2>/dev/null > "$output_file"
+        cat ".tmp/postleaks.txt" 2>/dev/null > "${output_file}"
     fi
 }
 
 # Default values
-domain=""
+DOMAIN=""
 output_file=""
 
 # Parse command-line arguments
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-        -d|--domain) domain="$2"; shift ;;
+        -d|--domain) DOMAIN="$2"; shift ;;
         -o|--output) output_file="$2"; shift ;;
         -h|--help) help_menu ;;
         *) echo -e "${bred}Unknown parameter passed: $1${reset}" >&2; help_menu ;;
@@ -45,10 +38,10 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 # Validate the domain using the utility script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 # Validate inputs
-if [ -z "$domain" ]; then
+if [[ -z "${DOMAIN}" ]]; then
     echo -e "${bred}Error: Missing required parameters.${reset}" >&2
     help_menu
     exit 1
diff --git a/bin/rftw_sub_active b/bin/rftw_sub_active
--- a/bin/rftw_sub_active
+++ b/bin/rftw_sub_active
@@ -1,66 +1,77 @@
 #!/bin/bash
 
-
 # Help menu
 display_help() {
-    echo "$(basename "$0") [Options]"
-    echo
-    echo "  -d, --domain            Domain for which subdomain enumeration is required"
-    echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
-    echo "  -o, --output            Output file location (Optional)"
-    echo "  -h, --help              Display this help and exit"
-    echo
-    echo "Example: $0 -d example.com -l /path/to/log"
-    exit 1
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Domain for which subdomain enumeration is required"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location (Optional)"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
 # Variables for input and output
 output_file=""
 
 # Parse input arguments
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift ;;
-        -f|--file) domain_file="$2"; shift ;;
-        -o|--output) output_file="$2"; shift ;;  # New output flag
-        -h|--help) display_help ;;
-        *) echo "Unknown parameter passed: $1"; exit 1 ;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-f | --file)
+		domain_file="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;; # New output flag
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		exit 1
+		;;
+	esac
+	shift
 done
 
 # Input validation
-if [ -z "$domain_file" ] || [ -z "$domain" ]; then
-    display_help
-    exit 1
+if [[ -z ${domain_file} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
+	exit 1
 fi
 
 # Validate file
-if [[ ! -f "$domain_file" ]] || [[ ! -r "$domain_file" ]]; then
-    echo "Error: Specified file does not exist or is not readable."
-    exit 1
+if [[ ! -f ${domain_file} ]] || [[ ! -r ${domain_file} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
 fi
 
 # Validate domain
-rftw_util_validatedomain "$domain" || exit 1  # Domain validation
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
 
 sub_active() {
-    mkdir -p .tmp 2>/dev/null
-	if [ ! "$AXIOM" = true ]; then
+	mkdir -p .tmp 2>/dev/null
+	if [[ ${AXIOM} != true ]]; then
 		resolvers_update_quick_local
-		[ -s $domain_file ] && puredns resolve $domain_file -w .tmp/subdomains_tmp.txt -r $resolvers --resolvers-trusted $resolvers_trusted -l $PUREDNS_PUBLIC_LIMIT --rate-limit-trusted $PUREDNS_TRUSTED_LIMIT --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT  --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT 2>>"$LOGFILE" >/dev/null
+		[[ -s ${domain_file} ]] && puredns resolve "${domain_file}" -w .tmp/subdomains_tmp.txt -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}" 2>>"${LOGFILE}" >/dev/null
 	else
 		resolvers_update_quick_axiom
-		[ -s $domain_file ] && axiom-scan $domain_file -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/subdomains_tmp.txt $AXIOM_EXTRA_ARGS 2>>"$LOGFILE" >/dev/null
+		[[ -s ${domain_file} ]] && axiom-scan ${domain_file} -m puredns-resolve -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}" -o .tmp/subdomains_tmp.txt "${AXIOM_EXTRA_ARGS}" 2>>"${LOGFILE}" >/dev/null
 	fi
-	echo $domain | dnsx -retry 3 -silent -r $resolvers_trusted 2>>"$LOGFILE" | anew -q .tmp/subdomains_tmp.txt
-	if [ "$DEEP" = true ]; then
+	echo "${DOMAIN}" | dnsx -retry 3 -silent -r $resolvers_trusted 2>>"${LOGFILE}" | anew -q .tmp/subdomains_tmp.txt
+	if [[ $DEEP == true ]]; then
 		cat .tmp/subdomains_tmp.txt | tlsx -san -cn -silent -ro -c $TLSX_THREADS -p $TLS_PORTS | anew -q .tmp/subdomains_tmp.txt
 	else
 		cat .tmp/subdomains_tmp.txt | tlsx -san -cn -silent -ro -c $TLSX_THREADS | anew -q .tmp/subdomains_tmp.txt
 	fi
-	[[ "$INSCOPE" = true ]] && rftw_util_inscope .tmp/subdomains_tmp.txt 2>>"$LOGFILE" >/dev/null
-    [ -s "$output_file" ] && cat .tmp/subdomains_tmp.txt >> "$output_file"
+	[[ ${INSCOPE} == true ]] && rftw_util_inscope .tmp/subdomains_tmp.txt 2>>"${LOGFILE}" >/dev/null
+	[[ -s ${output_file} ]] && cat .tmp/subdomains_tmp.txt >>"${output_file}"
 }
 
 # Run the function
diff --git a/bin/rftw_sub_crt b/bin/rftw_sub_crt
--- a/bin/rftw_sub_crt
+++ b/bin/rftw_sub_crt
@@ -2,60 +2,74 @@
 
 # Help Menu
 function display_help() {
-    echo "$(basename "$0") [OPTIONS]"
-    echo "Options:"
-    echo "  -d, --domain          Set the target domain. (Required)"
-    echo "  -l, --limit           Set the crt limit (default 100)."
-    echo "  -o, --output          Specify the output file. (Optional)"
-    echo "  -h, --help            Display this help menu."
+	echo "$(basename "$0") [OPTIONS]"
+	echo "Options:"
+	echo "  -d, --domain          Set the target domain. (Required)"
+	echo "  -l, --limit           Set the crt limit (default 100)."
+	echo "  -o, --output          Specify the output file. (Optional)"
+	echo "  -h, --help            Display this help menu."
 }
 
 # Variables for input and output
 output_file=""
-user_set_limit=false  # Variable to check if user set the limit
+user_set_limit=false # Variable to check if user set the limit
 
 # Input validation and argument parsing
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift;;
-        -l|--limit) 
-            CTR_LIMIT_LOCAL="$2"; 
-            user_set_limit=true;  # User set the limit
-            shift;;
-        -o|--output) 
-            shift;
-            output_file="$1";
-            touch "$output_file" 2>/dev/null || { echo "Error: Cannot write to the specified output file."; exit 1; }
-            ;;
-        -h|--help) display_help; exit 0;;
-        *) echo "Unknown parameter passed: $1"; display_help; exit 1;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-l | --limit)
+		CTR_LIMIT_LOCAL="$2"
+		user_set_limit=true # User set the limit
+		shift
+		;;
+	-o | --output)
+		shift
+		output_file="$1"
+		touch "${output_file}" 2>/dev/null || {
+			echo "Error: Cannot write to the specified output file."
+			exit 1
+		}
+		;;
+	-h | --help)
+		display_help
+		exit 0
+		;;
+	*)
+		echo "Unknown parameter passed: $1"
+		display_help
+		exit 1
+		;;
+	esac
+	shift
 done
 
-if [[ "$user_set_limit" == false ]]; then
-    CTR_LIMIT_LOCAL=$CTR_LIMIT
+if [[ ${user_set_limit} == false ]]; then
+	CTR_LIMIT_LOCAL=${CTR_LIMIT}
 fi
 
 # Validate domain
-if [ -z "$domain" ]; then
-    echo "Error: Domain not provided."
-    display_help
-    exit 1
+if [[ -z ${DOMAIN} ]]; then
+	echo "Error: Domain not provided."
+	display_help
+	exit 1
 fi
 
 # Call the domain validation script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 # Main Functionality
-crt -s -json -l ${CTR_LIMIT_LOCAL} $domain 2>>"$LOGFILE" | jq -r '.[].subdomain' 2>>"$LOGFILE" | sed -e "s/^\\*\\.//" | anew -q .tmp/crtsh_subs_tmp.txt 2>>"$LOGFILE" >/dev/null
+crt -s -json -l "${CTR_LIMIT_LOCAL}" "${DOMAIN}" 2>>"${LOGFILE}" | jq -r '.[].subdomain' 2>>"${LOGFILE}" | sed -e 's/^\*\.//' | anew -q .tmp/crtsh_subs_tmp.txt 2>>"${LOGFILE}" >/dev/null
 
 # Check inscope
 rftw_util_inscope .tmp/crtsh_subs_tmp.txt
 
 # Save results to the specified output file if provided
-if [ -n "$output_file" ]; then
-    cat .tmp/crtsh_subs_tmp.txt > "$output_file"
+if [[ -n ${output_file} ]]; then
+	cat .tmp/crtsh_subs_tmp.txt >"${output_file}"
 else
-    cat .tmp/crtsh_subs_tmp.txt
+	cat .tmp/crtsh_subs_tmp.txt
 fi
diff --git a/bin/rftw_sub_dns b/bin/rftw_sub_dns
--- a/bin/rftw_sub_dns
+++ b/bin/rftw_sub_dns
@@ -2,51 +2,63 @@
 
 # Help menu
 display_help() {
-    echo "$(basename "$0") [OPTIONS]"
-    echo "Options:"
-    echo "  -f, --input-file      Specify the input file with a list of domains. (Required)"
-    echo "  -o, --output-file     Specify the output file for saving results. (Optional)"
-    echo "  -h, --help            Display this help and exit."
-    echo
-    echo "Ensure all required environment variables are set in reconftw.cfg"
+	echo "$(basename "$0") [OPTIONS]"
+	echo "Options:"
+	echo "  -f, --input-file      Specify the input file with a list of domains. (Required)"
+	echo "  -o, --output-file     Specify the output file for saving results. (Optional)"
+	echo "  -h, --help            Display this help and exit."
+	echo
+	echo "Ensure all required environment variables are set in reconftw.cfg"
 }
 
 # Default values for input and output files
 INPUTFILE=""
 
 # Parse input arguments
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -f|--input-file) INPUTFILE="$2"; shift;;
-        -o|--output-file) OUTPUTFILE="$2"; shift;;
-        -h|--help) display_help; exit 0;;
-        *) echo "Unknown parameter passed: $1"; display_help; exit 1;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-f | --input-file)
+		INPUTFILE="$2"
+		shift
+		;;
+	-o | --output-file)
+		OUTPUTFILE="$2"
+		shift
+		;;
+	-h | --help)
+		display_help
+		exit 0
+		;;
+	*)
+		echo "Unknown parameter passed: $1"
+		display_help
+		exit 1
+		;;
+	esac
+	shift
 done
 
 # Input validation
-if [ -z "$INPUTFILE" ] || [ ! -f "$INPUTFILE" ]; then
-    echo "Error: Input file not provided or does not exist."
-    display_help
-    exit 1
+if [[ -z "${INPUTFILE}" ]] || [[ ! -f "${INPUTFILE}" ]]; then
+	echo "Error: Input file not provided or does not exist."
+	display_help
+	exit 1
 fi
 # Main logic (Original function content)
 
-if [ ! "$AXIOM" = true ]; then
-	cat $INPUTFILE | dnsx -r $resolvers_trusted -a -aaaa -cname -ns -ptr -mx -soa -silent -retry 3 -json -o subdomains/subdomains_dnsregs.json 2>>"$LOGFILE" >/dev/null
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[], try .aaaa[], try .cname[], try .ns[], try .ptr[], try .mx[], try .soa[]' 2>/dev/null | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[]' | sort -u | hakip2host | cut -d' ' -f 3 | unfurl -u domains | sed -e 's/*\.//' -e 's/\.$//' -e '/\./!d' | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try "\(.host) - \(.a[])"' 2>/dev/null | sort -u -k2 | anew -q subdomains/subdomains_ips.txt
+if [[ ${AXIOM} != true ]]; then
+	cat "${INPUTFILE}" | dnsx -r "${resolvers_trusted}" -a -aaaa -cname -ns -ptr -mx -soa -silent -retry 3 -json -o subdomains/subdomains_dnsregs.json 2>>"${LOGFILE}" >/dev/null
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[], try .aaaa[], try .cname[], try .ns[], try .ptr[], try .mx[], try .soa[]' 2>/dev/null | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[]' | sort -u | hakip2host | cut -d' ' -f 3 | unfurl -u domains | sed -e 's/*\.//' -e 's/\.$//' -e '/\./!d' | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try "\(.host) - \(.a[])"' 2>/dev/null | sort -u -k2 | anew -q subdomains/subdomains_ips.txt
 	resolvers_update_quick_local
-	[ -s ".tmp/subdomains_dns.txt" ] && puredns resolve .tmp/subdomains_dns.txt -w .tmp/subdomains_dns_resolved.txt -r $resolvers --resolvers-trusted $resolvers_trusted -l $PUREDNS_PUBLIC_LIMIT --rate-limit-trusted $PUREDNS_TRUSTED_LIMIT --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT  --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT 2>>"$LOGFILE" >/dev/null
+	[[ -s ".tmp/subdomains_dns.txt" ]] && puredns resolve .tmp/subdomains_dns.txt -w .tmp/subdomains_dns_resolved.txt -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}" 2>>"${LOGFILE}" >/dev/null
 else
-	axiom-scan $INPUTFILE -m dnsx -retry 3 -a -aaaa -cname -ns -ptr -mx -soa -json -o subdomains/subdomains_dnsregs.json $AXIOM_EXTRA_ARGS 2>>"$LOGFILE" >/dev/null
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[]' | sort -u | anew -q .tmp/subdomains_dns_a_records.txt
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[]' | sort -u | hakip2host | cut -d' ' -f 3 | unfurl -u domains | sed -e 's/*\.//' -e 's/\.$//' -e '/\./!d' | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[], try .aaaa[], try .cname[], try .ns[], try .ptr[], try .mx[], try .soa[]' 2>/dev/null | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
-	[ -s "subdomains/subdomains_dnsregs.json" ] && cat subdomains/subdomains_dnsregs.json | jq -r 'try "\(.host) - \(.a[])"' 2>/dev/null | sort -u -k2 | anew -q subdomains/subdomains_ips.txt
+	axiom-scan "${INPUTFILE}" -m dnsx -retry 3 -a -aaaa -cname -ns -ptr -mx -soa -json -o subdomains/subdomains_dnsregs.json "${AXIOM_EXTRA_ARGS}" 2>>"${LOGFILE}" >/dev/null
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[]' | sort -u | anew -q .tmp/subdomains_dns_a_records.txt
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[]' | sort -u | hakip2host | cut -d' ' -f 3 | unfurl -u domains | sed -e 's/*\.//' -e 's/\.$//' -e '/\./!d' | grep ".${domain}$" | anew -q .tmp/subdomains_dns.txt
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try .a[], try .aaaa[], try .cname[], try .ns[], try .ptr[], try .mx[], try .soa[]' 2>/dev/null | grep ".$domain$" | anew -q .tmp/subdomains_dns.txt
+	[[ -s "subdomains/subdomains_dnsregs.json" ]] && cat subdomains/subdomains_dnsregs.json | jq -r 'try "\(.host) - \(.a[])"' 2>/dev/null | sort -u -k2 | anew -q subdomains/subdomains_ips.txt
 	resolvers_update_quick_axiom
-	[ -s ".tmp/subdomains_dns.txt" ] && axiom-scan .tmp/subdomains_dns.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/subdomains_dns_resolved.txt $AXIOM_EXTRA_ARGS 2>>"$LOGFILE" >/dev/null
+	[[ -s ".tmp/subdomains_dns.txt" ]] && axiom-scan .tmp/subdomains_dns.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}" -o .tmp/subdomains_dns_resolved.txt "${AXIOM_EXTRA_ARGS}" 2>>"${LOGFILE}" >/dev/null
 fi
-
diff --git a/bin/rftw_sub_full b/bin/rftw_sub_full
--- a/bin/rftw_sub_full
+++ b/bin/rftw_sub_full
@@ -2,130 +2,146 @@
 
 # Function to display help menu
 help_menu() {
-    echo "$(basename "$0") [OPTIONS]"
-    echo "Options:"
-    echo "  -d, --domain          Set the target domain."
-    echo "  -h, --help            Display this help and exit."
-    echo "  -f, --input-file      Specify the input file with a list of domains."
-    echo "  -o, --output-file     Specify the output file for saving results."
-    echo "Ensure all required environment variables are set in reconftw.cfg"
-    exit 0
+	echo "$(basename "$0") [OPTIONS]"
+	echo "Options:"
+	echo "  -d, --domain          Set the target domain."
+	echo "  -h, --help            Display this help and exit."
+	echo "  -f, --input-file      Specify the input file with a list of domains."
+	echo "  -o, --output-file     Specify the output file for saving results."
+	echo "Ensure all required environment variables are set in reconftw.cfg"
+	exit 0
 }
 
 # Validate domain using rftw_util_validatedomain
 validate_domain() {
-    rftw_util_validatedomain "$1" || { echo "Invalid domain: $1"; exit 1; }
+	rftw_util_validatedomain "$1" || {
+		echo "Invalid domain: $1"
+		exit 1
+	}
 }
 
 # Parse input arguments
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift;;
-        -f|--input-file) INPUTFILE="$2"; shift;;
-        -o|--output-file) OUTPUTFILE="$2"; shift;;
-        -h|--help) help_menu;;
-        *) echo "Unknown parameter passed: $1"; help_menu; exit 1;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		domain="$2"
+		shift
+		;;
+	-f | --input-file)
+		INPUTFILE="$2"
+		shift
+		;;
+	-o | --output-file)
+		OUTPUTFILE="$2"
+		shift
+		;;
+	-h | --help) help_menu ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		help_menu
+		exit 1
+		;;
+	esac
+	shift
 done
 
 # If an input file is provided, validate it
-if [ -n "$INPUTFILE" ] && [ ! -f "$INPUTFILE" ]; then
-    echo "Error: Input file $INPUTFILE not found!"
-    exit 1
+if [[ -n ${INPUTFILE} ]] && [[ ! -f ${INPUTFILE} ]]; then
+	echo "Error: Input file ${INPUTFILE} not found!"
+	exit 1
 fi
 
 # Input validation
-if [ -z "$domain" ]; then
-    echo "No domain provided."
-    help_menu
-    exit 1
+if [[ -z ${DOMAIN} ]]; then
+	echo "No domain provided."
+	help_menu
+	exit 1
 fi
 
-validate_domain "$domain"
+validate_domain "${DOMAIN}"
 
 # Function to start the process
 start_func() {
-    echo "[*] $1"
+	echo "[*] $1"
 }
 
 # Function to end the process
 end_func() {
-    echo "[+] $1"
+	echo "[+] $1"
 }
 
 # Function to notify the user
 notification() {
-    echo "[!] $1"
+	echo "[!] $1"
 }
 
 # Main function to gather subdomain info
 subdomains_full_func() {
-    echo "Starting subdomain enumeration for $domain"
-    
-    NUMOFLINES_subs="0"
-    NUMOFLINES_probed="0"
-    printf "${bgreen}#######################################################################\n\n"
-    ! [[ $domain =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]] && printf "${bblue} Subdomain Enumeration $domain\n\n"
-    [[ $domain =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]] && printf "${bblue} Scanning IP $domain\n\n"
-    [ -s "subdomains/subdomains.txt" ] && cp subdomains/subdomains.txt .tmp/subdomains_old.txt
-    [ -s "webs/webs.txt" ] && cp webs/webs.txt .tmp/probed_old.txt
+	echo "Starting subdomain enumeration for${domain}/"
 
-    if ( [ ! -f "$called_fn_dir/.sub_active" ] || [ ! -f "$called_fn_dir/.sub_brute" ] || [ ! -f "$called_fn_dir/.sub_permut" ] || [ ! -f "$called_fn_dir/.sub_recursive_brute" ] )  || [ "$DIFF" = true ] ; then
-        resolvers_update
-    fi
+	NUMOFLINES_subs="0"
+	NUMOFLINES_probed="0"
+	printf "${bgreen}#######################################################################\n\n"
+	! [[ ${DOMAIN} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]] && printf "${bblue} Subdomain Enumeration${domain}/\n\n"
+	[[ ${DOMAIN} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]] && printf "${bblue} Scanning IP${domain}/\n\n"
+	[[ -s "subdomains/subdomains.txt" ]] && cp subdomains/subdomains.txt .tmp/subdomains_old.txt
+	[[ -s "webs/webs.txt" ]] && cp webs/webs.txt .tmp/probed_old.txt
 
-    [ -s "${inScope_file}" ] && cat ${inScope_file} | anew -q subdomains/subdomains.txt
+	if ([[ ! -f "${called_fn_dir}/.sub_active" ]] || [[ ! -f "${called_fn_dir}/.sub_brute" ]] || [[ ! -f "${called_fn_dir}/.sub_permut" ]] || [[ ! -f "${called_fn_dir}/.sub_recursive_brute" ]]) || [[ ${DIFF} == true ]]; then
+		resolvers_update
+	fi
 
-    if ! [[ $domain =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]] && [ "$SUBDOMAINS_GENERAL" = true ]; then
-        rftw_sub_passive
-        rftw_sub_crt
-        rftw_sub_active
-        rftw_sub_noerror
-        rftw_sub_brute
-        rftw_sub_permut
-        rftw_sub_regex_permut
-        rftw_sub_recursive_passive
-        rftw_sub_recursive_brute
-        rftw_sub_dns
-        rftw_sub_scraping
-        rftw_sub_analytics
-    else 
-        notification "IP/CIDR detected, subdomains search skipped"
-        echo $domain | anew -q subdomains/subdomains.txt
-    fi
+	[[ -s ${inScope_file} ]] && cat ${inScope_file} | anew -q subdomains/subdomains.txt
 
-    webprobe_simple
-    if [ -s "subdomains/subdomains.txt" ]; then
-        [ -s "$outOfScope_file" ] && deleteOutScoped $outOfScope_file subdomains/subdomains.txt
-        NUMOFLINES_subs=$(cat subdomains/subdomains.txt 2>>"$LOGFILE" | anew .tmp/subdomains_old.txt | sed '/^$/d' | wc -l)
-    fi
-    if [ -s "webs/webs.txt" ]; then
-        [ -s "$outOfScope_file" ] && deleteOutScoped $outOfScope_file webs/webs.txt
-        NUMOFLINES_probed=$(cat webs/webs.txt 2>>"$LOGFILE" | anew .tmp/probed_old.txt | sed '/^$/d' | wc -l)
-    fi
-    
-    if [ -n "$OUTPUTFILE" ]; then
-        cat subdomains/subdomains.txt > "$OUTPUTFILE"
-        cat webs/webs.txt >> "$OUTPUTFILE"
-    fi
+	if ! [[ ${DOMAIN} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]] && [[ ${SUBDOMAINS_GENERAL} == true ]]; then
+		rftw_sub_passive
+		rftw_sub_crt
+		rftw_sub_active
+		rftw_sub_noerror
+		rftw_sub_brute
+		rftw_sub_permut
+		rftw_sub_regex_permut
+		rftw_sub_recursive_passive
+		rftw_sub_recursive_brute
+		rftw_sub_dns
+		rftw_sub_scraping
+		rftw_sub_analytics
+	else
+		notification "IP/CIDR detected, subdomains search skipped"
+		echo "${DOMAIN}" | anew -q subdomains/subdomains.txt
+	fi
 
-    printf "${bblue}\n Total subdomains: ${reset}\n\n"
-    notification "- ${NUMOFLINES_subs} alive" good
-    [ -s "subdomains/subdomains.txt" ] && cat subdomains/subdomains.txt | sort
-    notification "- ${NUMOFLINES_probed} new web probed" good
-    [ -s "webs/webs.txt" ] && cat webs/webs.txt | sort
-    notification "Subdomain Enumeration Finished" good
-    printf "${bblue} Results are saved in $domain/subdomains/subdomains.txt and webs/webs.txt${reset}\n"
-    printf "${bgreen}#######################################################################\n\n"
+	webprobe_simple
+	if [[ -s "subdomains/subdomains.txt" ]]; then
+		[[ -s $outOfScope_file ]] && deleteOutScoped $outOfScope_file subdomains/subdomains.txt
+		NUMOFLINES_subs=$(cat subdomains/subdomains.txt 2>>"${LOGFILE}" | anew .tmp/subdomains_old.txt | sed '/^$/d' | wc -l)
+	fi
+	if [[ -s "webs/webs.txt" ]]; then
+		[[ -s $outOfScope_file ]] && deleteOutScoped $outOfScope_file webs/webs.txt
+		NUMOFLINES_probed=$(cat webs/webs.txt 2>>"${LOGFILE}" | anew .tmp/probed_old.txt | sed '/^$/d' | wc -l)
+	fi
+
+	if [[ -n ${OUTPUTFILE} ]]; then
+		cat subdomains/subdomains.txt >"${OUTPUTFILE}"
+		cat webs/webs.txt >>"${OUTPUTFILE}"
+	fi
+
+	printf "${bblue}\n Total subdomains: ${reset}\n\n"
+	notification "- ${NUMOFLINES_subs} alive" good
+	[[ -s "subdomains/subdomains.txt" ]] && cat subdomains/subdomains.txt | sort
+	notification "- ${NUMOFLINES_probed} new web probed" good
+	[[ -s "webs/webs.txt" ]] && cat webs/webs.txt | sort
+	notification "Subdomain Enumeration Finished" good
+	printf "${bblue} Results are saved in${domain}//subdomains/subdomains.txt and webs/webs.txt${reset}\n"
+	printf "${bgreen}#######################################################################\n\n"
 }
 
 # Call the main function
 # Logic to handle multiple domains if INPUTFILE is provided
-if [ -n "$INPUTFILE" ]; then
-    while read -r domain; do
-        subdomains_full_func
-    done < "$INPUTFILE"
+if [[ -n "${INPUTFILE}" ]]; then
+	while read -r domain; do
+		subdomains_full_func
+	done <""${INPUTFILE}""
 else
-    subdomains_full_func
+	subdomains_full_func
 fi
diff --git a/bin/rftw_sub_noerror b/bin/rftw_sub_noerror
--- a/bin/rftw_sub_noerror
+++ b/bin/rftw_sub_noerror
@@ -2,57 +2,69 @@
 
 # Help menu
 display_help() {
-    echo "$(basename "$0") [Options]"
-    echo
-    echo "  -d, --domain       Domain to check"
-    echo "  -i, --inscope      Check inscope."
-    echo "  -o, --output-file  File to save results"
-    echo "  -h, --help         Display this help and exit"
-    echo
-    echo "Example: $0 -d example.com"
-    exit 1
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain       Domain to check"
+	echo "  -i, --inscope      Check inscope."
+	echo "  -o, --output-file  File to save results"
+	echo "  -h, --help         Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com"
+	exit 1
 }
 
 # Parse input arguments
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift ;;
-        -i|--inscope) INSCOPE=true;;
-        -o|--output) OUTPUTFILE="$2"; shift ;;  # New output flag
-        -h|--help) display_help ;;
-        *) echo "Unknown parameter passed: $1"; display_help ;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		domain="$2"
+		shift
+		;;
+	-i | --inscope) INSCOPE=true ;;
+	-o | --output)
+		OUTPUTFILE="$2"
+		shift
+		;; # New output flag
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		display_help
+		;;
+	esac
+	shift
 done
 
 # Validate domain
-if [ -z "$domain" ]; then
-    echo "Error: Domain not provided."
-    display_help
-    exit 1
+if [[ -z ${DOMAIN} ]]; then
+	echo "Error: Domain not provided."
+	display_help
+	exit 1
 fi
 
-if [ -n "$OUTPUTFILE" ]; then
-    touch "$OUTPUTFILE" 2>/dev/null || { echo "Error: Cannot write to the specified output file."; exit 1; }
+if [[ -n ${OUTPUTFILE} ]]; then
+	touch "${OUTPUTFILE}" 2>/dev/null || {
+		echo "Error: Cannot write to the specified output file."
+		exit 1
+	}
 fi
 
 # Call the domain validation script
-rftw_util_validatedomain "$domain" || exit 1
+rftw_util_validatedomain "${DOMAIN}" || exit 1
 
 mkdir -p .tmp 2>/dev/null
-if [[ $(echo "${RANDOM}thistotallynotexist${RANDOM}.$domain" | dnsx -r $resolvers -rcode noerror,nxdomain -retry 3 -silent | cut -d' ' -f2) == "[NXDOMAIN]" ]]; then 
-    if [ "$DEEP" = true ]; then
-        dnsx -d $domain -r $resolvers -silent -rcode noerror -w $subs_wordlist_big | cut -d' ' -f1 | anew -q .tmp/subs_noerror.txt 2>>"$LOGFILE" >/dev/null
-    else
-        dnsx -d $domain -r $resolvers -silent -rcode noerror -w $subs_wordlist | cut -d' ' -f1 | anew -q .tmp/subs_noerror.txt 2>>"$LOGFILE" >/dev/null
-    fi
-    # Output handling
-    if [ -n "$OUTPUTFILE" ]; then
-        cat .tmp/subs_noerror.txt > "$OUTPUTFILE"
-    else
-        cat .tmp/subs_noerror.txt
-    fi
-    [[ "$INSCOPE" = true ]] && check_inscope .tmp/subs_noerror.txt 2>>"$LOGFILE" >/dev/null
-else 
-	printf "\n${yellow} Detected DNSSEC black lies, skipping this technique ${reset}\n" 
+if [[ $(echo "${RANDOM}thistotallynotexist${RANDOM}.${domain}" | dnsx -r $resolvers -rcode noerror,nxdomain -retry 3 -silent | cut -d' ' -f2) == "[NXDOMAIN]" ]]; then
+	if [[ $DEEP == true ]]; then
+		dnsx -d "${DOMAIN}" -r $resolvers -silent -rcode noerror -w $subs_wordlist_big | cut -d' ' -f1 | anew -q .tmp/subs_noerror.txt 2>>"${LOGFILE}" >/dev/null
+	else
+		dnsx -d "${DOMAIN}" -r $resolvers -silent -rcode noerror -w $subs_wordlist | cut -d' ' -f1 | anew -q .tmp/subs_noerror.txt 2>>"${LOGFILE}" >/dev/null
+	fi
+	# Output handling
+	if [[ -n ${OUTPUTFILE} ]]; then
+		cat .tmp/subs_noerror.txt >"${OUTPUTFILE}"
+	else
+		cat .tmp/subs_noerror.txt
+	fi
+	[[ ${INSCOPE} == true ]] && check_inscope .tmp/subs_noerror.txt 2>>"${LOGFILE}" >/dev/null
+else
+	printf "\n${yellow} Detected DNSSEC black lies, skipping this technique ${reset}\n"
 fi
diff --git a/bin/rftw_sub_regex b/bin/rftw_sub_regex
--- a/bin/rftw_sub_regex
+++ b/bin/rftw_sub_regex
@@ -32,35 +32,25 @@ if [[ -z "$SUBREGEXPERMUTE" || -z "$called_fn_dir" || -z "$DIFF" ]]; then
 fi
 
 sub_regex_permut() {
-    if { [ ! -f "$called_fn_dir/.${FUNCNAME[0]}" ] || [ "$DIFF" = true ]; } && [ "$SUBREGEXPERMUTE" = true ]; then
-        start_subfunc ${FUNCNAME[0]} "Running : Permutations by regex analysis"
-		cd "$tools/regulator" || { echo "Failed to cd directory in ${FUNCNAME[0]} @ line ${LINENO}"; exit 1; }
-		python3 main.py -t $domain -f ${dir}/subdomains/subdomains.txt -o ${dir}/.tmp/${domain}.brute
-		cd "$dir" || { echo "Failed to cd to $dir in ${FUNCNAME[0]} @ line ${LINENO}"; exit 1; }
+		cd "${tools}/regulator" || { echo "Failed to cd directory in ${FUNCNAME[0]} @ line ${LINENO}"; exit 1; }
+		python3 main.py -t "${DOMAIN}" -f ${dir}/subdomains/subdomains.txt -o ${dir}/.tmp/${domain}.brute
+		cd "${dir}" || { echo "Failed to cd to $dir in ${FUNCNAME[0]} @ line ${LINENO}"; exit 1; }
 
-		if [ ! "$AXIOM" = true ]; then
+		if [[ ! ${AXIOM} = true ]]; then
 			resolvers_update_quick_local
-			[ -s ".tmp/${domain}.brute" ] && puredns resolve .tmp/${domain}.brute -w .tmp/regulator.txt -r $resolvers --resolvers-trusted $resolvers_trusted -l $PUREDNS_PUBLIC_LIMIT --rate-limit-trusted $PUREDNS_TRUSTED_LIMIT --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT 2>>"$LOGFILE" >/dev/null
+			[[ -s ".tmp/${domain}.brute" ]] && puredns resolve .tmp/${domain}.brute -w .tmp/regulator.txt -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}" 2>>"${LOGFILE}" >/dev/null
 		else
 			resolvers_update_quick_axiom
-			[ -s ".tmp/${domain}.brute" ] && axiom-scan .tmp/${domain}.brute -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/regulator.txt $AXIOM_EXTRA_ARGS 2>>"$LOGFILE" >/dev/null
+			[[ -s ".tmp/${domain}.brute" ]] && axiom-scan .tmp/${domain}.brute -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/regulator.txt "${AXIOM_EXTRA_ARGS}" 2>>"${LOGFILE}" >/dev/null
 		fi
 		
-		if [ -s ".tmp/regulator.txt" ]; then
-			[ -s "$outOfScope_file" ] && deleteOutScoped $outOfScope_file .tmp/regulator.txt
-			[[ "$INSCOPE" = true ]] && check_inscope .tmp/regulator.txt 2>>"$LOGFILE" >/dev/null
-			NUMOFLINES=$(cat .tmp/regulator.txt 2>>"$LOGFILE" | grep ".$domain$" | anew subdomains/subdomains.txt | sed '/^$/d' | wc -l)
+		if [[ -s ".tmp/regulator.txt" ]]; then
+			[[ -s "$outOfScope_file" ]] && deleteOutScoped $outOfScope_file .tmp/regulator.txt
+			[[ "${INSCOPE}" = true ]] && check_inscope .tmp/regulator.txt 2>>"${LOGFILE}" >/dev/null
+			NUMOFLINES=$(cat .tmp/regulator.txt 2>>"${LOGFILE}" | grep ".$domain$" | anew subdomains/subdomains.txt | sed '/^$/d' | wc -l)
 		else
 			NUMOFLINES=0
 		fi
-		end_subfunc "${NUMOFLINES} new subs (permutations by regex)" ${FUNCNAME[0]}
-    else
-        if [ "$SUBREGEXPERMUTE" = false ]; then
-            printf "\n${yellow} ${FUNCNAME[0]} skipped in this mode or defined in reconftw.cfg ${reset}\n"
-        else
-            printf "${yellow} ${FUNCNAME[0]} is already processed, to force executing ${FUNCNAME[0]} delete\n    $called_fn_dir/.${FUNCNAME[0]} ${reset}\n\n"
-        fi
-    fi
 }
 
 # Execute the main function
diff --git a/bin/rftw_util_ascii b/bin/rftw_util_ascii
--- a/bin/rftw_util_ascii
+++ b/bin/rftw_util_ascii
@@ -2,11 +2,11 @@
 
 # Load environment variables from reconftw.cfg
 # Load environment variables
-if [ -f "reconftw.cfg" ]; then
-    source reconftw.cfg
+if [[ -f "reconftw.cfg" ]]; then
+	source reconftw.cfg
 else
-    echo "Error: reconftw.cfg not found!"
-    exit 1
+	echo "Error: reconftw.cfg not found!"
+	exit 1
 fi
 
 # Colors for console output
@@ -16,41 +16,41 @@ reset="\033[0m"
 
 # Help menu function
 function display_help() {
-    echo "$(basename "$0") [FILE]"
-    echo
-    echo "Checks if the provided file contains ASCII text."
-    echo "Options:"
-    echo "  -h, --help    Display this help and exit"
-    echo
+	echo "$(basename "$0") [FILE]"
+	echo
+	echo "Checks if the provided file contains ASCII text."
+	echo "Options:"
+	echo "  -h, --help    Display this help and exit"
+	echo
 }
 
 # Validate arguments function
 function validate_args() {
-    if [[ -z "$1" ]]; then
-        echo -e "${red}Error: FILE is required.${reset}"
-        display_help
-        exit 1
-    fi
-    if [[ ! -f "$1" ]]; then
-        echo -e "${red}Error: $1 is not a file.${reset}"
-        exit 2
-    fi
+	if [[ -z $1 ]]; then
+		echo -e "${red}Error: FILE is required.${reset}"
+		display_help
+		exit 1
+	fi
+	if [[ ! -f $1 ]]; then
+		echo -e "${red}Error: $1 is not a file.${reset}"
+		exit 2
+	fi
 }
 
 # Check ASCII text function
 function is_ascii_text() {
-    local filepath="$1"
-    if [[ $(file "$filepath" | grep -o 'ASCII text$') == "ASCII text" ]]; then
-        echo -e "${green}$filepath contains ASCII text.${reset}"
-    else
-        echo -e "${red}$filepath does not contain ASCII text.${reset}"
-    fi
+	local filepath="$1"
+	if [[ $(file "${filepath}" | grep -o 'ASCII text$') == "ASCII text" ]]; then
+		echo -e "${green}${filepath} contains ASCII text.${reset}"
+	else
+		echo -e "${red}${filepath} does not contain ASCII text.${reset}"
+	fi
 }
 
 # Main script execution
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-    display_help
-    exit 0
+if [[ $1 == "-h" || $1 == "--help" ]]; then
+	display_help
+	exit 0
 fi
 
 validate_args "$1"
diff --git a/bin/rftw_util_inscope b/bin/rftw_util_inscope
--- a/bin/rftw_util_inscope
+++ b/bin/rftw_util_inscope
@@ -2,49 +2,52 @@
 
 # Help Menu
 function display_help() {
-    echo "$(basename "$0") -f <file>"
-    echo "Options:"
-    echo "  -f, --file            Specify the input file to check inscope."
-    echo "  -h, --help            Display this help menu."
+	echo "$(basename "$0") -f <file>"
+	echo "Options:"
+	echo "  -f, --file            Specify the input file to check inscope."
+	echo "  -h, --help            Display this help menu."
 }
 
 # check_inscope function
 function check_inscope() {
-    echo "Checking inscope for $1"
-    cat $1 | inscope > $1_tmp && cp $1_tmp $1 && rm -f $1_tmp
+	echo "Checking inscope for $1"
+	cat $1 | inscope >$1_tmp && cp $1_tmp $1 && rm -f $1_tmp
 }
 
 # Variables for input
 input_file=""
 
 # Input validation and argument parsing
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -f|--file) 
-            input_file="$2"; 
-            shift;;
-        -h|--help) 
-            display_help; 
-            exit 0;;
-        *) 
-            echo "Unknown parameter passed: $1"; 
-            display_help; 
-            exit 1;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
+		;;
+	-h | --help)
+		display_help
+		exit 0
+		;;
+	*)
+		echo "Unknown parameter passed: $1"
+		display_help
+		exit 1
+		;;
+	esac
+	shift
 done
 
 # Validate input file
-if [ -z "$input_file" ]; then
-    echo "Error: Input file not provided."
-    display_help
-    exit 1
+if [[ -z ${input_file} ]]; then
+	echo "Error: Input file not provided."
+	display_help
+	exit 1
 fi
 
-if [ ! -f "$input_file" ]; then
-    echo "Error: Specified input file does not exist."
-    exit 1
+if [[ ! -f ${input_file} ]]; then
+	echo "Error: Specified input file does not exist."
+	exit 1
 fi
 
 # Call the check_inscope function
-check_inscope "$input_file"
+check_inscope "${input_file}"
diff --git a/bin/rftw_util_notification b/bin/rftw_util_notification
--- a/bin/rftw_util_notification
+++ b/bin/rftw_util_notification
@@ -2,11 +2,11 @@
 
 # Load environment variables from reconftw.cfg
 # Load environment variables
-if [ -f "reconftw.cfg" ]; then
-    source reconftw.cfg
+if [[ -f "reconftw.cfg" ]]; then
+	source reconftw.cfg
 else
-    echo "Error: reconftw.cfg not found!"
-    exit 1
+	echo "Error: reconftw.cfg not found!"
+	exit 1
 fi
 
 # Colors for console output
@@ -18,57 +18,57 @@ bgreen="\033[1;32m"
 
 # Help menu function
 function display_help() {
-    echo "$(basename "$0") <message> <type>"
-    echo
-    echo "Sends notification based on the given message and type."
-    echo "Types:"
-    echo "  info   - Informational message (Blue)"
-    echo "  warn   - Warning message (Yellow)"
-    echo "  error  - Error message (Red)"
-    echo "  good   - Positive message (Green)"
-    echo 
-    echo "Options:"
-    echo "  -h, --help    Display this help and exit"
-    echo
+	echo "$(basename "$0") <message> <type>"
+	echo
+	echo "Sends notification based on the given message and type."
+	echo "Types:"
+	echo "  info   - Informational message (Blue)"
+	echo "  warn   - Warning message (Yellow)"
+	echo "  error  - Error message (Red)"
+	echo "  good   - Positive message (Green)"
+	echo
+	echo "Options:"
+	echo "  -h, --help    Display this help and exit"
+	echo
 }
 
 # Send notification function
 function notification() {
-    local message=$1
-    local type=$2
-    local text=""
-    
-    if [[ -z "$message" || -z "$type" ]]; then
-        echo -e "${bred}Error: Both message and type are required.${reset}"
-        exit 2
-    fi
+	local message=$1
+	local type=$2
+	local text=""
 
-    case $type in
-        info)
-            text="\n${bblue} ${message} ${reset}"
-            ;;
-        warn)
-            text="\n${yellow} ${message} ${reset}"
-            ;;
-        error)
-            text="\n${bred} ${message} ${reset}"
-            ;;
-        good)
-            text="\n${bgreen} ${message} ${reset}"
-            ;;
-        *)
-            echo -e "${bred}Error: Invalid type. Valid types are: info, warn, error, good.${reset}"
-            exit 2
-            ;;
-    esac
+	if [[ -z ${message} || -z ${type} ]]; then
+		echo -e "${bred}Error: Both message and type are required.${reset}"
+		exit 2
+	fi
 
-    printf "${text}\n" && printf "${text} - ${domain}\n" | $NOTIFY
+	case $type in
+	info)
+		text="\n${bblue} ${message} ${reset}"
+		;;
+	warn)
+		text="\n${yellow} ${message} ${reset}"
+		;;
+	error)
+		text="\n${bred} ${message} ${reset}"
+		;;
+	good)
+		text="\n${bgreen} ${message} ${reset}"
+		;;
+	*)
+		echo -e "${bred}Error: Invalid type. Valid types are: info, warn, error, good.${reset}"
+		exit 2
+		;;
+	esac
+
+	printf "${text}\n" && printf "${text} - ${domain}\n" | ${NOTIFY}
 }
 
 # Main script execution
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-    display_help
-    exit 0
+if [[ $1 == "-h" || $1 == "--help" ]]; then
+	display_help
+	exit 0
 fi
 
 notification "$1" "$2"
diff --git a/bin/rftw_util_tools b/bin/rftw_util_tools
--- a/bin/rftw_util_tools
+++ b/bin/rftw_util_tools
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 # Default config path
-CONFIG_PATH="$RECONFTW_CFG"
+CONFIG_PATH="${RECONFTW_CFG}"
 
 # Check if the config file exists
-if [ -f "$CONFIG_PATH" ]; then
-    source "$CONFIG_PATH"
+if [[ -f "${CONFIG_PATH}" ]]; then
+    source "${CONFIG_PATH}"
 else
-    echo "Error: reconftw.cfg not found at $CONFIG_PATH!"
+    echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
     exit 1
 fi
 
@@ -27,86 +27,86 @@ function tools_installed() {
 
 	allinstalled=true
 
-	[ -n "$GOPATH" ] || { printf "${bred} [*] GOPATH var			[NO]${reset}\n"; allinstalled=false;}
-	[ -n "$GOROOT" ] || { printf "${bred} [*] GOROOT var			[NO]${reset}\n"; allinstalled=false;}
-	[ -n "$PATH" ] || { printf "${bred} [*] PATH var			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/dorks_hunter/dorks_hunter.py" ] || { printf "${bred} [*] dorks_hunter		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/brutespray/brutespray.py" ] || { printf "${bred} [*] brutespray			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/fav-up/favUp.py" ] || { printf "${bred} [*] fav-up			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/Corsy/corsy.py" ] || { printf "${bred} [*] Corsy			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/testssl.sh/testssl.sh" ] || { printf "${bred} [*] testssl			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/CMSeeK/cmseek.py" ] || { printf "${bred} [*] CMSeeK			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${fuzz_wordlist}" ] || { printf "${bred} [*] OneListForAll		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${lfi_wordlist}" ] || { printf "${bred} [*] lfi_wordlist		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${ssti_wordlist}" ] || { printf "${bred} [*] ssti_wordlist		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${subs_wordlist}" ] || { printf "${bred} [*] subs_wordlist		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${subs_wordlist_big}" ] || { printf "${bred} [*] subs_wordlist_big		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${resolvers}" ] || { printf "${bred} [*] resolvers		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "${resolvers_trusted}" ] || { printf "${bred} [*] resolvers_trusted		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/xnLinkFinder/xnLinkFinder.py" ] || { printf "${bred} [*] xnLinkFinder		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/waymore/waymore.py" ] || { printf "${bred} [*] waymore		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/commix/commix.py" ] || { printf "${bred} [*] commix			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/getjswords.py" ] || { printf "${bred} [*] getjswords   		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/JSA/jsa.py" ] || { printf "${bred} [*] JSA			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/cloud_enum/cloud_enum.py" ] || { printf "${bred} [*] cloud_enum			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/ultimate-nmap-parser/ultimate-nmap-parser.sh" ] || { printf "${bred} [*] nmap-parse-output		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/pydictor/pydictor.py" ] || { printf "${bred} [*] pydictor   		[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/urless/urless/urless.py" ] || { printf "${bred} [*] urless			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/smuggler/smuggler.py" ] || { printf "${bred} [*] smuggler			[NO]${reset}\n"; allinstalled=false;}
-	[ -f "$tools/regulator/main.py" ] || { printf "${bred} [*] regulator			[NO]${reset}\n"; allinstalled=false;}
-	which github-endpoints &>/dev/null || { printf "${bred} [*] github-endpoints		[NO]${reset}\n"; allinstalled=false;}
-	which github-subdomains &>/dev/null || { printf "${bred} [*] github-subdomains		[NO]${reset}\n"; allinstalled=false;}
-	which gitlab-subdomains &>/dev/null || { printf "${bred} [*] gitlab-subdomains		[NO]${reset}\n"; allinstalled=false;}
-	which katana &>/dev/null || { printf "${bred} [*] katana			[NO]${reset}\n"; allinstalled=false;}
-	which wafw00f &>/dev/null || { printf "${bred} [*] wafw00f			[NO]${reset}\n"; allinstalled=false;}
-	which dnsvalidator &>/dev/null || { printf "${bred} [*] dnsvalidator		[NO]${reset}\n"; allinstalled=false;}
-	which gowitness &>/dev/null || { printf "${bred} [*] gowitness			[NO]${reset}\n"; allinstalled=false;}
-	which amass &>/dev/null || { printf "${bred} [*] Amass			[NO]${reset}\n"; allinstalled=false;}
-	which dnsx &>/dev/null || { printf "${bred} [*] dnsx			[NO]${reset}\n"; allinstalled=false;}
-	which gotator &>/dev/null || { printf "${bred} [*] gotator			[NO]${reset}\n"; allinstalled=false;}
-	which nuclei &>/dev/null || { printf "${bred} [*] Nuclei			[NO]${reset}\n"; allinstalled=false;}
-	[ -d ${NUCLEI_TEMPLATES_PATH} ] || { printf "${bred} [*] Nuclei templates	[NO]${reset}\n"; allinstalled=false;}
-	[ -d ${tools}/fuzzing-templates ] || { printf "${bred} [*] Fuzzing templates	[NO]${reset}\n"; allinstalled=false;}
-	which gf &>/dev/null || { printf "${bred} [*] Gf				[NO]${reset}\n"; allinstalled=false;}
-	which Gxss &>/dev/null || { printf "${bred} [*] Gxss			[NO]${reset}\n"; allinstalled=false;}
-	which subjs &>/dev/null || { printf "${bred} [*] subjs			[NO]${reset}\n"; allinstalled=false;}
-	which ffuf &>/dev/null || { printf "${bred} [*] ffuf			[NO]${reset}\n"; allinstalled=false;}
-	which massdns &>/dev/null || { printf "${bred} [*] Massdns			[NO]${reset}\n"; allinstalled=false;}
-	which qsreplace &>/dev/null || { printf "${bred} [*] qsreplace			[NO]${reset}\n"; allinstalled=false;}
-	which interlace &>/dev/null || { printf "${bred} [*] interlace			[NO]${reset}\n"; allinstalled=false;}
-	which anew &>/dev/null || { printf "${bred} [*] Anew			[NO]${reset}\n"; allinstalled=false;}
-	which unfurl &>/dev/null || { printf "${bred} [*] unfurl			[NO]${reset}\n"; allinstalled=false;}
-	which crlfuzz &>/dev/null || { printf "${bred} [*] crlfuzz			[NO]${reset}\n"; allinstalled=false;}
-	which httpx &>/dev/null || { printf "${bred} [*] Httpx			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which jq &>/dev/null || { printf "${bred} [*] jq				[NO]${reset}\n${reset}"; allinstalled=false;}
-	which notify &>/dev/null || { printf "${bred} [*] notify			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which dalfox &>/dev/null || { printf "${bred} [*] dalfox			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which puredns &>/dev/null || { printf "${bred} [*] puredns			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which emailfinder &>/dev/null || { printf "${bred} [*] emailfinder		[NO]${reset}\n"; allinstalled=false;}
-	which analyticsrelationships &>/dev/null || { printf "${bred} [*] analyticsrelationships	[NO]${reset}\n"; allinstalled=false;}
-	which mapcidr &>/dev/null || { printf "${bred} [*] mapcidr			[NO]${reset}\n"; allinstalled=false;}
-	which ppfuzz &>/dev/null || { printf "${bred} [*] ppfuzz			[NO]${reset}\n"; allinstalled=false;}
-	which cdncheck &>/dev/null || { printf "${bred} [*] cdncheck			[NO]${reset}\n"; allinstalled=false;}
-	which interactsh-client &>/dev/null || { printf "${bred} [*] interactsh-client		[NO]${reset}\n"; allinstalled=false;}
-	which tlsx &>/dev/null || { printf "${bred} [*] tlsx			[NO]${reset}\n"; allinstalled=false;}
-	which smap &>/dev/null || { printf "${bred} [*] smap			[NO]${reset}\n"; allinstalled=false;}
-	which gitdorks_go &>/dev/null || { printf "${bred} [*] gitdorks_go		[NO]${reset}\n"; allinstalled=false;}
-	which ripgen &>/dev/null || { printf "${bred} [*] ripgen			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which dsieve &>/dev/null || { printf "${bred} [*] dsieve			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which inscope &>/dev/null || { printf "${bred} [*] inscope			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which enumerepo &>/dev/null || { printf "${bred} [*] enumerepo			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which Web-Cache-Vulnerability-Scanner &>/dev/null || { printf "${bred} [*] Web-Cache-Vulnerability-Scanner [NO]${reset}\n"; allinstalled=false;}
-	which subfinder &>/dev/null || { printf "${bred} [*] subfinder			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which byp4xx &>/dev/null || { printf "${bred} [*] byp4xx			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which ghauri &>/dev/null || { printf "${bred} [*] ghauri			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which hakip2host &>/dev/null || { printf "${bred} [*] hakip2host			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which gau &>/dev/null || { printf "${bred} [*] gau			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which crt &>/dev/null || { printf "${bred}  [*] crt			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which gitleaks &>/dev/null || { printf "${bred} [*] gitleaks			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which trufflehog &>/dev/null || { printf "${bred} [*] trufflehog			[NO]${reset}\n${reset}"; allinstalled=false;}
-	which s3scanner &>/dev/null || { printf "${bred} [*] s3scanner			[NO]${reset}\n${reset}"; allinstalled=false;}
+	[[ -n "$GOPATH" ]] || { printf "${bred} [*] GOPATH var			[NO]${reset}\n"; allinstalled=false;}
+	[[ -n "$GOROOT" ]] || { printf "${bred} [*] GOROOT var			[NO]${reset}\n"; allinstalled=false;}
+	[[ -n "$PATH" ]] || { printf "${bred} [*] PATH var			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/dorks_hunter/dorks_hunter.py" ]] || { printf "${bred} [*] dorks_hunter		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/brutespray/brutespray.py" ]] || { printf "${bred} [*] brutespray			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/fav-up/favUp.py" ]] || { printf "${bred} [*] fav-up			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/Corsy/corsy.py" ]] || { printf "${bred} [*] Corsy			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/testssl.sh/testssl.sh" ]] || { printf "${bred} [*] testssl			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/CMSeeK/cmseek.py" ]] || { printf "${bred} [*] CMSeeK			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${fuzz_wordlist}" ]] || { printf "${bred} [*] OneListForAll		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${lfi_wordlist}" ]] || { printf "${bred} [*] lfi_wordlist		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${ssti_wordlist}" ]] || { printf "${bred} [*] ssti_wordlist		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${subs_wordlist}" ]] || { printf "${bred} [*] subs_wordlist		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${subs_wordlist_big}" ]] || { printf "${bred} [*] subs_wordlist_big		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${resolvers}" ]] || { printf "${bred} [*] resolvers		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${resolvers_trusted}" ]] || { printf "${bred} [*] resolvers_trusted		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/xnLinkFinder/xnLinkFinder.py" ]] || { printf "${bred} [*] xnLinkFinder		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/waymore/waymore.py" ]] || { printf "${bred} [*] waymore		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/commix/commix.py" ]] || { printf "${bred} [*] commix			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/getjswords.py" ]] || { printf "${bred} [*] getjswords   		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/JSA/jsa.py" ]] || { printf "${bred} [*] JSA			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/cloud_enum/cloud_enum.py" ]] || { printf "${bred} [*] cloud_enum			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/ultimate-nmap-parser/ultimate-nmap-parser.sh" ]] || { printf "${bred} [*] nmap-parse-output		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/pydictor/pydictor.py" ]] || { printf "${bred} [*] pydictor   		[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/urless/urless/urless.py" ]] || { printf "${bred} [*] urless			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/smuggler/smuggler.py" ]] || { printf "${bred} [*] smuggler			[NO]${reset}\n"; allinstalled=false;}
+	[[ -f "${tools}/regulator/main.py" ]] || { printf "${bred} [*] regulator			[NO]${reset}\n"; allinstalled=false;}
+	command -v github-endpoints &>/dev/null || { printf "${bred} [*] github-endpoints		[NO]${reset}\n"; allinstalled=false;}
+	command -v github-subdomains &>/dev/null || { printf "${bred} [*] github-subdomains		[NO]${reset}\n"; allinstalled=false;}
+	command -v gitlab-subdomains &>/dev/null || { printf "${bred} [*] gitlab-subdomains		[NO]${reset}\n"; allinstalled=false;}
+	command -v katana &>/dev/null || { printf "${bred} [*] katana			[NO]${reset}\n"; allinstalled=false;}
+	command -v wafw00f &>/dev/null || { printf "${bred} [*] wafw00f			[NO]${reset}\n"; allinstalled=false;}
+	command -v dnsvalidator &>/dev/null || { printf "${bred} [*] dnsvalidator		[NO]${reset}\n"; allinstalled=false;}
+	command -v gowitness &>/dev/null || { printf "${bred} [*] gowitness			[NO]${reset}\n"; allinstalled=false;}
+	command -v amass &>/dev/null || { printf "${bred} [*] Amass			[NO]${reset}\n"; allinstalled=false;}
+	command -v dnsx &>/dev/null || { printf "${bred} [*] dnsx			[NO]${reset}\n"; allinstalled=false;}
+	command -v gotator &>/dev/null || { printf "${bred} [*] gotator			[NO]${reset}\n"; allinstalled=false;}
+	command -v nuclei &>/dev/null || { printf "${bred} [*] Nuclei			[NO]${reset}\n"; allinstalled=false;}
+	[[ -d ${NUCLEI_TEMPLATES_PATH} ]] || { printf "${bred} [*] Nuclei templates	[NO]${reset}\n"; allinstalled=false;}
+	[[ -d ${tools}/fuzzing-templates ]] || { printf "${bred} [*] Fuzzing templates	[NO]${reset}\n"; allinstalled=false;}
+	command -v gf &>/dev/null || { printf "${bred} [*] Gf				[NO]${reset}\n"; allinstalled=false;}
+	command -v Gxss &>/dev/null || { printf "${bred} [*] Gxss			[NO]${reset}\n"; allinstalled=false;}
+	command -v subjs &>/dev/null || { printf "${bred} [*] subjs			[NO]${reset}\n"; allinstalled=false;}
+	command -v ffuf &>/dev/null || { printf "${bred} [*] ffuf			[NO]${reset}\n"; allinstalled=false;}
+	command -v massdns &>/dev/null || { printf "${bred} [*] Massdns			[NO]${reset}\n"; allinstalled=false;}
+	command -v qsreplace &>/dev/null || { printf "${bred} [*] qsreplace			[NO]${reset}\n"; allinstalled=false;}
+	command -v interlace &>/dev/null || { printf "${bred} [*] interlace			[NO]${reset}\n"; allinstalled=false;}
+	command -v anew &>/dev/null || { printf "${bred} [*] Anew			[NO]${reset}\n"; allinstalled=false;}
+	command -v unfurl &>/dev/null || { printf "${bred} [*] unfurl			[NO]${reset}\n"; allinstalled=false;}
+	command -v crlfuzz &>/dev/null || { printf "${bred} [*] crlfuzz			[NO]${reset}\n"; allinstalled=false;}
+	command -v httpx &>/dev/null || { printf "${bred} [*] Httpx			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v jq &>/dev/null || { printf "${bred} [*] jq				[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v notify &>/dev/null || { printf "${bred} [*] notify			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v dalfox &>/dev/null || { printf "${bred} [*] dalfox			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v puredns &>/dev/null || { printf "${bred} [*] puredns			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v emailfinder &>/dev/null || { printf "${bred} [*] emailfinder		[NO]${reset}\n"; allinstalled=false;}
+	command -v analyticsrelationships &>/dev/null || { printf "${bred} [*] analyticsrelationships	[NO]${reset}\n"; allinstalled=false;}
+	command -v mapcidr &>/dev/null || { printf "${bred} [*] mapcidr			[NO]${reset}\n"; allinstalled=false;}
+	command -v ppfuzz &>/dev/null || { printf "${bred} [*] ppfuzz			[NO]${reset}\n"; allinstalled=false;}
+	command -v cdncheck &>/dev/null || { printf "${bred} [*] cdncheck			[NO]${reset}\n"; allinstalled=false;}
+	command -v interactsh-client &>/dev/null || { printf "${bred} [*] interactsh-client		[NO]${reset}\n"; allinstalled=false;}
+	command -v tlsx &>/dev/null || { printf "${bred} [*] tlsx			[NO]${reset}\n"; allinstalled=false;}
+	command -v smap &>/dev/null || { printf "${bred} [*] smap			[NO]${reset}\n"; allinstalled=false;}
+	command -v gitdorks_go &>/dev/null || { printf "${bred} [*] gitdorks_go		[NO]${reset}\n"; allinstalled=false;}
+	command -v ripgen &>/dev/null || { printf "${bred} [*] ripgen			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v dsieve &>/dev/null || { printf "${bred} [*] dsieve			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v inscope &>/dev/null || { printf "${bred} [*] inscope			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v enumerepo &>/dev/null || { printf "${bred} [*] enumerepo			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v Web-Cache-Vulnerability-Scanner &>/dev/null || { printf "${bred} [*] Web-Cache-Vulnerability-Scanner [NO]${reset}\n"; allinstalled=false;}
+	command -v subfinder &>/dev/null || { printf "${bred} [*] subfinder			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v byp4xx &>/dev/null || { printf "${bred} [*] byp4xx			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v ghauri &>/dev/null || { printf "${bred} [*] ghauri			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v hakip2host &>/dev/null || { printf "${bred} [*] hakip2host			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v gau &>/dev/null || { printf "${bred} [*] gau			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v crt &>/dev/null || { printf "${bred}  [*] crt			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v gitleaks &>/dev/null || { printf "${bred} [*] gitleaks			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v trufflehog &>/dev/null || { printf "${bred} [*] trufflehog			[NO]${reset}\n${reset}"; allinstalled=false;}
+	command -v s3scanner &>/dev/null || { printf "${bred} [*] s3scanner			[NO]${reset}\n${reset}"; allinstalled=false;}
 	
-	if [ "${allinstalled}" = true ]; then
+	if [[ "${allinstalled}" = true ]]; then
 		printf "${bgreen} Good! All installed! ${reset}\n\n"
 	else
 		printf "\n${yellow} Try running the installer script again ./install.sh"
@@ -132,7 +132,7 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 # Validate tools directory
-if [ -z "$tools_dir" ]; then
+if [[ -z "${tools_dir}" ]]; then
     echo -e "${bred}Error: Tools directory not specified.${reset}" >&2
     help_menu
     exit 1
diff --git a/bin/rftw_util_validatedomain b/bin/rftw_util_validatedomain
--- a/bin/rftw_util_validatedomain
+++ b/bin/rftw_util_validatedomain
@@ -9,20 +9,20 @@ DOMAIN_VALIDATION_REGEX="^(?:[a-zA-Z0-9]+:\/\/)?(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[
 
 # Function to validate the domain
 validate_domain() {
-    local domain="$1"
-    if [[ $domain =~ $DOMAIN_VALIDATION_REGEX ]]; then
-        echo "Valid domain/URL."
-        exit 0
-    else
-        echo "Invalid domain/URL."
-        exit 1
-    fi
+	local DOMAIN="$1"
+	if [[ ${DOMAIN} =~ ${DOMAIN_VALIDATION_REGEX} ]]; then
+		echo "Valid domain/URL."
+		exit 0
+	else
+		echo "Invalid domain/URL."
+		exit 1
+	fi
 }
 
 # Check if a domain is provided
-if [ "$#" -ne 1 ]; then
-    echo "$(basename "$0") <domain/website/URL>"
-    exit 1
+if [[ $# -ne 1 ]]; then
+	echo "$(basename "$0") <domain/website/URL>"
+	exit 1
 fi
 
 # Call the validation function
diff --git a/bin/rftw_vuln_4xx b/bin/rftw_vuln_4xx
--- a/bin/rftw_vuln_4xx
+++ b/bin/rftw_vuln_4xx
@@ -2,7 +2,7 @@
 
 # Load environment variables from reconftw.cfg
 # Load environment variables
-if [ -f "reconftw.cfg" ]; then
+if [[ -f "reconftw.cfg" ]]; then
     source reconftw.cfg
 else
     echo "Error: reconftw.cfg not found!"
@@ -25,11 +25,11 @@ function display_help() {
 
 # Validate requirements function
 function validate_requirements() {
-    if ! [ -x "$(command -v byp4xx)" ]; then
+    if ! [[ -x "$(command -v byp4xx)" ]]; then
         echo "Error: byp4xx not found." >&2
         exit 1
     fi
-    if ! [ -f "fuzzing/fuzzing_full.txt" ]; then
+    if ! [[ -f "fuzzing/fuzzing_full.txt" ]]; then
         echo "Error: fuzzing_full.txt not found." >&2
         exit 1
     fi
@@ -37,20 +37,20 @@ function validate_requirements() {
 
 # 4XX Bypass test function
 function bypass_4xx_test() {
-    if { [ ! -f "$called_fn_dir/.4xxbypass" ] || [ "$DIFF" = true ]; } && [ "$BYPASSER4XX" = true ]; then
-        if [[ $(cat fuzzing/fuzzing_full.txt 2>/dev/null | grep -E '^4' | grep -Ev '^404' | cut -d ' ' -f3 | wc -l) -le 1000 ]] || [ "$DEEP" = true ]; then
+    if { [[ ! -f "${called_fn_dir}/.4xxbypass" ]] || [[ "$DIFF" = true ]]; } && [[ "$BYPASSER4XX" = true ]]; then
+        if [[ $(cat fuzzing/fuzzing_full.txt 2>/dev/null | grep -E '^4' | grep -Ev '^404' | cut -d ' ' -f3 | wc -l) -le 1000 ]] || [[ "$DEEP" = true ]]; then
             echo "[*] Starting 403 bypass"
-            cat $dir/fuzzing/fuzzing_full.txt 2>/dev/null | grep -E '^4' | grep -Ev '^404' | cut -d ' ' -f3 > $dir/.tmp/403test.txt
-            cd "$tools/byp4xx" || { echo "Failed to cd directory in 4xxbypass @ line ${LINENO}"; exit 1; }
-            byp4xx -threads $BYP4XX_THREADS $dir/.tmp/403test.txt > $dir/.tmp/byp4xx.txt
-            cd "$dir" || { echo "Failed to cd directory in 4xxbypass @ line ${LINENO}"; exit 1; }
-            [ -s ".tmp/byp4xx.txt" ] && cat .tmp/byp4xx.txt | anew -q vulns/byp4xx.txt
+            cat "${dir}"/fuzzing/fuzzing_full.txt 2>/dev/null | grep -E '^4' | grep -Ev '^404' | cut -d ' ' -f3 > "${dir}"/.tmp/403test.txt
+            cd "${tools}/byp4xx" || { echo "Failed to cd directory in 4xxbypass @ line ${LINENO}"; exit 1; }
+            byp4xx -threads $BYP4XX_THREADS "${dir}"/.tmp/403test.txt > "${dir}"/.tmp/byp4xx.txt
+            cd "${dir}" || { echo "Failed to cd directory in 4xxbypass @ line ${LINENO}"; exit 1; }
+            [[ -s ".tmp/byp4xx.txt" ]] && cat .tmp/byp4xx.txt | anew -q vulns/byp4xx.txt
             echo "[+] Results are saved in vulns/byp4xx.txt"
         else
             echo "[!] Too many URLs to bypass, skipping"
         fi
     else
-        if [ "$BYPASSER4XX" = false ]; then
+        if [[ "$BYPASSER4XX" = false ]]; then
             echo -e "\n${yellow} 4xxbypass skipped in this mode or defined in reconftw.cfg ${reset}"
         else
             echo -e "${yellow} 4xxbypass is already processed, to force executing 4xxbypass delete\n    $called_fn_dir/.4xxbypass ${reset}\n"
diff --git a/bin/rftw_web_cms b/bin/rftw_web_cms
--- a/bin/rftw_web_cms
+++ b/bin/rftw_web_cms
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-# Load environment variables from reconftw.cfg
 # Load environment variables
-if [ -f "reconftw.cfg" ]; then
+if [[ -f "reconftw.cfg" ]]; then
 	source reconftw.cfg
 else
 	echo "Error: reconftw.cfg not found!"
@@ -50,43 +49,28 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-if { [ ! -f "$called_fn_dir/.cms_scanner" ] || [ "$FORCE" = true ]; } && [ "$CMS_SCANNER" = true ]; then
-	start_func "cms_scanner" "CMS Scanner"
-
-	mkdir -p $dir/cms && rm -rf $dir/cms/*
-	anew -q .tmp/webs_all.txt < <(cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null)
-
-	if [ -s ".tmp/webs_all.txt" ]; then
-		tr '\n' ',' <.tmp/webs_all.txt >.tmp/cms.txt
-timeout -k 1m ${CMSSCAN_TIMEOUT}s python3 $tools/CMSeeK/cmseek.py -l .tmp/cms.txt --batch -r 2>>"$LOGFILE" >/dev/null
-		exit_status=$?
-		if [[ $exit_status -eq 125 ]]; then
-			echo "TIMEOUT cmseek.py - investigate manually for $dir" >>"$LOGFILE"
-			end_func "TIMEOUT cmseek.py - investigate manually for $dir" "cms_scanner"
-			exit 1
-		elif [[ $exit_status -ne 0 ]]; then
-			echo "ERROR cmseek.py - investigate manually for $dir" >>"$LOGFILE"
-			end_func "ERROR cmseek.py - investigate manually for $dir" "cms_scanner"
-			exit 1
+mkdir -p "${dir}"/cms && rm -rf "${dir}"/cms/*
+anew -q .tmp/webs_all.txt < <(cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null)
+if [[ -s ".tmp/webs_all.txt" ]]; then
+	tr '\n' ',' <.tmp/webs_all.txt >.tmp/cms.txt
+	timeout -k 1m ${CMSSCAN_TIMEOUT}s python3"${tools}"/CMSeeK/cmseek.py -l .tmp/cms.txt --batch -r 2>>"${LOGFILE}" >/dev/null
+	exit_status=$?
+	if [[ $exit_status -eq 125 ]]; then
+		echo "TIMEOUT cmseek.py - investigate manually for $dir" >>"${LOGFILE}"
+		end_func "TIMEOUT cmseek.py - investigate manually for $dir" "cms_scanner"
+		exit 1
+	elif [[ $exit_status -ne 0 ]]; then
+		echo "ERROR cmseek.py - investigate manually for $dir" >>"${LOGFILE}"
+		end_func "ERROR cmseek.py - investigate manually for $dir" "cms_scanner"
+		exit 1
+	fi
+	while read -r sub; do
+		sub_out=$(echo "$sub" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
+		cms_id=$(jq -r 'try .cms_id' "${tools}/CMSeeK/Result/${sub_out}/cms.json" 2>/dev/null)
+		if [[ -z $cms_id ]]; then
+			rm -rf "${tools}/CMSeeK/Result/${sub_out}"
+		else
+			mv -f "${tools}/CMSeeK/Result/${sub_out}" "${dir}"/cms/ 2>>"${LOGFILE}"
 		fi
-		while read -r sub; do
-			sub_out=$(echo "$sub" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
-			cms_id=$(jq -r 'try .cms_id' "$tools/CMSeeK/Result/${sub_out}/cms.json" 2>/dev/null)
-			if [ -z "$cms_id" ]; then
-				rm -rf "$tools/CMSeeK/Result/${sub_out}"
-			else
-				mv -f "$tools/CMSeeK/Result/${sub_out}" $dir/cms/ 2>>"$LOGFILE"
-			fi
-		done <.tmp/webs_all.txt
-
-		end_func "Results are saved in $domain/cms/*subdomain* folder" "cms_scanner"
-	else
-		end_func "No $domain/web/webs.txts file found, cms scanner skipped" "cms_scanner"
-	fi
-else
-	if [ "$CMS_SCANNER" = false ]; then
-		printf "\n${yellow} cms_scanner skipped in this mode or defined in reconftw.cfg ${reset}\n"
-	else
-		printf "${yellow} cms_scanner is already processed. To force executing cms_scanner, delete\n    $called_fn_dir/.cms_scanner ${reset}\n\n"
-	fi
+	done <.tmp/webs_all.txt
 fi
