Tests and starting style improvements

diff --git a/bin/rftw_ip_favicon b/bin/rftw_ip_favicon
--- a/bin/rftw_ip_favicon
+++ b/bin/rftw_ip_favicon
@@ -2,71 +2,83 @@
 # Looks good, needs testing
 
 # Load environment variables
-if [ -f "reconftw.cfg" ]; then
-    source reconftw.cfg
+if [[ -f "reconftw.cfg" ]]; then
+	source reconftw.cfg
 else
-    echo "Error: reconftw.cfg not found!"
-    exit 1
+	echo "Error: reconftw.cfg not found!"
+	exit 1
 fi
 
 help_menu() {
-  echo "$(basename "$0") [OPTIONS] DOMAIN"
-  echo ""
-  echo "Favicon Ip Lookup Tool"
-  echo ""
-  echo "Options:"
-  echo "  -h, --help            Show this help menu"
-  echo "  -d, --domain DOMAIN   Specify the domain to process"
-  echo "  -f, --force           Force the execution even if already processed"
+	echo "$(basename "$0") [OPTIONS] DOMAIN"
+	echo ""
+	echo "Favicon Ip Lookup Tool"
+	echo ""
+	echo "Options:"
+	echo "  -h, --help            Show this help menu"
+	echo "  -d, --domain DOMAIN   Specify the domain to process"
 }
 
 # Start function
 start_func() {
-    echo "Starting $1..."
+	echo "Starting $1..."
 }
 
 # End function
 end_func() {
-    echo "$1"
-    echo "End of $2..."
+	echo "$1"
+	echo "End of $2..."
 }
 
 # Default values
-FORCE=false
 DOMAIN=""
 
 # Parse arguments
-while [[ "$#" -gt 0 ]]; do
-  case $1 in
-    -h|--help) help_menu; exit 0 ;;
-    -d|--domain) DOMAIN="$2"; shift ;;
-    -f|--force) FORCE=true ;;
-    *)
-      # Set the domain if it's not specified with -d
-      [ -z "$DOMAIN" ] && DOMAIN="$1" || { echo "Unknown parameter passed: $1"; exit 1; }
-      ;;
-  esac
-  shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-h | --help)
+		help_menu
+		exit 0
+		;;
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	*)
+		# Set the domain if it's not specified with -d
+		[ -z "$DOMAIN" ] && DOMAIN="$1" || {
+			echo "Unknown parameter passed: $1"
+			exit 1
+		}
+		;;
+	esac
+	shift
 done
 
 # Input validation
 if [ -z "$DOMAIN" ]; then
-  help_menu
-  exit 1
+	help_menu
+	exit 1
 fi
 
 # Validate domain format
-if [[ ! "$DOMAIN" =~ ^[a-zA-Z0-9.-]+$ ]]; then
-    echo "Invalid domain format."
-    exit 1
+if [[ ! $DOMAIN =~ ^[a-zA-Z0-9.-]+$ ]]; then
+	echo "Invalid domain format."
+	exit 1
 fi
 
-pushd "$tools/fav-up" &>/dev/null || { echo "Failed to cd to $tools/fav-up in favicon"; exit 1; }
+pushd "$tools/fav-up" &>/dev/null || {
+	echo "Failed to cd to $tools/fav-up in favicon"
+	exit 1
+}
 python3 favUp.py -w "$DOMAIN" -sc -o favicontest.json
 if [ -s "favicontest.json" ]; then
-    jq -r 'try .found_ips' favicontest.json | grep -v "not-found" > favicontest.txt
-    sed -i "s/|/\n/g" favicontest.txt
+	jq -r 'try .found_ips' favicontest.json | grep -v "not-found" >favicontest.txt
+	sed -i "s/|/\n/g" favicontest.txt
 fi
-popd &>/dev/null || { echo "Failed to cd back from favicon"; exit 1; }
+popd &>/dev/null || {
+	echo "Failed to cd back from favicon"
+	exit 1
+}
 [ -s "$tools/fav-up/favicontest.txt" ] && cp $tools/fav-up/favicontest.txt .
 cat favicontest.txt
diff --git a/bin/rftw_osint_whois b/bin/rftw_osint_whois
--- a/bin/rftw_osint_whois
+++ b/bin/rftw_osint_whois
@@ -2,31 +2,34 @@
 
 # Help menu
 function help_menu() {
-    echo -e "$(basename "$0") [OPTIONS]"
-    echo -e "Search for domain information."
-    echo -e "Options:"
-    echo -e "  -d, --domain DOMAIN   Specify the domain target"
-    echo -e "  -o, --output DIR      (Optional) Specify the output directory (default: osint/)"
-    echo -e "  -h, --help            Display this help menu"
-    exit 1
+	echo -e "$(basename "$0") [OPTIONS]"
+	echo -e "Search for domain information."
+	echo -e "Options:"
+	echo -e "  -d, --domain DOMAIN   Specify the domain target"
+	echo -e "  -o, --output DIR      (Optional) Specify the output directory (default: osint/)"
+	echo -e "  -h, --help            Display this help menu"
+	exit 1
 }
 
 # Main function to gather domain info
 function domain_info_func() {
-    echo "[*] Searching domain info (whois, registrant name/email domains)"
-    
-    # Domain General Info
-    whois -H "$domain" > "${output_dir}/domain_info_general.txt" || { echo "whois command failed"; exit 1; }
-    
-    # Reverse Whois (if DEEP or REVERSE_WHOIS is true)
-    if [ "$DEEP" = true ] || [ "$REVERSE_WHOIS" = true ]; then
-        timeout -k 1m ${AMASS_INTEL_TIMEOUT}m amass intel -d "${domain}" -whois -timeout $AMASS_INTEL_TIMEOUT -o "${output_dir}/domain_info_reverse_whois.txt" 2>>"$LOGFILE" &>/dev/null
-    fi
-    
-    # Azure Tenant Domains
-    curl -s "https://aadinternals.azurewebsites.net/api/tenantinfo?domainName=${domain}" -H "Origin: https://aadinternals.com" | jq -r .domains[].name > "${output_dir}/azure_tenant_domains.txt"
+	echo "[*] Searching domain info (whois, registrant name/email domains)"
 
-    echo "[+] Results are saved in ${output_dir}/domain_info_[general/name/email/ip].txt"
+	# Domain General Info
+	whois -H "$domain" >"${output_dir}/domain_info_general.txt" || {
+		echo "whois command failed"
+		exit 1
+	}
+
+	# Reverse Whois (if DEEP or REVERSE_WHOIS is true)
+	if [ "$DEEP" = true ] || [ "$REVERSE_WHOIS" = true ]; then
+        timeout -k 1m ${AMASS_INTEL_TIMEOUT}m amass intel -d "${domain}" -whois -timeout $AMASS_INTEL_TIMEOUT -o "${output_dir}/domain_info_reverse_whois.txt" 2>>"$LOGFILE" >> /dev/null
+	fi
+
+	# Azure Tenant Domains
+	curl -s "https://aadinternals.azurewebsites.net/api/tenantinfo?domainName=${domain}" -H "Origin: https://aadinternals.com" | jq -r .domains[].name >"${output_dir}/azure_tenant_domains.txt"
+
+	echo "[+] Results are saved in ${output_dir}/domain_info_[general/name/email/ip].txt"
 }
 
 # Default values
@@ -34,14 +37,23 @@ domain=""
 output_dir="osint"
 
 # Parse command-line arguments
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift ;;
-        -o|--output) output_dir="$2"; shift ;;
-        -h|--help) help_menu ;;
-        *) echo -e "${bred}Unknown parameter passed: $1${reset}" >&2; help_menu ;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		domain="$2"
+		shift
+		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) help_menu ;;
+	*)
+		echo -e "${bred}Unknown parameter passed: $1${reset}" >&2
+		help_menu
+		;;
+	esac
+	shift
 done
 
 # Validate the domain using the utility script
@@ -49,9 +61,9 @@ rftw_util_validatedomain "$domain" || exit 1
 
 # Validate inputs
 if [ -z "$domain" ]; then
-    echo -e "${bred}Error: Missing required parameters.${reset}" >&2
-    help_menu
-    exit 1
+	echo -e "${bred}Error: Missing required parameters.${reset}" >&2
+	help_menu
+	exit 1
 fi
 
 # Execute the main function
diff --git a/bin/rftw_sub_passive b/bin/rftw_sub_passive
--- a/bin/rftw_sub_passive
+++ b/bin/rftw_sub_passive
@@ -2,48 +2,67 @@
 
 # Help Menu
 function display_help() {
-    echo "$(basename "$0") [OPTIONS]"
-    echo "Options:"
-    echo "  -d, --domain          Set the target domain."
-    echo "  -a, --amass           Run amass."
-    echo "  -s, --subfinder       Run subfinder."
-    echo "  -g, --github-tokens   Specify GitHub tokens file."
-    echo "  -l, --gitlab-tokens   Specify GitLab tokens file."
-    echo "  -D, --deep            Run in deep mode."
-    echo "  -i, --inscope         Check inscope."
-    echo "  -o, --output          Specify the output file."
-    echo "  -h, --help            Display this help menu."
+	echo "$(basename "$0") [OPTIONS]"
+	echo "Options:"
+	echo "  -d, --domain          Set the target domain."
+	echo "  -a, --amass           Run amass."
+	echo "  -s, --subfinder       Run subfinder."
+	echo "  -g, --github-tokens   Specify GitHub tokens file."
+	echo "  -l, --gitlab-tokens   Specify GitLab tokens file."
+	echo "  -D, --deep            Run in deep mode."
+	echo "  -i, --inscope         Check inscope."
+	echo "  -o, --output          Specify the output file."
+	echo "  -h, --help            Display this help menu."
 }
 
 # Variables for input and output
 output_file=""
 
 # Input validation and argument parsing
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -d|--domain) domain="$2"; shift;;
-        -a|--amass) RUNAMASS=true;;
-        -s|--subfinder) RUNSUBFINDER=true;;
-        -g|--github-tokens) GITHUB_TOKENS="$2"; shift;;
-        -l|--gitlab-tokens) GITLAB_TOKENS="$2"; shift;;
-        -D|--deep) DEEP=true;;
-        -i|--inscope) INSCOPE=true;;
-        -o|--output) 
-            shift;
-            output_file="$1";
-            touch "$output_file" 2>/dev/null || { echo "Error: Cannot write to the specified output file."; exit 1; }
-            ;;
-        -h|--help) display_help; exit 0;;
-        *) echo "Unknown parameter passed: $1"; display_help; exit 1;;
-    esac
-    shift
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		domain="$2"
+		shift
+		;;
+	-a | --amass) RUNAMASS=true ;;
+	-s | --subfinder) RUNSUBFINDER=true ;;
+	-g | --github-tokens)
+		GITHUB_TOKENS="$2"
+		shift
+		;;
+	-l | --gitlab-tokens)
+		GITLAB_TOKENS="$2"
+		shift
+		;;
+	-D | --deep) DEEP=true ;;
+	-i | --inscope) INSCOPE=true ;;
+	-o | --output)
+		shift
+		output_file="$1"
+		touch "$output_file" 2>/dev/null || {
+			echo "Error: Cannot write to the specified output file."
+			exit 1
+		}
+		;;
+	-h | --help)
+		display_help
+		exit 0
+		;;
+	*)
+		echo "Unknown parameter passed: $1"
+		display_help
+		exit 1
+		;;
+	esac
+	shift
 done
 
 # Validate domain
 if [ -z "$domain" ]; then
-    echo "Error: Domain not provided."
-    display_help
-    exit 1
+	echo "Error: Domain not provided."
+	display_help
+	exit 1
 fi
 
 # Call the domain validation script
@@ -51,27 +70,29 @@ rftw_util_validatedomain "$domain" || exit 1
 
 # Main functionality
 
-[[ $RUNAMASS == true ]] && timeout -k 1m ${AMASS_ENUM_TIMEOUT} amass enum -passive -d $domain -config $AMASS_CONFIG -timeout $AMASS_ENUM_TIMEOUT -json .tmp/amass_json.json 2>>"$LOGFILE" &>/dev/null
+if [[ $RUNAMASS == true ]]; then
+	timeout -k 1m ${AMASS_ENUM_TIMEOUT} amass enum -passive -d $domain -config $AMASS_CONFIG -timeout $AMASS_ENUM_TIMEOUT -json .tmp/amass_json.json 2>>"$LOGFILE" >/dev/null
+fi
 [ -s ".tmp/amass_json.json" ] && cat .tmp/amass_json.json | jq -r '.name' | anew -q .tmp/amass_psub.txt
-[[ $RUNSUBFINDER == true ]] && subfinder -all -d "$domain" -silent -o .tmp/subfinder_psub.txt 2>>"$LOGFILE" >/dev/null		
+[[ $RUNSUBFINDER == true ]] && subfinder -all -d "$domain" -silent -o .tmp/subfinder_psub.txt 2>>"$LOGFILE" >/dev/null
 if [ -s "${GITHUB_TOKENS}" ]; then
-    if [ "$DEEP" = true ]; then
-        github-subdomains -d $domain -t $GITHUB_TOKENS -o .tmp/github_subdomains_psub.txt 2>>"$LOGFILE" >/dev/null
-    else
-        github-subdomains -d $domain -k -q -t $GITHUB_TOKENS -o .tmp/github_subdomains_psub.txt 2>>"$LOGFILE" >/dev/null
-    fi
+	if [ "$DEEP" = true ]; then
+		github-subdomains -d $domain -t $GITHUB_TOKENS -o .tmp/github_subdomains_psub.txt 2>>"$LOGFILE" >/dev/null
+	else
+		github-subdomains -d $domain -k -q -t $GITHUB_TOKENS -o .tmp/github_subdomains_psub.txt 2>>"$LOGFILE" >/dev/null
+	fi
 fi
 if [ -s "${GITLAB_TOKENS}" ]; then
-    gitlab-subdomains -d $domain -t $GITLAB_TOKENS > .tmp/gitlab_subdomains_psub.txt 2>>"$LOGFILE" >/dev/null
+gitlab-subdomains -d "$domain" -t "$GITLAB_TOKENS" 2>>"$LOGFILE" | tee .tmp/gitlab_subdomains_psub.txt >/dev/null
 fi
 # Check inscope if the flag is set
-if [[ "$INSCOPE" = true ]]; then
-    rftw_util_inscope .tmp/amass_psub.txt
-    rftw_util_inscope .tmp/subfinder_psub.txt
-    rftw_util_inscope .tmp/github_subdomains_psub.txt
-    rftw_util_inscope .tmp/gitlab_subdomains_psub.txt
+if [[ $INSCOPE == true ]]; then
+	rftw_util_inscope .tmp/amass_psub.txt
+	rftw_util_inscope .tmp/subfinder_psub.txt
+	rftw_util_inscope .tmp/github_subdomains_psub.txt
+	rftw_util_inscope .tmp/gitlab_subdomains_psub.txt
 fi
 # Save results to the specified output file if provided
 if [ -n "$output_file" ]; then
-    cat .tmp/*_psub.txt > "$output_file"
+	cat .tmp/*_psub.txt >"$output_file"
 fi
