Dropped web interface, keep testing and fixing things

diff --git a/bin/rftw_sub_crt b/bin/rftw_sub_crt
--- a/bin/rftw_sub_crt
+++ b/bin/rftw_sub_crt
@@ -4,35 +4,24 @@
 function display_help() {
     echo "Usage: $0 [OPTIONS]"
     echo "Options:"
-    echo "  -d, --domain          Set the target domain."
+    echo "  -d, --domain          Set the target domain. (Required)"
     echo "  -l, --limit           Set the crt limit (default 100)."
-    echo "  -D, --diff            Set DIFF to true."
-    echo "  -s, --subcrt          Run crt subdomain enumeration."
-    echo "  -i, --inscope         Check inscope."
-    echo "  -o, --output          Specify the output file."
+    echo "  -o, --output          Specify the output file. (Optional)"
     echo "  -h, --help            Display this help menu."
-}
-
-# Other functions
-function start_subfunc() {
-    echo "[+] Starting $1: $2"
-}
-
-function end_subfunc() {
-    echo "[+] Ending $1: $2"
 }
 
 # Variables for input and output
 output_file=""
+user_set_limit=false  # Variable to check if user set the limit
 
 # Input validation and argument parsing
 while [[ "$#" -gt 0 ]]; do
     case $1 in
         -d|--domain) domain="$2"; shift;;
-        -l|--limit) CTR_LIMIT="$2"; shift;;
-        -D|--diff) DIFF=true;;
-        -s|--subcrt) SUBCRT=true;;
-        -i|--inscope) INSCOPE=true;;
+        -l|--limit) 
+            CTR_LIMIT_LOCAL="$2"; 
+            user_set_limit=true;  # User set the limit
+            shift;;
         -o|--output) 
             shift;
             output_file="$1";
@@ -44,5 +33,29 @@ while [[ "$#" -gt 0 ]]; do
     shift
 done
 
+if [[ "$user_set_limit" == false ]]; then
+    CTR_LIMIT_LOCAL=$CTR_LIMIT
+fi
+
+# Validate domain
+if [ -z "$domain" ]; then
+    echo "Error: Domain not provided."
+    display_help
+    exit 1
+fi
+
+# Call the domain validation script
+rftw_util_validatedomain "$domain" || exit 1
+
 # Main Functionality
-crt -s -json -l ${CTR_LIMIT} $domain 2>>"$LOGFILE" | jq -r '.[].subdomain' 2>>"$LOGFILE" | sed -e "s/^\\*\\.//" | anew -q .tmp/crtsh_subs_tmp.txt 2>>"$LOGFILE" >/dev/null
+crt -s -json -l ${CTR_LIMIT_LOCAL} $domain 2>>"$LOGFILE" | jq -r '.[].subdomain' 2>>"$LOGFILE" | sed -e "s/^\\*\\.//" | anew -q .tmp/crtsh_subs_tmp.txt 2>>"$LOGFILE" >/dev/null
+
+# Check inscope
+rftw_util_inscope .tmp/crtsh_subs_tmp.txt
+
+# Save results to the specified output file if provided
+if [ -n "$output_file" ]; then
+    cat .tmp/crtsh_subs_tmp.txt > "$output_file"
+else
+    cat .tmp/crtsh_subs_tmp.txt
+fi
