hosts and partial webs

diff --git a/bin/rftw_ip_cdnprovider b/bin/rftw_ip_cdnprovider
--- a/bin/rftw_ip_cdnprovider
+++ b/bin/rftw_ip_cdnprovider
@@ -10,65 +10,55 @@ else
     echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
     exit 1
 fi
-
-# Help function
-help_menu() {
-	cat <<-EOF
-		Usage: $(basename "$0") [OPTIONS] -i <input_file>
-
-		CDN Provider Check Tool
-
-		Options:
-		  -h, --help            Show this help menu
-		  -i, --input           Specify the input IP lists file (required)
-		  -f, --force           Force the execution even if already processed
-		  -o, --output          Specify the output file (default is print to stdout)
-	EOF
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing IPs for port scan (Required)"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f file.txt -o dir"
+	exit 1
 }
 
-# Default values
-INPUT_FILE=""
-OUTPUT_FILE=""
-
-# Parse arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-i | --input)
-		INPUT_FILE="$2"
+	-f | --file)
+		DOMAIN_FILE="$2"
 		shift
-		;;
-	-h | --help)
-		help_menu
-		exit 0
 		;;
 	-o | --output)
 		OUTPUT_FILE="$2"
 		shift
 		;;
+	-h | --help) display_help ;;
 	*)
-		if [[ -z ${INPUT_FILE} ]]; then
-			INPUT_FILE=$1
-		else
-			echo "Unknown parameter passed: $1"
-			exit 1
-		fi
+		echo "Unknown parameter passed: $1"
+		exit 1
 		;;
 	esac
 	shift
 done
 
-# Validate input file
-if [[ ! -f ${INPUT_FILE} ]] || [[ ! -s ${INPUT_FILE} ]]; then
-	echo "Invalid or empty input file!"
-	help_menu
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] ; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
 	exit 1
 fi
 
 # Handle the output of the cdncheck command based on the presence of the -o flag
 if [[ -z ${OUTPUT_FILE} ]]; then
-	cdncheck -silent -resp -nc <"${INPUT_FILE}"
+	cdncheck -silent -resp -nc <"${DOMAIN_FILE}"
 else
-	cdncheck -silent -resp -nc <"${INPUT_FILE}" >temp.txt
+	cdncheck -silent -resp -nc <"${DOMAIN_FILE}" >temp.txt
 	sort -u temp.txt >"${OUTPUT_FILE}"
 	rm temp.txt
 fi
diff --git a/bin/rftw_ip_favicon b/bin/rftw_ip_favicon
--- a/bin/rftw_ip_favicon
+++ b/bin/rftw_ip_favicon
@@ -1,5 +1,4 @@
 #!/bin/bash
-# Looks good, needs testing
 
 # Default config path
 CONFIG_PATH="${RECONFTW_CFG}"
@@ -11,75 +10,75 @@ else
     echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
     exit 1
 fi
-
-help_menu() {
-	echo "$(basename "$0") [OPTIONS] DOMAIN"
-	echo ""
-	echo "Favicon Ip Lookup Tool"
-	echo ""
-	echo "Options:"
-	echo "  -h, --help            Show this help menu"
-	echo "  -d, --domain DOMAIN   Specify the domain to process"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
-# Start function
-start_func() {
-	echo "Starting $1..."
-}
+# Variables for input and output
+output_file=""
 
-# End function
-end_func() {
-	echo "$1"
-	echo "End of $2..."
-}
-
-# Default values
-DOMAIN=""
-
-# Parse arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
-		;;
 	-d | --domain)
 		DOMAIN="$2"
 		shift
 		;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
-		# Set the domain if it's not specified with -d
-		if [[ -z ${DOMAIN} ]]; then
-			DOMAIN="$1"
-		fi
+		echo "Unknown parameter passed: $1"
+		exit 1
 		;;
 	esac
 	shift
 done
 
 # Input validation
-if [[ -z ${DOMAIN} ]]; then
-	help_menu
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
 	exit 1
 fi
 
-# Validate domain format
-if [[ ! ${DOMAIN} =~ ^[a-zA-Z0-9.-]+$ ]]; then
-	echo "Invalid domain format."
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
 	exit 1
 fi
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
+
 
 pushd "${tools}/fav-up" &>/dev/null || {
 	echo "Failed to cd to ${tools}/fav-up in favicon"
 	exit 1
 }
 python3 favUp.py -w "${DOMAIN}" -sc -o favicontest.json
+
 if [[ -s "favicontest.json" ]]; then
 	jq -r 'try .found_ips' favicontest.json >temp.txt
 	grep -v "not-found" temp.txt >favicontest.txt
 	rm temp.txt
 	sed -i "s/|/\n/g" favicontest.txt
+	mv favicontest.txt ${output_file}
 fi
+
 popd &>/dev/null || {
 	echo "Failed to cd back from favicon"
 	exit 1
diff --git a/bin/rftw_ip_portscan b/bin/rftw_ip_portscan
--- a/bin/rftw_ip_portscan
+++ b/bin/rftw_ip_portscan
@@ -10,46 +10,33 @@ else
     echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
     exit 1
 fi
-
-# Help function
-help_menu() {
-	echo "$(basename "$0") [OPTIONS] DOMAIN"
-	echo ""
-	echo "Port Scan Tool"
-	echo ""
-	echo "Options:"
-	echo "  -h, --help            Show this help menu"
-	echo "  -d, --domain DOMAIN   Specify the domain to process"
-}
-
-# Start function
-start_func() {
-	echo "Starting $1..."
-}
-
-# End function
-end_func() {
-	echo "$1"
-	echo "End of $2..."
-}
-
-# Input validation
-if [[ -z $1 ]]; then
-	help_menu
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing IPs for port scan (Required)"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f file.txt -o dir"
 	exit 1
-fi
+}
 
-# Parse arguments
+# Variables for input and output
+output_dir=""
+
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
-		;;
-	-d | --domain)
-		DOMAIN="$2"
+	-f | --file)
+		DOMAIN_FILE="$2"
 		shift
 		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
 		echo "Unknown parameter passed: $1"
 		exit 1
@@ -58,32 +45,31 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-# Validate domain format
-if [[ ! ${DOMAIN} =~ ^[a-zA-Z0-9.-]+$ ]] && ! [[ ${DOMAIN} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-	echo "Invalid domain format."
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] ; then
+	display_help
 	exit 1
 fi
 
-if ! [[ ${DOMAIN} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-	# The following checks and actions are based on the original function logic
-	[[ -s "subdomains/subdomains_dnsregs.json" ]] && jq -r 'try . | "\(.host) \(.a[0])"' subdomains/subdomains_dnsregs.json | anew -q .tmp/subs_ips.txt
-	[[ -s ".tmp/subs_ips.txt" ]] && awk '{ print $2 " " $1}' .tmp/subs_ips.txt | sort -k2 -n | anew -q hosts/subs_ips_vhosts.txt
-	[[ -s "hosts/subs_ips_vhosts.txt" ]] && cut -d ' ' -f1 hosts/subs_ips_vhosts.txt | grep -aEiv "^(127|10|169\.154|172\.1[6789]|172\.2[0-9]|172\.3[01]|192\.168)\." | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | anew -q hosts/ips.txt
-else
-	echo "${DOMAIN}" | grep -aEiv "^(127|10|169\.154|172\.1[6789]|172\.2[0-9]|172\.3[01]|192\.168)\." | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | anew -q hosts/ips.txt
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
 fi
-[[ ! -s "hosts/cdn_providers.txt" ]] && [[ -s "hosts/ips.txt" ]] && cdncheck -silent -resp -nc <hosts/ips.txt 2>/dev/null >hosts/cdn_providers.txt
-[[ -s "hosts/ips.txt" ]] && comm -23 <(sort -u hosts/ips.txt) <(cut -d'[' -f1 hosts/cdn_providers.txt | sed 's/[[:space:]]*$//' | sort -u) | grep -aEiv "^(127|10|169\.154|172\.1[6789]|172\.2[0-9]|172\.3[01]|192\.168)\." | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort -u | anew -q .tmp/ips_nocdn.txt
+
+mkdir -p .tmp 2>/dev/null
+cdncheck -silent -resp -nc <${DOMAIN_FILE} 2>/dev/null >${output_dir}/cdn_providers.txt
+comm -23 <(sort -u ${DOMAIN_FILE}) <(cut -d'[' -f1 ${output_dir}/cdn_providers.txt | sed 's/[[:space:]]*$//' | sort -u) | grep -aEiv "^(127|10|169\.154|172\.1[6789]|172\.2[0-9]|172\.3[01]|192\.168)\." | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort -u | anew -q .tmp/ips_nocdn.txt
 printf "${bblue}\n Resolved IP addresses (No CDN) ${reset}\n\n"
 [[ -s ".tmp/ips_nocdn.txt" ]] && sort .tmp/ips_nocdn.txt
 printf "${bblue}\n Scanning ports... ${reset}\n\n"
-if [[ $PORTSCAN_PASSIVE == true ]] && [[ ! -f "hosts/portscan_passive.txt" ]] && [[ -s ".tmp/ips_nocdn.txt" ]]; then
-	smap -iL .tmp/ips_nocdn.txt >hosts/portscan_passive.txt
+if [[ $PORTSCAN_PASSIVE == true ]] && [[ ! -f "${output_dir}/portscan_passive.txt" ]] && [[ -s ".tmp/ips_nocdn.txt" ]]; then
+	smap -iL .tmp/ips_nocdn.txt >${output_dir}/portscan_passive.txt
 fi
 if [[ $PORTSCAN_ACTIVE == true ]]; then
 	if [[ ${AXIOM} == true ]]; then
-		[[ -s ".tmp/ips_nocdn.txt" ]] && axiom-scan .tmp/ips_nocdn.txt -m nmapx --top-ports 200 -sV -n -Pn --open --max-retries 2 --script vulners -oA hosts/portscan_active "${AXIOM_EXTRA_ARGS}"
+		[[ -s ".tmp/ips_nocdn.txt" ]] && axiom-scan .tmp/ips_nocdn.txt -m nmapx --top-ports 200 -sV -n -Pn --open --max-retries 2 --script vulners -oA ${output_dir}/portscan_active "${AXIOM_EXTRA_ARGS}"
 	else
-		[[ -s ".tmp/ips_nocdn.txt" ]] && $SUDO nmap --top-ports 200 -sV -n --max-retries 2 -Pn --open --script vulners -iL .tmp/ips_nocdn.txt -oA hosts/portscan_active
+		[[ -s ".tmp/ips_nocdn.txt" ]] && $SUDO nmap --top-ports 200 -sV -n --max-retries 2 -Pn --open --script vulners -iL .tmp/ips_nocdn.txt -oA ${output_dir}/portscan_active
 	fi
 fi
diff --git a/bin/rftw_sub_vhosts b/bin/rftw_sub_vhosts
--- a/bin/rftw_sub_vhosts
+++ b/bin/rftw_sub_vhosts
@@ -10,62 +10,68 @@ else
     echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
     exit 1
 fi
-
-help_menu() {
-    echo "$(basename "$0") [DOMAIN] [OPTIONS]"
-    echo "Virtual Hosts discovery tool for the specified domain."
-    echo
-    echo "Options:"
-    echo "  -h, --help   Display this help menu and exit"
-    echo "  -f, --force  Force the execution even if it was already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
-validate_inputs() {
-    if [[ -z "${DOMAIN}" ]]; then
-        echo -e "${yellow} No domain provided! ${reset}"
-        exit 1
-    fi
+# Variables for input and output
+output_dir=""
 
-    if [[ "$VIRTUALHOSTS" != true ]] && [[ "$FORCE_EXECUTION" != true ]]; then
-        echo -e "${yellow} virtualhosts skipped in this mode or defined in reconftw.cfg ${reset}"
-        exit 0
-    fi
-}
-
-run_virtualhosts() {
-    start_func "virtualhosts" "Virtual Hosts discovery"
-    
-    [[ ! -s ".tmp/webs_all.txt" ]] && cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null | anew -q .tmp/webs_all.txt
-
-    if [[ -s ".tmp/webs_all.txt" ]]; then
-        mkdir -p "${dir}"/virtualhosts "${dir}"/.tmp/virtualhosts
-        interlace -tL .tmp/webs_all.txt -threads "${INTERLACE_THREADS}" -c "ffuf -ac -t ${FFUF_THREADS} -rate ${FFUF_RATELIMIT} -H \"${HEADER}\" -H \"Host: FUZZ._cleantarget_\" -w ${fuzz_wordlist} -maxtime ${FFUF_MAXTIME} -u  _target_ -of json -o _output_/_cleantarget_.json" -o "${dir}"/.tmp/virtualhosts
-
-        for sub in $(cat .tmp/webs_all.txt); do
-            sub_out=$(echo $sub | sed -e 's|^[^/]*//||' -e 's|/.*$||')
-            [[ -s ""${dir}"/.tmp/virtualhosts/${sub_out}.json" ]] && cat "${dir}"/.tmp/virtualhosts/${sub_out}.json | jq -r 'try .results[] | "\(.status) \(.length) \(.url)"' | sort | anew -q "${dir}"/virtualhosts/${sub_out}.txt
-        done
-        
-        find "${dir}"/virtualhosts/ -type f -iname "*.txt" -exec cat {} + | anew -q "${dir}"/virtualhosts/virtualhosts_full.txt
-        end_func "Results are saved in ${DOMAIN}/virtualhosts/*subdomain*.txt" "virtualhosts"
-    else
-        end_func "No${DOMAIN}//web/webs.txts file found, virtualhosts skipped " "virtualhosts"
-    fi
-}
-
-# Main
-FORCE_EXECUTION=false
-DOMAIN="$1"
-
-shift
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -h|--help) help_menu; exit 0 ;;
-        -f|--force) FORCE_EXECUTION=true; shift ;;
-        *) echo "Unknown parameter passed: $1"; exit 1 ;;
-    esac
-    shift
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		exit 1
+		;;
+	esac
+	shift
 done
 
-validate_inputs
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
+
+run_virtualhosts() {
+    mkdir -p "${output_dir}" .tmp 2>/dev/null
+    interlace -tL ${DOMAIN_FILE} -threads "${INTERLACE_THREADS}" -c "ffuf -ac -t ${FFUF_THREADS} -rate ${FFUF_RATELIMIT} -H \"${HEADER}\" -H \"Host: FUZZ._cleantarget_\" -w ${fuzz_wordlist} -maxtime ${FFUF_MAXTIME} -u  _target_ -of json -o _output_/_cleantarget_.json" -o .tmp/virtualhosts
+    for sub in $(cat ${DOMAIN_FILE}); do
+        sub_out=$(echo "${sub}" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
+        [[ -s ".tmp/virtualhosts/${sub_out}.json" ]] && cat ".tmp/virtualhosts/${sub_out}.json" | jq -r 'try .results[] | "\(.status) \(.length) \(.url)"' | sort | anew -q "${dir}/virtualhosts/${sub_out}.txt"
+    done
+    find "${dir}/virtualhosts/" -type f -iname "*.txt" -exec cat {} + | anew -q "${dir}/virtualhosts/virtualhosts_full.txt"
+}
+
 run_virtualhosts
diff --git a/bin/rftw_web_cms b/bin/rftw_web_cms
--- a/bin/rftw_web_cms
+++ b/bin/rftw_web_cms
@@ -11,39 +11,30 @@ else
     exit 1
 fi
 
-# Help function
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo ""
-	echo "CMS Scanner"
-	echo ""
-	echo "Options:"
-	echo "  -h, --help            Show this help menu"
-	echo "  -f, --force           Force the execution even if already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Start function
-start_func() {
-	echo "Starting $1: $2..."
-}
-
-# End function
-end_func() {
-	echo "$1"
-	echo "End of $2..."
-}
-
-# Default values
-FORCE=false
-
-# Parse arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
+	-f | --file)
+		input_file="$2"
+		shift
 		;;
-	-f | --force) FORCE=true ;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
 		echo "Unknown parameter passed: $1"
 		exit 1
@@ -52,28 +43,39 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-mkdir -p "${dir}"/cms && rm -rf "${dir}"/cms/*
-anew -q .tmp/webs_all.txt < <(cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null)
-if [[ -s ".tmp/webs_all.txt" ]]; then
-	tr '\n' ',' <.tmp/webs_all.txt >.tmp/cms.txt
-	timeout -k 1m ${CMSSCAN_TIMEOUT}s python3"${tools}"/CMSeeK/cmseek.py -l .tmp/cms.txt --batch -r
-	exit_status=$?
-	if [[ $exit_status -eq 125 ]]; then
-		echo "TIMEOUT cmseek.py - investigate manually for $dir"
-		end_func "TIMEOUT cmseek.py - investigate manually for $dir" "cms_scanner"
-		exit 1
-	elif [[ $exit_status -ne 0 ]]; then
-		echo "ERROR cmseek.py - investigate manually for $dir"
-		end_func "ERROR cmseek.py - investigate manually for $dir" "cms_scanner"
-		exit 1
-	fi
-	while read -r sub; do
-		sub_out=$(echo "$sub" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
-		cms_id=$(jq -r 'try .cms_id' "${tools}/CMSeeK/Result/${sub_out}/cms.json" 2>/dev/null)
-		if [[ -z $cms_id ]]; then
-			rm -rf "${tools}/CMSeeK/Result/${sub_out}"
-		else
-			mv -f "${tools}/CMSeeK/Result/${sub_out}" "${dir}"/cms/
-		fi
-	done <.tmp/webs_all.txt
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
 fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+mkdir -p .tmp 2>/dev/null
+
+tr '\n' ',' <${input_file} >.tmp/cms.txt
+timeout -k 1m ${CMSSCAN_TIMEOUT}s python3 "${tools}"/CMSeeK/cmseek.py -l .tmp/cms.txt --batch -r
+exit_status=$?
+if [[ $exit_status -eq 125 ]]; then
+	echo "TIMEOUT cmseek.py - investigate manually for $dir"
+	end_func "TIMEOUT cmseek.py - investigate manually for $dir" "cms_scanner"
+	exit 1
+elif [[ $exit_status -ne 0 ]]; then
+	echo "ERROR cmseek.py - investigate manually for $dir"
+	end_func "ERROR cmseek.py - investigate manually for $dir" "cms_scanner"
+	exit 1
+fi
+
+while read -r sub; do
+	sub_out=$(echo "$sub" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
+	cms_id=$(jq -r 'try .cms_id' "${tools}/CMSeeK/Result/${sub_out}/cms.json" 2>/dev/null)
+	if [[ -z $cms_id ]]; then
+		rm -rf "${tools}/CMSeeK/Result/${sub_out}"
+	else
+		mv -f "${tools}/CMSeeK/Result/${sub_out}" ${output_dir}/
+	fi
+done <${input_file}
diff --git a/bin/rftw_web_fuzz b/bin/rftw_web_fuzz
--- a/bin/rftw_web_fuzz
+++ b/bin/rftw_web_fuzz
@@ -11,39 +11,30 @@ else
     exit 1
 fi
 
-# Help function
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo ""
-	echo "Web Directory Fuzzing"
-	echo ""
-	echo "Options:"
-	echo "  -h, --help            Show this help menu"
-	echo "  -f, --force           Force the execution even if already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Start function
-start_func() {
-	echo "Starting $1: $2..."
-}
-
-# End function
-end_func() {
-	echo "$1"
-	echo "End of $2..."
-}
-
-# Default values
-FORCE=false
-
-# Parse arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
+	-f | --file)
+		input_file="$2"
+		shift
 		;;
-	-f | --force) FORCE=true ;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
 		echo "Unknown parameter passed: $1"
 		exit 1
@@ -52,30 +43,39 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-anew -q .tmp/webs_all.txt < <(cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null)
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
 
-if [[ -s ".tmp/webs_all.txt" ]]; then
-	mkdir -p "${dir}"/fuzzing "${dir}"/.tmp/fuzzing
-	if [[ ${AXIOM} != true ]]; then
-		interlace -tL .tmp/webs_all.txt -threads "${INTERLACE_THREADS}" -c "ffuf ${FFUF_FLAGS} -t ${FFUF_THREADS} -rate ${FFUF_RATELIMIT} -H \"${HEADER}\" -w ${fuzz_wordlist} -maxtime ${FFUF_MAXTIME} -u _target_/FUZZ -o _output_/_cleantarget_.json" -o "${dir}"/.tmp/fuzzing
-		while read -r sub; do
-			sub_out=$(echo "${sub}" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
-			if [[ -s ""${dir}"/.tmp/fuzzing/${sub_out}.json" ]]; then
-				jq -r 'try .results[] | "\(.status) \(.length) \(.url)"' <""${dir}"/.tmp/fuzzing/${sub_out}.json" | sort -k1 | anew -q "${dir}"/fuzzing/${sub_out}.txt
-			fi
-		done <.tmp/webs_all.txt
-		sort -k1 < <(find "${dir}"/fuzzing/ -type f -iname "*.txt" -exec cat {} +) | anew -q "${dir}"/fuzzing/fuzzing_full.txt
-	else
-		axiom-exec "mkdir -p /home/op/lists/seclists/Discovery/Web-Content/" &>/dev/null
-		axiom-exec "wget -q -O - ${fuzzing_remote_list} > /home/op/lists/fuzz_wordlist.txt" &>/dev/null
-		axiom-exec "wget -q -O - ${fuzzing_remote_list} > /home/op/lists/seclists/Discovery/Web-Content/big.txt" &>/dev/null
-		axiom-scan .tmp/webs_all.txt -m ffuf_base -H "${HEADER}" $FFUF_FLAGS -s -maxtime $FFUF_MAXTIME -o "${dir}"/.tmp/ffuf-content.json "${AXIOM_EXTRA_ARGS}"
-		while read -r sub; do
-			sub_out=$(echo "$sub" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
-			if [[ -s ""${dir}"/.tmp/ffuf-content.json" ]]; then
-				grep "$sub" < <(jq -r 'try .results[] | "\(.status) \(.length) \(.url)"' .tmp/ffuf-content.json) | sort -k1 | anew -q fuzzing/${sub_out}.txt
-			fi
-		done <.tmp/webs_all.txt
-		sort -k1 < <(find "${dir}"/fuzzing/ -type f -iname "*.txt" -exec cat {} +) | anew -q "${dir}"/fuzzing/fuzzing_full.txt
-	fi
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+
+mkdir -p "${output_dir}" .tmp/fuzzing 2>/dev/null
+if [[ ${AXIOM} != true ]]; then
+	interlace -tL ${input_file} -threads "${INTERLACE_THREADS}" -c "ffuf ${FFUF_FLAGS} -t ${FFUF_THREADS} -rate ${FFUF_RATELIMIT} -H \"${HEADER}\" -w ${fuzz_wordlist} -maxtime ${FFUF_MAXTIME} -u _target_/FUZZ -o _output_/_cleantarget_.json" -o .tmp/fuzzing
+	while read -r sub; do
+		sub_out=$(echo "${sub}" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
+		if [[ -s ".tmp/fuzzing/${sub_out}.json" ]]; then
+			jq -r 'try .results[] | "\(.status) \(.length) \(.url)"' <".tmp/fuzzing/${sub_out}.json" | sort -k1 | anew -q "${output_dir}/${sub_out}.txt"
+		fi
+	done <${input_file}
+	sort -k1 < <(find "${output_dir}/" -type f -iname "*.txt" -exec cat {} +) | anew -q "${output_dir}/fuzzing_full.txt"
+else
+	axiom-exec "mkdir -p /home/op/lists/seclists/Discovery/Web-Content/" &>/dev/null
+	axiom-exec "wget -q -O - ${fuzzing_remote_list} > /home/op/lists/fuzz_wordlist.txt" &>/dev/null
+	axiom-exec "wget -q -O - ${fuzzing_remote_list} > /home/op/lists/seclists/Discovery/Web-Content/big.txt" &>/dev/null
+	axiom-scan ${input_file} -m ffuf_base -H "${HEADER}" $FFUF_FLAGS -s -maxtime $FFUF_MAXTIME -o .tmp/ffuf-content.json "${AXIOM_EXTRA_ARGS}"
+	while read -r sub; do
+		sub_out=$(echo "$sub" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
+		if [[ -s ".tmp/ffuf-content.json" ]]; then
+			grep "$sub" < <(jq -r 'try .results[] | "\(.status) \(.length) \(.url)"' .tmp/ffuf-content.json) | sort -k1 | anew -q fuzzing/${sub_out}.txt
+		fi
+	done <${input_file}
+	sort -k1 < <(find "${output_dir}/" -type f -iname "*.txt" -exec cat {} +) | anew -q ${output_dir}/fuzzing_full.txt
 fi
diff --git a/bin/rftw_web_nucleicheck b/bin/rftw_web_nucleicheck
--- a/bin/rftw_web_nucleicheck
+++ b/bin/rftw_web_nucleicheck
@@ -11,35 +11,30 @@ else
     exit 1
 fi
 
-# Help function
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo ""
-	echo "Templates Based Web Scanner"
-	echo ""
-	echo "Options:"
-	echo "  -h, --help            Show this help menu"
-	echo "  -f, --force           Force the execution even if already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Start function
-start_func() {
-	echo "Starting $1: $2..."
-}
-
-# End function
-end_func() {
-	echo "$1"
-	echo "End of $2..."
-}
-
-# Parse arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
+	-f | --file)
+		input_file="$2"
+		shift
 		;;
+	-o | --output)
+		output_dir="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
 		echo "Unknown parameter passed: $1"
 		exit 1
@@ -48,25 +43,34 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
 nuclei -update
 mkdir -p nuclei_output
-anew -q .tmp/webs_all.txt < <(cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null)
-anew -q .tmp/webs_subs.txt < <(cat subdomains/subdomains.txt .tmp/webs_all.txt)
+
 if [[ ${AXIOM} != true ]]; then
 	IFS=',' read -ra severity_array <<<"$NUCLEI_SEVERITY"
 	for crit in "${severity_array[@]}"; do
 		printf "${yellow}\n Running : Nuclei $crit ${reset}\n\n"
-		nuclei $NUCLEI_FLAGS -severity $crit -nh -rl $NUCLEI_RATELIMIT -o nuclei_output/${crit}.txt <.tmp/webs_subs.txt
+		nuclei $NUCLEI_FLAGS -severity $crit -nh -rl $NUCLEI_RATELIMIT -o ${output_dir}/${crit}.txt <${input_file}
 	done
 	printf "\n\n"
 else
-	if [[ -s ".tmp/webs_subs.txt" ]]; then
-		IFS=',' read -ra severity_array <<<"$NUCLEI_SEVERITY"
-		for crit in "${severity_array[@]}"; do
-			printf "${yellow}\n Running : Nuclei $crit, check results on nuclei_output folder${reset}\n\n"
-			axiom-scan .tmp/webs_subs.txt -m nuclei --nuclei-templates ${NUCLEI_TEMPLATES_PATH} -severity ${crit} -nh -rl $NUCLEI_RATELIMIT -o nuclei_output/${crit}.txt "${AXIOM_EXTRA_ARGS}"
-			[[ -s "nuclei_output/${crit}.txt" ]] && cat nuclei_output/${crit}.txt
-		done
-		printf "\n\n"
-	fi
+	IFS=',' read -ra severity_array <<<"$NUCLEI_SEVERITY"
+	for crit in "${severity_array[@]}"; do
+		printf "${yellow}\n Running : Nuclei $crit, check results on nuclei_output folder${reset}\n\n"
+		axiom-scan ${input_file} -m nuclei --nuclei-templates ${NUCLEI_TEMPLATES_PATH} -severity ${crit} -nh -rl $NUCLEI_RATELIMIT -o ${output_dir}/${crit}.txt "${AXIOM_EXTRA_ARGS}"
+		[[ -s "${output_dir}/${crit}.txt" ]] && cat ${output_dir}/${crit}.txt
+	done
+	printf "\n\n"
 fi
diff --git a/bin/rftw_web_urlchecks b/bin/rftw_web_urlchecks
--- a/bin/rftw_web_urlchecks
+++ b/bin/rftw_web_urlchecks
@@ -11,111 +11,109 @@ else
     exit 1
 fi
 
-# Help menu function
-help_menu() {
-	echo "Usage: urlchecks.sh [OPTIONS]"
-	echo ""
-	echo "Options:"
-	echo "  -d, --domain <domain>   Specify the domain to scan."
-	echo "  -h, --help             Display this help menu."
-	echo ""
-	echo "Example:"
-	echo "  urlchecks.sh -d example.com"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output-dir        Output dir location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Input validation function
-validate_input() {
-	if [[ -z ${DOMAIN} ]]; then
-		echo "Error: Domain not specified."
-		help_menu
-		exit 1
-	fi
-}
-
-# URL checks function
-urlchecks() {
-	echo "[+] Starting URL Extraction"
-	mkdir -p js
-	[[ ! -s ".tmp/webs_all.txt" ]] && cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null | anew -q .tmp/webs_all.txt
-	if [[ -s ".tmp/webs_all.txt" ]]; then
-		if [[ ! ${AXIOM} == true ]]; then
-			if [[ $URL_CHECK_PASSIVE == true ]]; then
-				if [[ $DEEP == true ]]; then
-					cat .tmp/webs_all.txt | unfurl -u domains >.tmp/waymore_input.txt
-					python3 ${tools}/waymore/waymore.py -i .tmp/waymore_input.txt -mode U -f -oU .tmp/url_extract_tmp.txt
-				else
-					cat .tmp/webs_all.txt | gau --threads $GAU_THREADS | anew -q .tmp/url_extract_tmp.txt
-				fi
-				if [[ -s ${GITHUB_TOKENS} ]]; then
-					github-endpoints -q -k -d "${DOMAIN}" -t ${GITHUB_TOKENS} -o .tmp/github-endpoints.txt
-					[[ -s ".tmp/github-endpoints.txt" ]] && cat .tmp/github-endpoints.txt | anew -q .tmp/url_extract_tmp.txt
-				fi
-			fi
-			diff_webs=$(diff <(sort -u .tmp/probed_tmp.txt) <(sort -u .tmp/webs_all.txt) | wc -l)
-			if [[ $diff_webs != "0" ]] || [[ ! -s ".tmp/katana.txt" ]]; then
-				if [[ $URL_CHECK_ACTIVE == true ]]; then
-					if [[ $DEEP == true ]]; then
-						katana -silent -list .tmp/webs_all.txt -jc -kf all -c $KATANA_THREADS -d 3 -fs rdn -o .tmp/katana.txt
-					else
-						katana -silent -list .tmp/webs_all.txt -jc -kf all -c $KATANA_THREADS -d 2 -fs rdn -o .tmp/katana.txt
-					fi
-				fi
-			fi
-		else
-			if [[ $URL_CHECK_PASSIVE == true ]]; then
-				if [[ $DEEP == true ]]; then
-					cat .tmp/webs_all.txt | unfurl -u domains >.tmp/waymore_input.txt
-					axiom-scan .tmp/waymore_input.txt -m waymore -o .tmp/url_extract_tmp.txt "${AXIOM_EXTRA_ARGS}"
-				else
-					axiom-scan .tmp/webs_all.txt -m gau -o .tmp/url_extract_tmp.txt "${AXIOM_EXTRA_ARGS}"
-				fi
-				if [[ -s ${GITHUB_TOKENS} ]]; then
-					github-endpoints -q -k -d "${DOMAIN}" -t ${GITHUB_TOKENS} -o .tmp/github-endpoints.txt
-					[[ -s ".tmp/github-endpoints.txt" ]] && cat .tmp/github-endpoints.txt | anew -q .tmp/url_extract_tmp.txt
-				fi
-			fi
-			diff_webs=$(diff <(sort -u .tmp/probed_tmp.txt) <(sort -u .tmp/webs_all.txt) | wc -l)
-			if [[ $diff_webs != "0" ]] || [[ ! -s ".tmp/katana.txt" ]]; then
-				if [[ $URL_CHECK_ACTIVE == true ]]; then
-					if [[ $DEEP == true ]]; then
-						axiom-scan .tmp/webs_all.txt -m katana -jc -kf all -d 3 -fs rdn -fs rdn -o .tmp/katana.txt "${AXIOM_EXTRA_ARGS}"
-					else
-						axiom-scan .tmp/webs_all.txt -m katana -jc -kf all -d 2 -fs rdn -fs rdn -o .tmp/katana.txt "${AXIOM_EXTRA_ARGS}"
-					fi
-				fi
-			fi
-		fi
-		[[ -s ".tmp/katana.txt" ]] && sed -i '/^.\{2048\}./d' .tmp/katana.txt
-		[[ -s ".tmp/katana.txt" ]] && cat .tmp/katana.txt | anew -q .tmp/url_extract_tmp.txt
-		[[ -s ".tmp/url_extract_tmp.txt" ]] && cat .tmp/url_extract_tmp.txt | grep "${DOMAIN}" | grep -aEi "\.(js)" | anew -q .tmp/url_extract_js.txt
-		if [[ $DEEP == true ]]; then
-			[[ -s ".tmp/url_extract_js.txt" ]] && interlace -tL .tmp/url_extract_js.txt -threads 10 -c "python3"${tools}"/JSA/jsa.py -f target | anew -q .tmp/url_extract_tmp.txt" &>/dev/null
-		fi
-		[[ -s ".tmp/url_extract_tmp.txt" ]] && cat .tmp/url_extract_tmp.txt | grep "${DOMAIN}" | grep "=" | qsreplace -a | grep -aEiv "\.(eot|jpg|jpeg|gif|css|tif|tiff|png|ttf|otf|woff|woff2|ico|pdf|svg|txt|js)$" | anew -q .tmp/url_extract_tmp2.txt
-		[[ -s ".tmp/url_extract_tmp2.txt" ]] && cat .tmp/url_extract_tmp2.txt | python3"${tools}"/urless/urless/urless.py | anew -q .tmp/url_extract_uddup.txt
-	fi
-
-}
-
-# Parse command-line arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
-	case "$1" in
-	-d | --domain)
-		DOMAIN="$2"
-		shift 2
+	case $1 in
+	-f | --file)
+		input_file="$2"
+		shift
 		;;
-	-h | --help)
-		help_menu
-		exit 0
+	-o | --output)
+		output_dir="$2"
+		shift
 		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown parameter: $1"
-		help_menu
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
+	shift
 done
 
-# Validate input and start main function
-validate_input
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+
+
+# URL checks function
+urlchecks() {
+	mkdir -p ${output_dir} 2>/dev/null
+
+	if [[ ! ${AXIOM} == true ]]; then
+		if [[ $URL_CHECK_PASSIVE == true ]]; then
+			if [[ $DEEP == true ]]; then
+				cat ${input_file} | unfurl -u domains >${output_dir}/waymore_input.txt
+				python3 ${tools}/waymore/waymore.py -i ${output_dir}/waymore_input.txt -mode U -f -oU ${output_dir}/url_extract_tmp.txt
+			else
+				cat ${input_file} | gau --threads $GAU_THREADS | anew -q ${output_dir}/url_extract_tmp.txt
+			fi
+			if [[ -s ${GITHUB_TOKENS} ]]; then
+				github-endpoints -q -k -d "${DOMAIN}" -t ${GITHUB_TOKENS} -o ${output_dir}/github-endpoints.txt
+				[[ -s "${output_dir}/github-endpoints.txt" ]] && cat ${output_dir}/github-endpoints.txt | anew -q ${output_dir}/url_extract_tmp.txt
+			fi
+		fi
+		if [[ $URL_CHECK_ACTIVE == true ]]; then
+			if [[ $DEEP == true ]]; then
+				katana -silent -list ${input_file} -jc -kf all -c $KATANA_THREADS -d 3 -fs rdn -o ${output_dir}/katana.txt
+			else
+				katana -silent -list ${input_file} -jc -kf all -c $KATANA_THREADS -d 2 -fs rdn -o ${output_dir}/katana.txt
+			fi
+		fi
+	else
+		if [[ $URL_CHECK_PASSIVE == true ]]; then
+			if [[ $DEEP == true ]]; then
+				cat ${input_file} | unfurl -u domains >${output_dir}/waymore_input.txt
+				axiom-scan ${output_dir}/waymore_input.txt -m waymore -o ${output_dir}/url_extract_tmp.txt "${AXIOM_EXTRA_ARGS}"
+			else
+				axiom-scan ${input_file} -m gau -o ${output_dir}/url_extract_tmp.txt "${AXIOM_EXTRA_ARGS}"
+			fi
+			if [[ -s ${GITHUB_TOKENS} ]]; then
+				github-endpoints -q -k -d "${DOMAIN}" -t ${GITHUB_TOKENS} -o ${output_dir}/github-endpoints.txt
+				[[ -s "${output_dir}/github-endpoints.txt" ]] && cat ${output_dir}/github-endpoints.txt | anew -q ${output_dir}/url_extract_tmp.txt
+			fi
+		fi
+
+		if [[ $URL_CHECK_ACTIVE == true ]]; then
+			if [[ $DEEP == true ]]; then
+				axiom-scan ${input_file} -m katana -jc -kf all -d 3 -fs rdn -fs rdn -o ${output_dir}/katana.txt "${AXIOM_EXTRA_ARGS}"
+			else
+				axiom-scan ${input_file} -m katana -jc -kf all -d 2 -fs rdn -fs rdn -o ${output_dir}/katana.txt "${AXIOM_EXTRA_ARGS}"
+			fi
+		fi
+
+	fi
+	[[ -s "${output_dir}/katana.txt" ]] && sed -i '/^.\{2048\}./d' ${output_dir}/katana.txt
+	[[ -s "${output_dir}/katana.txt" ]] && cat ${output_dir}/katana.txt | anew -q ${output_dir}/url_extract_tmp.txt
+	[[ -s "${output_dir}/url_extract_tmp.txt" ]] && cat ${output_dir}/url_extract_tmp.txt | grep "${DOMAIN}" | grep -aEi "\.(js)" | anew -q ${output_dir}/url_extract_js.txt
+	if [[ $DEEP == true ]]; then
+		[[ -s "${output_dir}/url_extract_js.txt" ]] && interlace -tL ${output_dir}/url_extract_js.txt -threads 10 -c "python3"${tools}"/JSA/jsa.py -f target | anew -q ${output_dir}/url_extract_tmp.txt" &>/dev/null
+	fi
+	[[ -s "${output_dir}/url_extract_tmp.txt" ]] && cat ${output_dir}/url_extract_tmp.txt | grep "${DOMAIN}" | grep "=" | qsreplace -a | grep -aEiv "\.(eot|jpg|jpeg|gif|css|tif|tiff|png|ttf|otf|woff|woff2|ico|pdf|svg|txt|js)$" | anew -q ${output_dir}/url_extract_tmp2.txt
+	[[ -s "${output_dir}/url_extract_tmp2.txt" ]] && cat ${output_dir}/url_extract_tmp2.txt | python3"${tools}"/urless/urless/urless.py | anew -q ${output_dir}/url_extract_uddup.txt
+
+
+}
+
 urlchecks
diff --git a/bin/rftw_web_wafcheck b/bin/rftw_web_wafcheck
--- a/bin/rftw_web_wafcheck
+++ b/bin/rftw_web_wafcheck
@@ -11,40 +11,30 @@ else
     exit 1
 fi
 
-# Help function
-help_menu() {
-	echo "$(basename "$0") [OPTIONS]"
-	echo ""
-	echo "Website's WAF Detection Tool"
-	echo ""
-	echo "Options:"
-	echo "  -h, --help            Show this help menu"
-	echo "  -f, --force           Force the execution even if already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-# Start function
-start_func() {
-	echo "Starting $1: $2..."
-}
-
-# End function
-end_func() {
-	echo "$1"
-	echo "End of $2..."
-}
-
-# Notification function
-notification() {
-	echo "$1"
-}
-
-# Parse arguments
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
+	-f | --file)
+		input_file="$2"
+		shift
 		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
 		echo "Unknown parameter passed: $1"
 		exit 1
@@ -53,19 +43,24 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-if [[ ! -s ".tmp/webs_all.txt" ]]; then
-	anew -q .tmp/webs_all.txt < <(cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null)
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
 fi
-if [[ -s ".tmp/webs_all.txt" ]]; then
-	if [[ ! ${AXIOM} == true ]]; then
-		wafw00f -i .tmp/webs_all.txt -o .tmp/wafs.txt
-	else
-		axiom-scan .tmp/webs_all.txt -m wafw00f -o .tmp/wafs.txt "${AXIOM_EXTRA_ARGS}"
-	fi
-	if [[ -s ".tmp/wafs.txt" ]]; then
-		sed -e 's/^[ \t]*//' -e 's/ \+ /\t/g' -e '/(None)/d' .tmp/wafs.txt | tr -s "\t" ";" >webs/webs_wafs.txt
-		NUMOFLINES=$(sed '/^$/d' webs/webs_wafs.txt | wc -l)
-		notification "${NUMOFLINES} websites protected by waf" info
-		end_func "Results are saved in ${DOMAIN}/webs/webs_wafs.txt" "waf_checks"
-	fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
 fi
+
+mkdir -p .tmp 2>/dev/null
+
+if [[ ! ${AXIOM} == true ]]; then
+	wafw00f -i ${input_file} -o .tmp/wafs.txt
+else
+	axiom-scan ${input_file} -m wafw00f -o .tmp/wafs.txt "${AXIOM_EXTRA_ARGS}"
+fi
+
+sed -e 's/^[ \t]*//' -e 's/ \+ /\t/g' -e '/(None)/d' .tmp/wafs.txt | tr -s "\t" ";" >${output_file}
