subdomain discovery migrated

diff --git a/bin/rftw_sub_permut b/bin/rftw_sub_permut
--- a/bin/rftw_sub_permut
+++ b/bin/rftw_sub_permut
@@ -11,40 +11,69 @@ else
     exit 1
 fi
 
-# Helper function to display usage/help menu
-usage() {
-	echo "$(basename "$0") [OPTIONS]"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
 	echo
-	echo "Options:"
-	echo "  -h, --help          Display this help and exit."
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
 	echo
-	echo "Make sure to set up 'reconftw.cfg' with required environment variables."
+	echo "Example: $0 -d example.com -l /path/to/log"
 	exit 1
 }
 
-# Input validation
-if [[ $# -eq 1 && ($1 == "-h" || $1 == "--help") ]]; then
-	usage
-fi
+# Variables for input and output
+output_file=""
 
-# Check for mandatory variables
-if [[ -z ${SUBPERMUTE} || -z ${called_fn_dir} || -z ${DIFF} ]]; then
-	echo "Mandatory variables not set in the configuration file. Exiting."
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		exit 1
+		;;
+	esac
+	shift
+done
+
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
 	exit 1
 fi
 
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
+
 sub_permut() {
-	if [[ ${DEEP} == true ]] || [[ "$(cat subdomains/subdomains.txt | wc -l)" -le ${DEEP_LIMIT} ]]; then
+	mkdir -p .tmp 2>/dev/null
+	if [[ ${DEEP} == true ]] || [[ "$(cat ${DOMAIN_FILE} | wc -l)" -le ${DEEP_LIMIT} ]]; then
 		if [[ ${PERMUTATIONS_OPTION} == "gotator" ]]; then
-			[[ -s "subdomains/subdomains.txt" ]] && gotator -sub subdomains/subdomains.txt -perm"${tools}"/permutations_list.txt "${GOTATOR_FLAGS}" -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
+			[[ -s "${DOMAIN_FILE}" ]] && gotator -sub ${DOMAIN_FILE} -perm "${tools}"/permutations_list.txt "${GOTATOR_FLAGS}" -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
 		else
-			[[ -s "subdomains/subdomains.txt" ]] && ripgen -d subdomains/subdomains.txt -w"${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
+			[[ -s "${DOMAIN_FILE}" ]] && ripgen -d ${DOMAIN_FILE} -w "${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
 		fi
 	elif [[ "$(cat .tmp/subs_no_resolved.txt | wc -l)" -le ${DEEP_LIMIT2} ]]; then
 		if [[ ${PERMUTATIONS_OPTION} == "gotator" ]]; then
-			[[ -s ".tmp/subs_no_resolved.txt" ]] && gotator -sub .tmp/subs_no_resolved.txt -perm"${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
+			[[ -s ".tmp/subs_no_resolved.txt" ]] && gotator -sub .tmp/subs_no_resolved.txt -perm "${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
 		else
-			[[ -s ".tmp/subs_no_resolved.txt" ]] && ripgen -d .tmp/subs_no_resolved.txt -w"${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
+			[[ -s ".tmp/subs_no_resolved.txt" ]] && ripgen -d .tmp/subs_no_resolved.txt -w "${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1.txt
 		fi
 	else
 		end_subfunc "Skipping Permutations: Too Many Subdomains" ${FUNCNAME[0]}
@@ -59,9 +88,9 @@ sub_permut() {
 	fi
 
 	if [[ $PERMUTATIONS_OPTION == "gotator" ]]; then
-		[[ -s ".tmp/permute1.txt" ]] && gotator -sub .tmp/permute1.txt -perm"${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2.txt
+		[[ -s ".tmp/permute1.txt" ]] && gotator -sub .tmp/permute1.txt -perm "${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2.txt
 	else
-		[[ -s ".tmp/permute1.txt" ]] && ripgen -d .tmp/permute1.txt -w"${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2.txt
+		[[ -s ".tmp/permute1.txt" ]] && ripgen -d .tmp/permute1.txt -w "${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2.txt
 	fi
 
 	if [[ ${AXIOM} != true ]]; then
@@ -69,7 +98,7 @@ sub_permut() {
 	else
 		[[ -s ".tmp/gotator2.txt" ]] && axiom-scan .tmp/gotator2.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" -o .tmp/permute2.txt "${AXIOM_EXTRA_ARGS}"
 	fi
-	cat .tmp/permute1.txt .tmp/permute2.txt | anew -q .tmp/permute_subs.txt
+	cat .tmp/permute1.txt .tmp/permute2.txt | anew -q ${output_file}
 
 }
 
diff --git a/bin/rftw_sub_recbrute b/bin/rftw_sub_recbrute
--- a/bin/rftw_sub_recbrute
+++ b/bin/rftw_sub_recbrute
@@ -11,66 +11,66 @@ else
     exit 1
 fi
 
-function print_help() {
-	echo "$(basename "$0") [-d <domain>] [-h]"
-	echo ""
-	echo "Options:"
-	echo "  -d <domain>     Specify target domain"
-	echo "  -h              Display this help message"
-	echo ""
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
-function start_subfunc() {
-	# This function is just a placeholder as the original function details were not provided.
-	echo "Starting function $1 with message: $2"
-}
+# Variables for input and output
+output_file=""
 
-function end_subfunc() {
-	# This function is just a placeholder as the original function details were not provided.
-	echo "Ending function $2 with result: $1"
-}
-
-function check_inscope() {
-	# Placeholder for check_inscope function
-	echo "Checking inscope for file $1"
-}
-
-function rftw_util_resolver_quick_local() {
-	# Placeholder for rftw_util_resolver_quick_local function
-	echo "Updating local resolvers"
-}
-
-function resolvers_update_quick_axiom() {
-	# Placeholder for resolvers_update_quick_axiom function
-	echo "Updating axiom resolvers"
-}
-
-DOMAIN=""
-while getopts "d:h" option; do
-	case "${option}" in
-	d) DOMAIN=${OPTARG} ;;
-	h)
-		print_help
-		exit 0
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
 		;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
-		print_help
+		echo "Unknown parameter passed: $1"
 		exit 1
 		;;
 	esac
+	shift
 done
 
-if [[ -z ${DOMAIN} ]]; then
-	echo "Error: Domain is required!"
-	print_help
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
 	exit 1
 fi
 
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
+
 # Main function
 sub_recursive_brute() {
-
-	if [[ $(cat subdomains/subdomains.txt | wc -l) -le $DEEP_LIMIT ]]; then
-		[[ ! -s ".tmp/subdomains_recurs_top.txt" ]] && dsieve -if subdomains/subdomains.txt -f 3 -top $DEEP_RECURSIVE_PASSIVE >.tmp/subdomains_recurs_top.txt
+	mkdir -p .tmp 2>/dev/null
+	if [[ $(cat ${DOMAIN_FILE} | wc -l) -le $DEEP_LIMIT ]]; then
+		[[ ! -s ".tmp/subdomains_recurs_top.txt" ]] && dsieve -if ${DOMAIN_FILE} -f 3 -top $DEEP_RECURSIVE_PASSIVE >.tmp/subdomains_recurs_top.txt
 		ripgen -d .tmp/subdomains_recurs_top.txt -w $subs_wordlist >.tmp/brute_recursive_wordlist.txt
 		if [[ ! ${AXIOM} == true ]]; then
 			rftw_util_resolver_quick_local
@@ -81,9 +81,9 @@ sub_recursive_brute() {
 		fi
 		[[ -s ".tmp/brute_recursive_result.txt" ]] && cat .tmp/brute_recursive_result.txt | anew -q .tmp/brute_recursive.txt
 		if [[ $PERMUTATIONS_OPTION == "gotator" ]]; then
-			[[ -s ".tmp/brute_recursive.txt" ]] && gotator -sub .tmp/brute_recursive.txt -perm"${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1_recursive.txt
+			[[ -s ".tmp/brute_recursive.txt" ]] && gotator -sub .tmp/brute_recursive.txt -perm "${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1_recursive.txt
 		else
-			[[ -s ".tmp/brute_recursive.txt" ]] && ripgen -d .tmp/brute_recursive.txt -w"${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1_recursive.txt
+			[[ -s ".tmp/brute_recursive.txt" ]] && ripgen -d .tmp/brute_recursive.txt -w "${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator1_recursive.txt
 		fi
 		if [[ ! ${AXIOM} == true ]]; then
 			[[ -s ".tmp/gotator1_recursive.txt" ]] && puredns resolve .tmp/gotator1_recursive.txt -w .tmp/permute1_recursive.txt -r $resolvers --resolvers-trusted $resolvers_trusted -l $PUREDNS_PUBLIC_LIMIT --rate-limit-trusted $PUREDNS_TRUSTED_LIMIT --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT
@@ -91,9 +91,9 @@ sub_recursive_brute() {
 			[[ -s ".tmp/gotator1_recursive.txt" ]] && axiom-scan .tmp/gotator1_recursive.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/permute1_recursive.txt "${AXIOM_EXTRA_ARGS}"
 		fi
 		if [[ $PERMUTATIONS_OPTION == "gotator" ]]; then
-			[[ -s ".tmp/permute1_recursive.txt" ]] && gotator -sub .tmp/permute1_recursive.txt -perm"${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2_recursive.txt
+			[[ -s ".tmp/permute1_recursive.txt" ]] && gotator -sub .tmp/permute1_recursive.txt -perm "${tools}"/permutations_list.txt $GOTATOR_FLAGS -silent | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2_recursive.txt
 		else
-			[[ -s ".tmp/permute1_recursive.txt" ]] && ripgen -d .tmp/permute1_recursive.txt -w"${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2_recursive.txt
+			[[ -s ".tmp/permute1_recursive.txt" ]] && ripgen -d .tmp/permute1_recursive.txt -w "${tools}"/permutations_list.txt | head -c "${PERMUTATIONS_LIMIT}" >.tmp/gotator2_recursive.txt
 		fi
 		if [[ ! ${AXIOM} == true ]]; then
 			[[ -s ".tmp/gotator2_recursive.txt" ]] && puredns resolve .tmp/gotator2_recursive.txt -w .tmp/permute2_recursive.txt -r $resolvers --resolvers-trusted $resolvers_trusted -l $PUREDNS_PUBLIC_LIMIT --rate-limit-trusted $PUREDNS_TRUSTED_LIMIT --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT
@@ -101,19 +101,13 @@ sub_recursive_brute() {
 			[[ -s ".tmp/gotator2_recursive.txt" ]] && axiom-scan .tmp/gotator2_recursive.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/permute2_recursive.txt "${AXIOM_EXTRA_ARGS}"
 		fi
 		cat .tmp/permute1_recursive.txt .tmp/permute2_recursive.txt | anew -q .tmp/permute_recursive.txt
-	else
-		end_subfunc "skipped in this mode or defined in reconftw.cfg" ${FUNCNAME[0]}
-	fi
-	if [[ ${INSCOPE} == true ]]; then
-		check_inscope .tmp/permute_recursive.txt
-		check_inscope .tmp/brute_recursive.txt
 	fi
 	# Last validation
 	cat .tmp/permute_recursive.txt .tmp/brute_recursive.txt | anew -q .tmp/brute_perm_recursive.txt
 	if [[ ! ${AXIOM} == true ]]; then
-		[[ -s ".tmp/brute_recursive.txt" ]] && puredns resolve .tmp/brute_perm_recursive.txt -w .tmp/brute_perm_recursive_final.txt -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}"
+		[[ -s ".tmp/brute_recursive.txt" ]] && puredns resolve .tmp/brute_perm_recursive.txt -w ${output_file} -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}"
 	else
-		[[ -s ".tmp/brute_recursive.txt" ]] && axiom-scan .tmp/brute_perm_recursive.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/brute_perm_recursive_final.txt "${AXIOM_EXTRA_ARGS}"
+		[[ -s ".tmp/brute_recursive.txt" ]] && axiom-scan .tmp/brute_perm_recursive.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .${output_file} "${AXIOM_EXTRA_ARGS}"
 	fi
 
 }
diff --git a/bin/rftw_sub_recpassive b/bin/rftw_sub_recpassive
--- a/bin/rftw_sub_recpassive
+++ b/bin/rftw_sub_recpassive
@@ -11,64 +11,74 @@ else
     exit 1
 fi
 
-# Helper function to display usage/help menu
-usage() {
-	echo "$(basename "$0") -d domain"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
 	echo
-	echo "Options:"
-	echo "  -d, --domain domain     Specify the domain to perform recursive passive search."
-	echo "  -h, --help              Display this help and exit."
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
 	echo
-	echo "Make sure to set up 'reconftw.cfg' with required environment variables."
+	echo "Example: $0 -d example.com -l /path/to/log"
 	exit 1
 }
 
-# Input validation and parsing
-DOMAIN=""
+# Variables for input and output
+output_file=""
+
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
 	-d | --domain)
 		DOMAIN="$2"
 		shift
 		;;
-	-h | --help) usage ;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
-		echo "Unknown parameter: $1"
-		usage
+		echo "Unknown parameter passed: $1"
+		exit 1
 		;;
 	esac
 	shift
 done
 
-if [[ -z "${DOMAIN}" ]]; then
-	echo "Domain not specified!"
-	usage
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
+	exit 1
 fi
 
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
+
+
 sub_recursive_passive() {
-	if { [[ ! -f "${called_fn_dir}/.${FUNCNAME[0]}" ]] || [[ "$DIFF" = true ]]; } && [[ "$SUB_RECURSIVE_PASSIVE" = true ]] && [[ -s "subdomains/subdomains.txt" ]]; then
-		start_subfunc ${FUNCNAME[0]} "Running : Subdomains recursive search passive"
-		# Passive recursive
-		[[ -s "subdomains/subdomains.txt" ]] && dsieve -if subdomains/subdomains.txt -f 3 -top $DEEP_RECURSIVE_PASSIVE >.tmp/subdomains_recurs_top.txt
-		if [[ ! ${AXIOM} = true ]]; then
-			rftw_util_resolver_quick_local
-			[[ -s ".tmp/subdomains_recurs_top.txt" ]] && timeout -k 1m ${AMASS_ENUM_TIMEOUT}m amass enum -passive -df .tmp/subdomains_recurs_top.txt -nf subdomains/subdomains.txt -config $AMASS_CONFIG -timeout $AMASS_ENUM_TIMEOUT | anew -q .tmp/passive_recursive.txt
-			[[ -s ".tmp/passive_recursive.txt" ]] && puredns resolve .tmp/passive_recursive.txt -w .tmp/passive_recurs_tmp.txt -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}"
-		else
-			rftw_util_resolver_quick_axiom
-			[[ -s ".tmp/subdomains_recurs_top.txt" ]] && axiom-scan .tmp/subdomains_recurs_top.txt -m amass -passive -o .tmp/amass_prec.txt "${AXIOM_EXTRA_ARGS}"
-			[[ -s ".tmp/amass_prec.txt" ]] && cat .tmp/amass_prec.txt | anew -q .tmp/passive_recursive.txt
-			[[ -s ".tmp/passive_recursive.txt" ]] && axiom-scan .tmp/passive_recursive.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/passive_recurs_tmp.txt "${AXIOM_EXTRA_ARGS}"
-		fi
-		[[ ${INSCOPE} == true ]] && check_inscope .tmp/passive_recurs_tmp.txt
-		NUMOFLINES=$(cat .tmp/passive_recurs_tmp.txt | grep "\.$DOMAIN$\|^$DOMAIN$" | sed '/^$/d' | anew subdomains/subdomains.txt | wc -l)
-		end_subfunc "${NUMOFLINES} new subs (recursive)" ${FUNCNAME[0]}
+	mkdir -p .tmp 2>/dev/null
+	[[ -s "${DOMAIN_FILE}" ]] && dsieve -if ${DOMAIN_FILE} -f 3 -top $DEEP_RECURSIVE_PASSIVE >.tmp/subdomains_recurs_top.txt
+	if [[ ! ${AXIOM} = true ]]; then
+		rftw_util_resolver_quick_local
+		[[ -s ".tmp/subdomains_recurs_top.txt" ]] && timeout -k 1m ${AMASS_ENUM_TIMEOUT}m amass enum -passive -df .tmp/subdomains_recurs_top.txt -nf ${DOMAIN_FILE} -config $AMASS_CONFIG -timeout $AMASS_ENUM_TIMEOUT | anew -q .tmp/passive_recursive.txt
+		[[ -s ".tmp/passive_recursive.txt" ]] && puredns resolve .tmp/passive_recursive.txt -w ${output_file} -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}"
 	else
-		if [[ "$SUB_RECURSIVE_PASSIVE" = false ]]; then
-			printf "\n${yellow} ${FUNCNAME[0]} skipped in this mode or defined in reconftw.cfg ${reset}\n"
-		else
-			printf "${yellow} ${FUNCNAME[0]} is already processed, to force executing ${FUNCNAME[0]} delete\n    $called_fn_dir/.${FUNCNAME[0]} ${reset}\n\n"
-		fi
+		rftw_util_resolver_quick_axiom
+		[[ -s ".tmp/subdomains_recurs_top.txt" ]] && axiom-scan .tmp/subdomains_recurs_top.txt -m amass -passive -o .tmp/amass_prec.txt "${AXIOM_EXTRA_ARGS}"
+		[[ -s ".tmp/amass_prec.txt" ]] && cat .tmp/amass_prec.txt | anew -q .tmp/passive_recursive.txt
+		[[ -s ".tmp/passive_recursive.txt" ]] && axiom-scan .tmp/passive_recursive.txt -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o ${output_file} "${AXIOM_EXTRA_ARGS}"
 	fi
 }
 
diff --git a/bin/rftw_sub_regex b/bin/rftw_sub_regex
--- a/bin/rftw_sub_regex
+++ b/bin/rftw_sub_regex
@@ -11,47 +11,78 @@ else
     exit 1
 fi
 
-# Helper function to display usage/help menu
-usage() {
-    echo "$(basename "$0") [OPTIONS]"
-    echo
-    echo "Options:"
-    echo "  -h, --help          Display this help and exit."
-    echo
-    echo "Make sure to set up 'reconftw.cfg' with required environment variables."
-    exit 1
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
+# Variables for input and output
+output_file=""
+
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		exit 1
+		;;
+	esac
+	shift
+done
+
 # Input validation
-if [[ "$#" -eq 1 && ("$1" == "-h" || "$1" == "--help") ]]; then
-    usage
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
+	exit 1
 fi
 
-# Check for mandatory variables
-if [[ -z "$SUBREGEXPERMUTE" || -z "$called_fn_dir" || -z "$DIFF" ]]; then
-    echo "Mandatory variables not set in the configuration file. Exiting."
-    exit 1
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
 fi
+
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
 
 sub_regex_permut() {
-		cd "${tools}/regulator" || { echo "Failed to cd directory in ${FUNCNAME[0]} @ line ${LINENO}"; exit 1; }
-		python3 main.py -t "${DOMAIN}" -f ${dir}/subdomains/subdomains.txt -o ${dir}/.tmp/${DOMAIN}.brute
-		cd "${dir}" || { echo "Failed to cd to $dir in ${FUNCNAME[0]} @ line ${LINENO}"; exit 1; }
+		pushd "${tools}/regulator" &>/dev/null || {
+            echo "Failed to cd to regulator"
+            exit 1
+        }
+        python3 main.py -t "${DOMAIN}" -f ${DOMAIN_FILE} -o ${dir}/.tmp/${DOMAIN}.brute
+        popd &>/dev/null || {
+            echo "Failed to cd back"
+            exit 1
+        }
 
 		if [[ ! ${AXIOM} = true ]]; then
 			rftw_util_resolver_quick_local
-			[[ -s ".tmp/${DOMAIN}.brute" ]] && puredns resolve .tmp/${DOMAIN}.brute -w .tmp/regulator.txt -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}"
+			[[ -s ".tmp/${DOMAIN}.brute" ]] && puredns resolve .tmp/${DOMAIN}.brute -w ${output_file} -r "${resolvers}" --resolvers-trusted "${resolvers_trusted}" -l "${PUREDNS_PUBLIC_LIMIT}" --rate-limit-trusted "${PUREDNS_TRUSTED_LIMIT}" --wildcard-tests "${PUREDNS_WILDCARDTEST_LIMIT}" --wildcard-batch "${PUREDNS_WILDCARDBATCH_LIMIT}"
 		else
 			rftw_util_resolver_quick_axiom
-			[[ -s ".tmp/${DOMAIN}.brute" ]] && axiom-scan .tmp/${DOMAIN}.brute -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o .tmp/regulator.txt "${AXIOM_EXTRA_ARGS}"
-		fi
-		
-		if [[ -s ".tmp/regulator.txt" ]]; then
-			[[ -s "$outOfScope_file" ]] && deleteOutScoped $outOfScope_file .tmp/regulator.txt
-			[[ "${INSCOPE}" = true ]] && check_inscope .tmp/regulator.txt
-			NUMOFLINES=$(cat .tmp/regulator.txt | grep ".$DOMAIN$" | anew subdomains/subdomains.txt | sed '/^$/d' | wc -l)
-		else
-			NUMOFLINES=0
+			[[ -s ".tmp/${DOMAIN}.brute" ]] && axiom-scan .tmp/${DOMAIN}.brute -m puredns-resolve -r /home/op/lists/resolvers.txt --resolvers-trusted /home/op/lists/resolvers_trusted.txt --wildcard-tests $PUREDNS_WILDCARDTEST_LIMIT --wildcard-batch $PUREDNS_WILDCARDBATCH_LIMIT -o ${output_file} "${AXIOM_EXTRA_ARGS}"
 		fi
 }
 
diff --git a/bin/rftw_sub_s3buckets b/bin/rftw_sub_s3buckets
--- a/bin/rftw_sub_s3buckets
+++ b/bin/rftw_sub_s3buckets
@@ -11,71 +11,71 @@ else
     exit 1
 fi
 
-help_menu() {
-    echo "$(basename "$0") [DOMAIN] [OPTIONS]"
-    echo "AWS S3 buckets and cloud assets checker."
-    echo
-    echo "Options:"
-    echo "  -h, --help   Display this help menu and exit"
-    echo "  -f, --force  Force the execution even if it was already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
-validate_inputs() {
-    if [[ -z "${DOMAIN}" ]]; then
-        echo -e "${yellow} No domain provided! ${reset}"
-        exit 1
-    fi
+# Variables for input and output
+output_file=""
 
-    if [[ "${DOMAIN}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9] ]]; then
-        echo -e "${yellow} Invalid domain format: IP address provided instead of a domain name ${reset}"
-        exit 1
-    fi
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		exit 1
+		;;
+	esac
+	shift
+done
 
-    if [[ "$S3BUCKETS" != true ]] && [[ "$FORCE_EXECUTION" != true ]]; then
-        echo -e "${yellow} s3buckets skipped in this mode or defined in reconftw.cfg ${reset}"
-        exit 0
-    fi
-}
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
 
 run_s3buckets() {
-    start_func "s3buckets" "AWS S3 buckets search"
-    # S3Scanner
     if [[ ! ${AXIOM} = true ]]; then
-        [[ -s "subdomains/subdomains.txt" ]] && s3scanner scan -f subdomains/subdomains.txt | anew -q .tmp/s3buckets.txt
+        [[ -s "${DOMAIN_FILE}" ]] && s3scanner scan -f ${DOMAIN_FILE} | anew -q .tmp/s3buckets.txt
     else
-        axiom-scan subdomains/subdomains.txt -m s3scanner -o .tmp/s3buckets_tmp.txt "${AXIOM_EXTRA_ARGS}"
-        [[ -s ".tmp/s3buckets_tmp.txt" ]] && cat .tmp/s3buckets_tmp.txt .tmp/s3buckets_tmp2.txt | anew -q .tmp/s3buckets.txt && sed -i '/^$/d' .tmp/s3buckets.txt
+        axiom-scan ${DOMAIN_FILE} -m s3scanner -o .tmp/s3buckets_tmp.txt "${AXIOM_EXTRA_ARGS}"
+        [[ -s ".tmp/s3buckets_tmp.txt" ]] && cat .tmp/s3buckets_tmp.txt .tmp/s3buckets_tmp2.txt | anew -q .tmp/s3buckets.txt && sed -i '/^$/d' ${output_dir}/s3buckets.txt
     fi
     # Cloudenum
     keyword=${DOMAIN%%.*}
-    python3 ~/Tools/cloud_enum/cloud_enum.py -k $keyword -qs -l .tmp/output_cloud.txt
-
-    NUMOFLINES1=$(cat .tmp/output_cloud.txt | sed '/^#/d' | sed '/^$/d' | anew subdomains/cloud_assets.txt | wc -l)
-    if [[ "$NUMOFLINES1" -gt 0 ]]; then
-        notification "${NUMOFLINES1} new cloud assets found" info
-    fi
-
-    NUMOFLINES2=$(cat .tmp/s3buckets.txt | grep -aiv "not_exist" | grep -aiv "Warning:" | grep -aiv "invalid_name" | grep -aiv "^http" | awk 'NF' | anew subdomains/s3buckets.txt | sed '/^$/d' | wc -l)
-    if [[ "$NUMOFLINES2" -gt 0 ]]; then
-        notification "${NUMOFLINES2} new S3 buckets found" info
-    fi
-
-    end_func "Results are saved in subdomains/s3buckets.txt and subdomains/cloud_assets.txt" "s3buckets"
+    python3 ~/Tools/cloud_enum/cloud_enum.py -k $keyword -qs -l ${output_dir}/output_cloud.txt
 }
 
-# Main
-FORCE_EXECUTION=false
-DOMAIN="$1"
-
-shift
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -h|--help) help_menu; exit 0 ;;
-        -f|--force) FORCE_EXECUTION=true; shift ;;
-        *) echo "Unknown parameter passed: $1"; exit 1 ;;
-    esac
-    shift
-done
-
-validate_inputs
 run_s3buckets
diff --git a/bin/rftw_sub_takeover b/bin/rftw_sub_takeover
--- a/bin/rftw_sub_takeover
+++ b/bin/rftw_sub_takeover
@@ -10,59 +10,74 @@ else
     echo "Error: reconftw.cfg not found at ${CONFIG_PATH}!"
     exit 1
 fi
-
-help_menu() {
-    echo "$(basename "$0") [OPTIONS]"
-    echo "Subdomain and DNS takeover checker."
-    echo
-    echo "Options:"
-    echo "  -h, --help   Display this help menu and exit"
-    echo "  -f, --force  Force the execution even if it was already processed"
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
+	echo
+	echo "  -d, --domain            Target for subdomain enumeration (Required)"
+	echo "  -f, --file              File containing domains for subdomain enumeration (Required)"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -d example.com -l /path/to/log"
+	exit 1
 }
 
-validate_inputs() {
-    if [[ "$SUBTAKEOVER" != true ]] && [[ "$FORCE_EXECUTION" != true ]]; then
-        echo -e "${yellow} subtakeover skipped in this mode or defined in reconftw.cfg ${reset}"
-        exit 0
-    fi
-}
+# Variables for input and output
+output_file=""
 
-run_subtakeover() {
-    start_func ${FUNCNAME[0]} "Looking for possible subdomain and DNS takeover"
-		touch .tmp/tko.txt
-		[[ ! -s ".tmp/webs_all.txt" ]] && cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null | anew -q .tmp/webs_all.txt
-		if [[ ! ${AXIOM} = true ]]; then
-			nuclei -update
-			cat subdomains/subdomains.txt .tmp/webs_all.txt 2>/dev/null | nuclei -silent -nh -tags takeover -severity info,low,medium,high,critical -retries 3 -rl $NUCLEI_RATELIMIT -t ${NUCLEI_TEMPLATES_PATH} -o .tmp/tko.txt
-		else
-			cat subdomains/subdomains.txt .tmp/webs_all.txt | sed '/^$/d' | anew -q .tmp/webs_subs.txt
-			[[ -s ".tmp/webs_subs.txt" ]] && axiom-scan .tmp/webs_subs.txt -m nuclei --nuclei-templates ${NUCLEI_TEMPLATES_PATH} -tags takeover -nh -severity info,low,medium,high,critical -retries 3 -rl $NUCLEI_RATELIMIT -t ${NUCLEI_TEMPLATES_PATH} -o .tmp/tko.txt "${AXIOM_EXTRA_ARGS}"
-		fi
-
-		# DNS_TAKEOVER
-		cat .tmp/subs_no_resolved.txt .tmp/subdomains_dns.txt .tmp/scrap_subs.txt .tmp/analytics_subs_clean.txt .tmp/passive_recursive.txt 2>/dev/null | anew -q .tmp/subs_dns_tko.txt
-		cat .tmp/subs_dns_tko.txt 2>/dev/null | dnstake -c $DNSTAKE_THREADS -s | sed '/^$/d' | anew -q .tmp/tko.txt
-
-		sed -i '/^$/d' .tmp/tko.txt
-
-		NUMOFLINES=$(cat .tmp/tko.txt | anew webs/takeover.txt | sed '/^$/d' | wc -l)
-		if [[ "$NUMOFLINES" -gt 0 ]]; then
-			notification "${NUMOFLINES} new possible takeovers found" info
-		fi
-		end_func "Results are saved in ${DOMAIN}/webs/takeover.txt" ${FUNCNAME[0]}
-}
-
-# Main
-FORCE_EXECUTION=false
-
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        -h|--help) help_menu; exit 0 ;;
-        -f|--force) FORCE_EXECUTION=true; shift ;;
-        *) echo "Unknown parameter passed: $1"; exit 1 ;;
-    esac
-    shift
+# Parse input arguments
+while [[ $# -gt 0 ]]; do
+	case $1 in
+	-d | --domain)
+		DOMAIN="$2"
+		shift
+		;;
+	-f | --file)
+		DOMAIN_FILE="$2"
+		shift
+		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
+	*)
+		echo "Unknown parameter passed: $1"
+		exit 1
+		;;
+	esac
+	shift
 done
 
-validate_inputs
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]] || [[ -z ${DOMAIN} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]] || [[ ! -r ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+# Validate domain
+rftw_util_validatedomain "${DOMAIN}" || exit 1 # Domain validation
+
+run_subtakeover() {
+
+	mkdir -p .tmp 2>/dev/null
+	if [[ ! ${AXIOM} = true ]]; then
+		nuclei -update
+		cat ${DOMAIN_FILE} | nuclei -silent -nh -tags takeover -severity info,low,medium,high,critical -retries 3 -rl $NUCLEI_RATELIMIT -t ${NUCLEI_TEMPLATES_PATH} -o .tmp/tko.txt
+	else
+		cat ${DOMAIN_FILE} | sed '/^$/d' | anew -q .tmp/webs_subs.txt
+		[[ -s ".tmp/webs_subs.txt" ]] && axiom-scan .tmp/webs_subs.txt -m nuclei --nuclei-templates ${NUCLEI_TEMPLATES_PATH} -tags takeover -nh -severity info,low,medium,high,critical -retries 3 -rl $NUCLEI_RATELIMIT -t ${NUCLEI_TEMPLATES_PATH} -o .tmp/tko.txt "${AXIOM_EXTRA_ARGS}"
+	fi
+	# DNS_TAKEOVER
+	cat .tmp/subs_no_resolved.txt .tmp/subdomains_dns.txt .tmp/scrap_subs.txt .tmp/analytics_subs_clean.txt .tmp/passive_recursive.txt 2>/dev/null | anew -q .tmp/subs_dns_tko.txt
+	cat .tmp/subs_dns_tko.txt 2>/dev/null | dnstake -c $DNSTAKE_THREADS -s | sed '/^$/d' | anew -q ${output_file}
+	sed -i '/^$/d' ${output_file}
+}
+
 run_subtakeover
diff --git a/bin/rftw_web_probecommon b/bin/rftw_web_probecommon
--- a/bin/rftw_web_probecommon
+++ b/bin/rftw_web_probecommon
@@ -11,64 +11,30 @@ else
     exit 1
 fi
 
-help_menu() {
-	echo "$(basename "$0") [DOMAIN] [OPTIONS]"
-	echo "Web probing tool for specified domain."
+# Help menu
+display_help() {
+	echo "$(basename "$0") [Options]"
 	echo
-	echo "Options:"
-	echo "  -h, --help   Display this help menu and exit"
-	echo "  -f, --force  Force the execution even if it was already processed"
+	echo "  -f, --file              File containing domains for web probing"
+	echo "  -o, --output            Output file location"
+	echo "  -h, --help              Display this help and exit"
+	echo
+	echo "Example: $0 -f input.txt -o output.txt"
+	exit 1
 }
 
-validate_inputs() {
-	if [[ -z ${DOMAIN} ]]; then
-		echo -e "${yellow} No domain provided! ${reset}"
-		exit 1
-	fi
-
-	if [[ $WEBPROBESIMPLE != true ]] && [[ $FORCE_EXECUTION != true ]]; then
-		echo -e "${yellow} webprobe_simple skipped in this mode or defined in reconftw.cfg ${reset}"
-		exit 0
-	fi
-}
-
-run_webprobe_simple() {
-	start_subfunc "webprobe_simple" "Running : Http probing${DOMAIN}/"
-	if [[ ! ${AXIOM} == true ]]; then
-		cat subdomains/subdomains.txt | httpx ${HTTPX_FLAGS} -no-color -json -random-agent -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -retries 2 -timeout $HTTPX_TIMEOUT -o .tmp/web_full_info_probe.txt
-	else
-		axiom-scan subdomains/subdomains.txt -m httpx ${HTTPX_FLAGS} -no-color -json -random-agent -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -retries 2 -timeout $HTTPX_TIMEOUT -o .tmp/web_full_info_probe.txt "${AXIOM_EXTRA_ARGS}"
-	fi
-
-	cat .tmp/web_full_info.txt .tmp/web_full_info_probe.txt webs/web_full_info.txt | jq -s 'try .' | jq 'try unique_by(.input)' | jq 'try .[]' >webs/web_full_info.txt
-	[[ -s "webs/web_full_info.txt" ]] && cat webs/web_full_info.txt | jq -r 'try .url' 2>/dev/null | grep "${DOMAIN}" | sed "s/*.//" | anew -q .tmp/probed_tmp.txt
-	[[ -s "webs/web_full_info.txt" ]] && cat webs/web_full_info.txt | jq -r 'try . |"\(.url) [\(.status_code)] [\(.title)] [\(.webserver)] \(.tech)"' | grep "${DOMAIN}" | anew -q webs/web_full_info_plain.txt
-	[[ -s $outOfScope_file ]] && deleteOutScoped $outOfScope_file .tmp/probed_tmp.txt
-	NUMOFLINES=$(cat .tmp/probed_tmp.txt | anew webs/webs.txt | sed '/^$/d' | wc -l)
-	cat webs/webs.txt webs/webs_uncommon_ports.txt 2>/dev/null | anew -q .tmp/webs_all.txt
-	end_subfunc "${NUMOFLINES} new websites resolved" "webprobe_simple"
-
-	if [[ $PROXY == true ]] && [[ -n $proxy_url ]] && [[ $(cat webs/webs.txt | wc -l) -le $DEEP_LIMIT2 ]]; then
-		notification "Sending websites to proxy" info
-		ffuf -mc all -w webs/webs.txt -u FUZZ -replay-proxy $proxy_url
-	fi
-}
-
-# Main
-FORCE_EXECUTION=false
-DOMAIN="$1"
-
-shift
+# Parse input arguments
 while [[ $# -gt 0 ]]; do
 	case $1 in
-	-h | --help)
-		help_menu
-		exit 0
-		;;
-	-f | --force)
-		FORCE_EXECUTION=true
+	-f | --file)
+		input_file="$2"
 		shift
 		;;
+	-o | --output)
+		output_file="$2"
+		shift
+		;;
+	-h | --help) display_help ;;
 	*)
 		echo "Unknown parameter passed: $1"
 		exit 1
@@ -77,5 +43,28 @@ while [[ $# -gt 0 ]]; do
 	shift
 done
 
-validate_inputs
+# Input validation
+if [[ -z ${DOMAIN_FILE} ]]; then
+	display_help
+	exit 1
+fi
+
+# Validate file
+if [[ ! -f ${DOMAIN_FILE} ]]; then
+	echo "Error: Specified file does not exist or is not readable."
+	exit 1
+fi
+
+
+run_webprobe_simple() {
+
+	mkdir -p .tmp 2>/dev/null
+	if [[ ! ${AXIOM} == true ]]; then
+		cat ${input_file} | httpx ${HTTPX_FLAGS} -no-color -json -random-agent -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -retries 2 -timeout $HTTPX_TIMEOUT -o ${output_file}
+	else
+		rftw_util_resolver_quick_axiom
+		axiom-scan ${input_file} -m httpx ${HTTPX_FLAGS} -no-color -json -random-agent -threads $HTTPX_THREADS -rl $HTTPX_RATELIMIT -retries 2 -timeout $HTTPX_TIMEOUT -o ${output_file} "${AXIOM_EXTRA_ARGS}"
+	fi
+}
+
 run_webprobe_simple
